// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAttemptEvent = `-- name: AppendAttemptEvent :exec
insert into attempt_event (org_id, attempt_id, seq, kind, payload, client_ts, problem_id, server_ts)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AppendAttemptEventParams struct {
	OrgID     uuid.UUID
	AttemptID uuid.UUID
	Seq       int64
	Kind      string
	Payload   []byte
	ClientTs  pgtype.Timestamptz
	ProblemID uuid.NullUUID
	ServerTs  pgtype.Timestamptz
}

func (q *Queries) AppendAttemptEvent(ctx context.Context, arg AppendAttemptEventParams) error {
	_, err := q.db.Exec(ctx, appendAttemptEvent,
		arg.OrgID,
		arg.AttemptID,
		arg.Seq,
		arg.Kind,
		arg.Payload,
		arg.ClientTs,
		arg.ProblemID,
		arg.ServerTs,
	)
	return err
}

const closeAttempt = `-- name: CloseAttempt :one
update attempt set status = $2, finished_at = $3, updated_at = now()
where id = $1 and status = 'started' returning id, org_id, application_id, assessment_id, stage_id, status, invited_at, invite_expires_at, started_at, expires_at, finished_at, score, risk_score, recording_status, recording_blob_key, created_at, updated_at, last_event_seq, problem_scores, error_count
`

type CloseAttemptParams struct {
	ID         uuid.UUID
	Status     string
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) CloseAttempt(ctx context.Context, arg CloseAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, closeAttempt, arg.ID, arg.Status, arg.FinishedAt)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.AssessmentID,
		&i.StageID,
		&i.Status,
		&i.InvitedAt,
		&i.InviteExpiresAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.Score,
		&i.RiskScore,
		&i.RecordingStatus,
		&i.RecordingBlobKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEventSeq,
		&i.ProblemScores,
		&i.ErrorCount,
	)
	return i, err
}

const countAssessmentProblems = `-- name: CountAssessmentProblems :many
select assessment_id, count(*)::int as n from assessment_problem where org_id = $1 group by assessment_id
`

type CountAssessmentProblemsRow struct {
	AssessmentID uuid.UUID
	N            int32
}

func (q *Queries) CountAssessmentProblems(ctx context.Context, orgID uuid.UUID) ([]CountAssessmentProblemsRow, error) {
	rows, err := q.db.Query(ctx, countAssessmentProblems, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAssessmentProblemsRow{}
	for rows.Next() {
		var i CountAssessmentProblemsRow
		if err := rows.Scan(&i.AssessmentID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAttemptEvents = `-- name: CountAttemptEvents :one
select count(*) from attempt_event where attempt_id = $1
`

func (q *Queries) CountAttemptEvents(ctx context.Context, attemptID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttemptEvents, attemptID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAttemptSubmissionErrors = `-- name: CountAttemptSubmissionErrors :one
select count(*) from submission where attempt_id = $1 and status = 'error'
`

func (q *Queries) CountAttemptSubmissionErrors(ctx context.Context, attemptID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttemptSubmissionErrors, attemptID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAttemptsForAssessment = `-- name: CountAttemptsForAssessment :one
select count(*) from attempt where assessment_id = $1
`

func (q *Queries) CountAttemptsForAssessment(ctx context.Context, assessmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttemptsForAssessment, assessmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingSubmissions = `-- name: CountPendingSubmissions :one
select count(*) from submission where attempt_id = $1 and problem_id = $2 and status in ('queued', 'running')
`

type CountPendingSubmissionsParams struct {
	AttemptID uuid.UUID
	ProblemID uuid.UUID
}

func (q *Queries) CountPendingSubmissions(ctx context.Context, arg CountPendingSubmissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSubmissions, arg.AttemptID, arg.ProblemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssessment = `-- name: CreateAssessment :one
insert into assessment (org_id, name, duration_minutes, language_override, invite_window_days)
values ($1, $2, $3, $4, $5) returning id, org_id, name, duration_minutes, language_override, invite_window_days, created_at, updated_at
`

type CreateAssessmentParams struct {
	OrgID            uuid.UUID
	Name             string
	DurationMinutes  int32
	LanguageOverride *string
	InviteWindowDays int32
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.OrgID,
		arg.Name,
		arg.DurationMinutes,
		arg.LanguageOverride,
		arg.InviteWindowDays,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DurationMinutes,
		&i.LanguageOverride,
		&i.InviteWindowDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssessmentProblem = `-- name: CreateAssessmentProblem :exec
insert into assessment_problem (assessment_id, org_id, problem_id, position) values ($1, $2, $3, $4)
`

type CreateAssessmentProblemParams struct {
	AssessmentID uuid.UUID
	OrgID        uuid.UUID
	ProblemID    uuid.UUID
	Position     int32
}

func (q *Queries) CreateAssessmentProblem(ctx context.Context, arg CreateAssessmentProblemParams) error {
	_, err := q.db.Exec(ctx, createAssessmentProblem,
		arg.AssessmentID,
		arg.OrgID,
		arg.ProblemID,
		arg.Position,
	)
	return err
}

const createAttempt = `-- name: CreateAttempt :one
insert into attempt (org_id, application_id, assessment_id, stage_id, invite_expires_at)
values ($1, $2, $3, $4, $5) returning id, org_id, application_id, assessment_id, stage_id, status, invited_at, invite_expires_at, started_at, expires_at, finished_at, score, risk_score, recording_status, recording_blob_key, created_at, updated_at, last_event_seq, problem_scores, error_count
`

type CreateAttemptParams struct {
	OrgID           uuid.UUID
	ApplicationID   uuid.UUID
	AssessmentID    uuid.UUID
	StageID         uuid.UUID
	InviteExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.OrgID,
		arg.ApplicationID,
		arg.AssessmentID,
		arg.StageID,
		arg.InviteExpiresAt,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.AssessmentID,
		&i.StageID,
		&i.Status,
		&i.InvitedAt,
		&i.InviteExpiresAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.Score,
		&i.RiskScore,
		&i.RecordingStatus,
		&i.RecordingBlobKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEventSeq,
		&i.ProblemScores,
		&i.ErrorCount,
	)
	return i, err
}

const createIntegritySignal = `-- name: CreateIntegritySignal :exec
insert into integrity_signal (org_id, attempt_id, name, value, weight, confidence, evidence)
values ($1, $2, $3, $4, $5, $6, $7)
`

type CreateIntegritySignalParams struct {
	OrgID      uuid.UUID
	AttemptID  uuid.UUID
	Name       string
	Value      pgtype.Numeric
	Weight     pgtype.Numeric
	Confidence string
	Evidence   []byte
}

func (q *Queries) CreateIntegritySignal(ctx context.Context, arg CreateIntegritySignalParams) error {
	_, err := q.db.Exec(ctx, createIntegritySignal,
		arg.OrgID,
		arg.AttemptID,
		arg.Name,
		arg.Value,
		arg.Weight,
		arg.Confidence,
		arg.Evidence,
	)
	return err
}

const createProblem = `-- name: CreateProblem :one
insert into problem (org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) returning id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at
`

type CreateProblemParams struct {
	OrgID            uuid.UUID
	Kind             string
	Title            string
	Statement        string
	Difficulty       string
	Tags             []string
	AllowedLanguages []string
	TimeLimitMs      int32
	MemoryLimitKb    int32
	SqlSchema        *string
	SqlSeed          *string
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.OrgID,
		arg.Kind,
		arg.Title,
		arg.Statement,
		arg.Difficulty,
		arg.Tags,
		arg.AllowedLanguages,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.SqlSchema,
		arg.SqlSeed,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Title,
		&i.Statement,
		&i.Difficulty,
		&i.Tags,
		&i.AllowedLanguages,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.SqlSchema,
		&i.SqlSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProblemReference = `-- name: CreateProblemReference :one
insert into problem_reference (org_id, problem_id, language, source)
values ($1, $2, $3, $4) returning id, org_id, problem_id, language, source
`

type CreateProblemReferenceParams struct {
	OrgID     uuid.UUID
	ProblemID uuid.UUID
	Language  string
	Source    string
}

func (q *Queries) CreateProblemReference(ctx context.Context, arg CreateProblemReferenceParams) (ProblemReference, error) {
	row := q.db.QueryRow(ctx, createProblemReference,
		arg.OrgID,
		arg.ProblemID,
		arg.Language,
		arg.Source,
	)
	var i ProblemReference
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProblemID,
		&i.Language,
		&i.Source,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
insert into submission (org_id, attempt_id, problem_id, kind, language, source)
values ($1, $2, $3, $4, $5, $6) returning id, org_id, attempt_id, problem_id, kind, language, source, status, result, score, created_at, updated_at
`

type CreateSubmissionParams struct {
	OrgID     uuid.UUID
	AttemptID uuid.UUID
	ProblemID uuid.UUID
	Kind      string
	Language  string
	Source    string
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.OrgID,
		arg.AttemptID,
		arg.ProblemID,
		arg.Kind,
		arg.Language,
		arg.Source,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AttemptID,
		&i.ProblemID,
		&i.Kind,
		&i.Language,
		&i.Source,
		&i.Status,
		&i.Result,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTestCase = `-- name: CreateTestCase :one
insert into test_case (org_id, problem_id, position, input, expected_output, visibility, weight, unordered)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, org_id, problem_id, position, input, expected_output, visibility, weight, unordered
`

type CreateTestCaseParams struct {
	OrgID          uuid.UUID
	ProblemID      uuid.UUID
	Position       int32
	Input          string
	ExpectedOutput string
	Visibility     string
	Weight         pgtype.Numeric
	Unordered      bool
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.OrgID,
		arg.ProblemID,
		arg.Position,
		arg.Input,
		arg.ExpectedOutput,
		arg.Visibility,
		arg.Weight,
		arg.Unordered,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProblemID,
		&i.Position,
		&i.Input,
		&i.ExpectedOutput,
		&i.Visibility,
		&i.Weight,
		&i.Unordered,
	)
	return i, err
}

const deleteAssessment = `-- name: DeleteAssessment :execrows
delete from assessment where id = $1 and org_id = $2
`

type DeleteAssessmentParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteAssessment(ctx context.Context, arg DeleteAssessmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssessment, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAssessmentProblems = `-- name: DeleteAssessmentProblems :exec
delete from assessment_problem where assessment_id = $1
`

func (q *Queries) DeleteAssessmentProblems(ctx context.Context, assessmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessmentProblems, assessmentID)
	return err
}

const deleteIntegritySignals = `-- name: DeleteIntegritySignals :exec
delete from integrity_signal where attempt_id = $1
`

func (q *Queries) DeleteIntegritySignals(ctx context.Context, attemptID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIntegritySignals, attemptID)
	return err
}

const deleteProblem = `-- name: DeleteProblem :execrows
delete from problem where id = $1 and org_id = $2
`

type DeleteProblemParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteProblem(ctx context.Context, arg DeleteProblemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProblem, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProblemReferences = `-- name: DeleteProblemReferences :exec
delete from problem_reference where problem_id = $1
`

func (q *Queries) DeleteProblemReferences(ctx context.Context, problemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProblemReferences, problemID)
	return err
}

const deleteTestCases = `-- name: DeleteTestCases :exec
delete from test_case where problem_id = $1
`

func (q *Queries) DeleteTestCases(ctx context.Context, problemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTestCases, problemID)
	return err
}

const extendMagicLinkExpiry = `-- name: ExtendMagicLinkExpiry :exec
update magic_link set expires_at = greatest(expires_at, $3)
where purpose = $1 and subject_id = $2 and revoked_at is null
`

type ExtendMagicLinkExpiryParams struct {
	Purpose   string
	SubjectID uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

// Only ever extends: a link is never cut short by the attempt it opens.
func (q *Queries) ExtendMagicLinkExpiry(ctx context.Context, arg ExtendMagicLinkExpiryParams) error {
	_, err := q.db.Exec(ctx, extendMagicLinkExpiry, arg.Purpose, arg.SubjectID, arg.ExpiresAt)
	return err
}

const filterProblems = `-- name: FilterProblems :many
select id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at from problem
where ($1::text = '' or kind = $1::text)
  and ($2::text = '' or difficulty = $2::text)
  and ($3::text = '' or $3::text = any(tags))
  and ($4::text = '' or title ilike '%' || $4::text || '%')
order by title
limit $5::int
`

type FilterProblemsParams struct {
	Kind       string
	Difficulty string
	Tag        string
	Query      string
	RowLimit   int32
}

// RLS shows the caller's own problems and the platform seed; the filters are
// all optional, an empty string meaning "any".
func (q *Queries) FilterProblems(ctx context.Context, arg FilterProblemsParams) ([]Problem, error) {
	rows, err := q.db.Query(ctx, filterProblems,
		arg.Kind,
		arg.Difficulty,
		arg.Tag,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Title,
			&i.Statement,
			&i.Difficulty,
			&i.Tags,
			&i.AllowedLanguages,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.SqlSchema,
			&i.SqlSeed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishSubmission = `-- name: FinishSubmission :exec
update submission set status = $2, result = $3, score = $4, updated_at = now() where id = $1
`

type FinishSubmissionParams struct {
	ID     uuid.UUID
	Status string
	Result []byte
	Score  pgtype.Numeric
}

func (q *Queries) FinishSubmission(ctx context.Context, arg FinishSubmissionParams) error {
	_, err := q.db.Exec(ctx, finishSubmission,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.Score,
	)
	return err
}

const getAssessment = `-- name: GetAssessment :one
select id, org_id, name, duration_minutes, language_override, invite_window_days, created_at, updated_at from assessment where id = $1
`

func (q *Queries) GetAssessment(ctx context.Context, id uuid.UUID) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessment, id)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DurationMinutes,
		&i.LanguageOverride,
		&i.InviteWindowDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
select id, org_id, application_id, assessment_id, stage_id, status, invited_at, invite_expires_at, started_at, expires_at, finished_at, score, risk_score, recording_status, recording_blob_key, created_at, updated_at, last_event_seq, problem_scores, error_count from attempt where id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.AssessmentID,
		&i.StageID,
		&i.Status,
		&i.InvitedAt,
		&i.InviteExpiresAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.Score,
		&i.RiskScore,
		&i.RecordingStatus,
		&i.RecordingBlobKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEventSeq,
		&i.ProblemScores,
		&i.ErrorCount,
	)
	return i, err
}

const getAttemptForApplicationStage = `-- name: GetAttemptForApplicationStage :one
select id, org_id, application_id, assessment_id, stage_id, status, invited_at, invite_expires_at, started_at, expires_at, finished_at, score, risk_score, recording_status, recording_blob_key, created_at, updated_at, last_event_seq, problem_scores, error_count from attempt where application_id = $1 and stage_id = $2 order by created_at desc limit 1
`

type GetAttemptForApplicationStageParams struct {
	ApplicationID uuid.UUID
	StageID       uuid.UUID
}

func (q *Queries) GetAttemptForApplicationStage(ctx context.Context, arg GetAttemptForApplicationStageParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptForApplicationStage, arg.ApplicationID, arg.StageID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.AssessmentID,
		&i.StageID,
		&i.Status,
		&i.InvitedAt,
		&i.InviteExpiresAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.Score,
		&i.RiskScore,
		&i.RecordingStatus,
		&i.RecordingBlobKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEventSeq,
		&i.ProblemScores,
		&i.ErrorCount,
	)
	return i, err
}

const getAttemptForUpdate = `-- name: GetAttemptForUpdate :one
select id, org_id, application_id, assessment_id, stage_id, status, invited_at, invite_expires_at, started_at, expires_at, finished_at, score, risk_score, recording_status, recording_blob_key, created_at, updated_at, last_event_seq, problem_scores, error_count from attempt where id = $1 for update
`

func (q *Queries) GetAttemptForUpdate(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptForUpdate, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.AssessmentID,
		&i.StageID,
		&i.Status,
		&i.InvitedAt,
		&i.InviteExpiresAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.Score,
		&i.RiskScore,
		&i.RecordingStatus,
		&i.RecordingBlobKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEventSeq,
		&i.ProblemScores,
		&i.ErrorCount,
	)
	return i, err
}

const getProblem = `-- name: GetProblem :one
select id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at from problem where id = $1
`

func (q *Queries) GetProblem(ctx context.Context, id uuid.UUID) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Title,
		&i.Statement,
		&i.Difficulty,
		&i.Tags,
		&i.AllowedLanguages,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.SqlSchema,
		&i.SqlSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemByTitle = `-- name: GetProblemByTitle :one
select id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at from problem where org_id = $1 and lower(title) = lower($2)
`

type GetProblemByTitleParams struct {
	OrgID uuid.UUID
	Lower string
}

func (q *Queries) GetProblemByTitle(ctx context.Context, arg GetProblemByTitleParams) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemByTitle, arg.OrgID, arg.Lower)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Title,
		&i.Statement,
		&i.Difficulty,
		&i.Tags,
		&i.AllowedLanguages,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.SqlSchema,
		&i.SqlSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewForAttempt = `-- name: GetReviewForAttempt :one
select r.id, r.org_id, r.attempt_id, r.vetter_id, r.verdict, r.notes, r.created_at,
    u.name as vetter_name
from review r join org_user u on u.id = r.vetter_id
where r.attempt_id = $1
`

type GetReviewForAttemptRow struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	AttemptID  uuid.UUID
	VetterID   uuid.UUID
	Verdict    string
	Notes      *string
	CreatedAt  pgtype.Timestamptz
	VetterName string
}

func (q *Queries) GetReviewForAttempt(ctx context.Context, attemptID uuid.UUID) (GetReviewForAttemptRow, error) {
	row := q.db.QueryRow(ctx, getReviewForAttempt, attemptID)
	var i GetReviewForAttemptRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AttemptID,
		&i.VetterID,
		&i.Verdict,
		&i.Notes,
		&i.CreatedAt,
		&i.VetterName,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
select id, org_id, attempt_id, problem_id, kind, language, source, status, result, score, created_at, updated_at from submission where id = $1 and attempt_id = $2
`

type GetSubmissionParams struct {
	ID        uuid.UUID
	AttemptID uuid.UUID
}

func (q *Queries) GetSubmission(ctx context.Context, arg GetSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, arg.ID, arg.AttemptID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AttemptID,
		&i.ProblemID,
		&i.Kind,
		&i.Language,
		&i.Source,
		&i.Status,
		&i.Result,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionForUpdate = `-- name: GetSubmissionForUpdate :one
select id, org_id, attempt_id, problem_id, kind, language, source, status, result, score, created_at, updated_at from submission where id = $1 for update
`

func (q *Queries) GetSubmissionForUpdate(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionForUpdate, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AttemptID,
		&i.ProblemID,
		&i.Kind,
		&i.Language,
		&i.Source,
		&i.Status,
		&i.Result,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssessmentProblems = `-- name: ListAssessmentProblems :many
select p.id, p.org_id, p.kind, p.title, p.statement, p.difficulty, p.tags, p.allowed_languages, p.time_limit_ms, p.memory_limit_kb, p.sql_schema, p.sql_seed, p.created_at, p.updated_at from assessment_problem ap join problem p on p.id = ap.problem_id
where ap.assessment_id = $1 order by ap.position
`

func (q *Queries) ListAssessmentProblems(ctx context.Context, assessmentID uuid.UUID) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listAssessmentProblems, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Title,
			&i.Statement,
			&i.Difficulty,
			&i.Tags,
			&i.AllowedLanguages,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.SqlSchema,
			&i.SqlSeed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessments = `-- name: ListAssessments :many
select id, org_id, name, duration_minutes, language_override, invite_window_days, created_at, updated_at from assessment where org_id = $1 order by name
`

func (q *Queries) ListAssessments(ctx context.Context, orgID uuid.UUID) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, listAssessments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assessment{}
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.DurationMinutes,
			&i.LanguageOverride,
			&i.InviteWindowDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptEvents = `-- name: ListAttemptEvents :many
select id, org_id, attempt_id, seq, kind, payload, client_ts, server_ts, problem_id from attempt_event where attempt_id = $1 order by seq
`

func (q *Queries) ListAttemptEvents(ctx context.Context, attemptID uuid.UUID) ([]AttemptEvent, error) {
	rows, err := q.db.Query(ctx, listAttemptEvents, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptEvent{}
	for rows.Next() {
		var i AttemptEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AttemptID,
			&i.Seq,
			&i.Kind,
			&i.Payload,
			&i.ClientTs,
			&i.ServerTs,
			&i.ProblemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptEventsAfter = `-- name: ListAttemptEventsAfter :many
select id, org_id, attempt_id, seq, kind, payload, client_ts, server_ts, problem_id from attempt_event where attempt_id = $1 and seq > $2 order by seq limit $3::int
`

type ListAttemptEventsAfterParams struct {
	AttemptID uuid.UUID
	Seq       int64
	RowLimit  int32
}

// One page of the recording, in seq order: the replay viewer pages through
// the stream rather than loading a whole sitting at once.
func (q *Queries) ListAttemptEventsAfter(ctx context.Context, arg ListAttemptEventsAfterParams) ([]AttemptEvent, error) {
	rows, err := q.db.Query(ctx, listAttemptEventsAfter, arg.AttemptID, arg.Seq, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptEvent{}
	for rows.Next() {
		var i AttemptEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AttemptID,
			&i.Seq,
			&i.Kind,
			&i.Payload,
			&i.ClientTs,
			&i.ServerTs,
			&i.ProblemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptSources = `-- name: ListAttemptSources :many
select attempt_id, org_id, problem_id, language, source, updated_at from attempt_source where attempt_id = $1 order by problem_id
`

func (q *Queries) ListAttemptSources(ctx context.Context, attemptID uuid.UUID) ([]AttemptSource, error) {
	rows, err := q.db.Query(ctx, listAttemptSources, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptSource{}
	for rows.Next() {
		var i AttemptSource
		if err := rows.Scan(
			&i.AttemptID,
			&i.OrgID,
			&i.ProblemID,
			&i.Language,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptSummariesForApplication = `-- name: ListAttemptSummariesForApplication :many
select t.id as attempt_id, t.stage_id, t.status, t.score, t.risk_score, t.error_count, t.finished_at,
    st.name as stage_name, r.verdict as verdict, r.notes as review_notes,
    r.created_at as reviewed_at, u.name as vetter_name
from attempt t
join stage st on st.id = t.stage_id
left join review r on r.attempt_id = t.id
left join org_user u on u.id = r.vetter_id
where t.application_id = $1
order by t.created_at
`

type ListAttemptSummariesForApplicationRow struct {
	AttemptID   uuid.UUID
	StageID     uuid.UUID
	Status      string
	Score       pgtype.Numeric
	RiskScore   pgtype.Numeric
	ErrorCount  int32
	FinishedAt  pgtype.Timestamptz
	StageName   string
	Verdict     *string
	ReviewNotes *string
	ReviewedAt  pgtype.Timestamptz
	VetterName  *string
}

// The score and verdict of every attempt on an application, for the
// recruiter's summary of it.
func (q *Queries) ListAttemptSummariesForApplication(ctx context.Context, applicationID uuid.UUID) ([]ListAttemptSummariesForApplicationRow, error) {
	rows, err := q.db.Query(ctx, listAttemptSummariesForApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptSummariesForApplicationRow{}
	for rows.Next() {
		var i ListAttemptSummariesForApplicationRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.StageID,
			&i.Status,
			&i.Score,
			&i.RiskScore,
			&i.ErrorCount,
			&i.FinishedAt,
			&i.StageName,
			&i.Verdict,
			&i.ReviewNotes,
			&i.ReviewedAt,
			&i.VetterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueAttemptOrgs = `-- name: ListDueAttemptOrgs :many
select org_id::uuid from due_attempt_orgs($1::timestamptz) as t(org_id)
`

func (q *Queries) ListDueAttemptOrgs(ctx context.Context, at pgtype.Timestamptz) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueAttemptOrgs, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var org_id uuid.UUID
		if err := rows.Scan(&org_id); err != nil {
			return nil, err
		}
		items = append(items, org_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueAttempts = `-- name: ListDueAttempts :many
select id, org_id, application_id, assessment_id, stage_id, status, invited_at, invite_expires_at, started_at, expires_at, finished_at, score, risk_score, recording_status, recording_blob_key, created_at, updated_at, last_event_seq, problem_scores, error_count from attempt where status = 'started' and expires_at <= $1 order by expires_at for update skip locked
`

func (q *Queries) ListDueAttempts(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listDueAttempts, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ApplicationID,
			&i.AssessmentID,
			&i.StageID,
			&i.Status,
			&i.InvitedAt,
			&i.InviteExpiresAt,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.FinishedAt,
			&i.Score,
			&i.RiskScore,
			&i.RecordingStatus,
			&i.RecordingBlobKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastEventSeq,
			&i.ProblemScores,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditedProblems = `-- name: ListEditedProblems :many
select distinct problem_id from attempt_event where attempt_id = $1 and kind = 'edit' and problem_id is not null
`

// The problems the recording holds an edit for. The rest never changed, so
// the text still synced for them is the text they started from.
func (q *Queries) ListEditedProblems(ctx context.Context, attemptID uuid.UUID) ([]uuid.NullUUID, error) {
	rows, err := q.db.Query(ctx, listEditedProblems, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.NullUUID{}
	for rows.Next() {
		var problem_id uuid.NullUUID
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegritySignals = `-- name: ListIntegritySignals :many
select id, org_id, attempt_id, name, value, weight, confidence, evidence, created_at from integrity_signal where attempt_id = $1 order by name
`

func (q *Queries) ListIntegritySignals(ctx context.Context, attemptID uuid.UUID) ([]IntegritySignal, error) {
	rows, err := q.db.Query(ctx, listIntegritySignals, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegritySignal{}
	for rows.Next() {
		var i IntegritySignal
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AttemptID,
			&i.Name,
			&i.Value,
			&i.Weight,
			&i.Confidence,
			&i.Evidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtherProblemSubmits = `-- name: ListOtherProblemSubmits :many
select attempt_id, source from (
    select distinct on (attempt_id) attempt_id, source, created_at from submission
    where problem_id = $1 and attempt_id <> $2 and kind = 'submit' and language = $3
    order by attempt_id, created_at desc
) latest order by created_at desc limit 200
`

type ListOtherProblemSubmitsParams struct {
	ProblemID uuid.UUID
	AttemptID uuid.UUID
	Language  string
}

type ListOtherProblemSubmitsRow struct {
	AttemptID uuid.UUID
	Source    string
}

// The latest submit of the problem, in the language, by each of the 200
// most recent other attempts RLS lets the caller see (every attempt of
// the org).
func (q *Queries) ListOtherProblemSubmits(ctx context.Context, arg ListOtherProblemSubmitsParams) ([]ListOtherProblemSubmitsRow, error) {
	rows, err := q.db.Query(ctx, listOtherProblemSubmits, arg.ProblemID, arg.AttemptID, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtherProblemSubmitsRow{}
	for rows.Next() {
		var i ListOtherProblemSubmitsRow
		if err := rows.Scan(&i.AttemptID, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemReferences = `-- name: ListProblemReferences :many
select id, org_id, problem_id, language, source from problem_reference where problem_id = $1 order by language
`

func (q *Queries) ListProblemReferences(ctx context.Context, problemID uuid.UUID) ([]ProblemReference, error) {
	rows, err := q.db.Query(ctx, listProblemReferences, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemReference{}
	for rows.Next() {
		var i ProblemReference
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProblemID,
			&i.Language,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissions = `-- name: ListSubmissions :many
select id, org_id, attempt_id, problem_id, kind, language, source, status, result, score, created_at, updated_at from submission where attempt_id = $1 order by created_at, id
`

func (q *Queries) ListSubmissions(ctx context.Context, attemptID uuid.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissions, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AttemptID,
			&i.ProblemID,
			&i.Kind,
			&i.Language,
			&i.Source,
			&i.Status,
			&i.Result,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCases = `-- name: ListTestCases :many
select id, org_id, problem_id, position, input, expected_output, visibility, weight, unordered from test_case where problem_id = $1 order by position
`

func (q *Queries) ListTestCases(ctx context.Context, problemID uuid.UUID) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProblemID,
			&i.Position,
			&i.Input,
			&i.ExpectedOutput,
			&i.Visibility,
			&i.Weight,
			&i.Unordered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVetterAttemptReviews = `-- name: ListVetterAttemptReviews :many
select t.id as attempt_id, t.application_id, t.stage_id, t.status, t.score, t.risk_score,
    t.error_count, t.recording_status, t.finished_at,
    c.name as candidate_name, c.email as candidate_email,
    j.title as job_title, st.name as stage_name, r.verdict as verdict
from attempt t
join application a on a.id = t.application_id
join candidate c on c.id = a.candidate_id
join job j on j.id = a.job_id
join stage st on st.id = t.stage_id
left join review r on r.attempt_id = t.id
where t.status in ('scored', 'reviewed')
  and coalesce(a.vetter_id, st.default_vetter_id) = $1
order by t.finished_at desc nulls last, t.id
`

type ListVetterAttemptReviewsRow struct {
	AttemptID       uuid.UUID
	ApplicationID   uuid.UUID
	StageID         uuid.UUID
	Status          string
	Score           pgtype.Numeric
	RiskScore       pgtype.Numeric
	ErrorCount      int32
	RecordingStatus string
	FinishedAt      pgtype.Timestamptz
	CandidateName   string
	CandidateEmail  string
	JobTitle        string
	StageName       string
	Verdict         *string
}

// The closed attempts waiting on the signed-in vetter, with their verdict if
// one is filed. The application's own vetter decides; until one is set the
// stage's default stands in, the same rule the scorecard queue uses.
func (q *Queries) ListVetterAttemptReviews(ctx context.Context, vetterID uuid.NullUUID) ([]ListVetterAttemptReviewsRow, error) {
	rows, err := q.db.Query(ctx, listVetterAttemptReviews, vetterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVetterAttemptReviewsRow{}
	for rows.Next() {
		var i ListVetterAttemptReviewsRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.ApplicationID,
			&i.StageID,
			&i.Status,
			&i.Score,
			&i.RiskScore,
			&i.ErrorCount,
			&i.RecordingStatus,
			&i.FinishedAt,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.JobTitle,
			&i.StageName,
			&i.Verdict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scoreAttempt = `-- name: ScoreAttempt :one
update attempt set status = 'scored', score = $2, problem_scores = $3, error_count = $4,
    recording_status = $5, recording_blob_key = $6, updated_at = now()
where id = $1 and status in ('submitted', 'expired') returning id, org_id, application_id, assessment_id, stage_id, status, invited_at, invite_expires_at, started_at, expires_at, finished_at, score, risk_score, recording_status, recording_blob_key, created_at, updated_at, last_event_seq, problem_scores, error_count
`

type ScoreAttemptParams struct {
	ID               uuid.UUID
	Score            pgtype.Numeric
	ProblemScores    []byte
	ErrorCount       int32
	RecordingStatus  string
	RecordingBlobKey *string
}

// Only a closed attempt is scored, and only once: concurrent deliveries of
// attempt.finalize race here and the losers match no row.
func (q *Queries) ScoreAttempt(ctx context.Context, arg ScoreAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, scoreAttempt,
		arg.ID,
		arg.Score,
		arg.ProblemScores,
		arg.ErrorCount,
		arg.RecordingStatus,
		arg.RecordingBlobKey,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.AssessmentID,
		&i.StageID,
		&i.Status,
		&i.InvitedAt,
		&i.InviteExpiresAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.Score,
		&i.RiskScore,
		&i.RecordingStatus,
		&i.RecordingBlobKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEventSeq,
		&i.ProblemScores,
		&i.ErrorCount,
	)
	return i, err
}

const setAttemptLastEventSeq = `-- name: SetAttemptLastEventSeq :exec
update attempt set last_event_seq = $2, updated_at = now() where id = $1
`

type SetAttemptLastEventSeqParams struct {
	ID           uuid.UUID
	LastEventSeq int64
}

func (q *Queries) SetAttemptLastEventSeq(ctx context.Context, arg SetAttemptLastEventSeqParams) error {
	_, err := q.db.Exec(ctx, setAttemptLastEventSeq, arg.ID, arg.LastEventSeq)
	return err
}

const setAttemptReviewed = `-- name: SetAttemptReviewed :exec
update attempt set status = 'reviewed', updated_at = now() where id = $1 and status in ('scored', 'reviewed')
`

func (q *Queries) SetAttemptReviewed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAttemptReviewed, id)
	return err
}

const setAttemptRiskScore = `-- name: SetAttemptRiskScore :exec
update attempt set risk_score = $2, updated_at = now() where id = $1
`

type SetAttemptRiskScoreParams struct {
	ID        uuid.UUID
	RiskScore pgtype.Numeric
}

func (q *Queries) SetAttemptRiskScore(ctx context.Context, arg SetAttemptRiskScoreParams) error {
	_, err := q.db.Exec(ctx, setAttemptRiskScore, arg.ID, arg.RiskScore)
	return err
}

const setStageAssessment = `-- name: SetStageAssessment :execrows
update stage set assessment_id = $3 where id = $1 and job_id = $2
`

type SetStageAssessmentParams struct {
	ID           uuid.UUID
	JobID        uuid.UUID
	AssessmentID uuid.NullUUID
}

func (q *Queries) SetStageAssessment(ctx context.Context, arg SetStageAssessmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStageAssessment, arg.ID, arg.JobID, arg.AssessmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startAttempt = `-- name: StartAttempt :one
update attempt set status = 'started', started_at = $2, expires_at = $3, updated_at = now()
where id = $1 and status = 'invited' returning id, org_id, application_id, assessment_id, stage_id, status, invited_at, invite_expires_at, started_at, expires_at, finished_at, score, risk_score, recording_status, recording_blob_key, created_at, updated_at, last_event_seq, problem_scores, error_count
`

type StartAttemptParams struct {
	ID        uuid.UUID
	StartedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) StartAttempt(ctx context.Context, arg StartAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, startAttempt, arg.ID, arg.StartedAt, arg.ExpiresAt)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.AssessmentID,
		&i.StageID,
		&i.Status,
		&i.InvitedAt,
		&i.InviteExpiresAt,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.Score,
		&i.RiskScore,
		&i.RecordingStatus,
		&i.RecordingBlobKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEventSeq,
		&i.ProblemScores,
		&i.ErrorCount,
	)
	return i, err
}

const startSubmission = `-- name: StartSubmission :exec
update submission set status = 'running', updated_at = now() where id = $1
`

func (q *Queries) StartSubmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startSubmission, id)
	return err
}

const updateAssessment = `-- name: UpdateAssessment :one
update assessment set name = $3, duration_minutes = $4, language_override = $5, invite_window_days = $6, updated_at = now()
where id = $1 and org_id = $2 returning id, org_id, name, duration_minutes, language_override, invite_window_days, created_at, updated_at
`

type UpdateAssessmentParams struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Name             string
	DurationMinutes  int32
	LanguageOverride *string
	InviteWindowDays int32
}

func (q *Queries) UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, updateAssessment,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.DurationMinutes,
		arg.LanguageOverride,
		arg.InviteWindowDays,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DurationMinutes,
		&i.LanguageOverride,
		&i.InviteWindowDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProblem = `-- name: UpdateProblem :one
update problem set kind = $3, title = $4, statement = $5, difficulty = $6, tags = $7,
    allowed_languages = $8, time_limit_ms = $9, memory_limit_kb = $10, sql_schema = $11,
    sql_seed = $12, updated_at = now()
where id = $1 and org_id = $2 returning id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at
`

type UpdateProblemParams struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Kind             string
	Title            string
	Statement        string
	Difficulty       string
	Tags             []string
	AllowedLanguages []string
	TimeLimitMs      int32
	MemoryLimitKb    int32
	SqlSchema        *string
	SqlSeed          *string
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.OrgID,
		arg.Kind,
		arg.Title,
		arg.Statement,
		arg.Difficulty,
		arg.Tags,
		arg.AllowedLanguages,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.SqlSchema,
		arg.SqlSeed,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Title,
		&i.Statement,
		&i.Difficulty,
		&i.Tags,
		&i.AllowedLanguages,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.SqlSchema,
		&i.SqlSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAttemptSource = `-- name: UpsertAttemptSource :exec
insert into attempt_source (attempt_id, org_id, problem_id, language, source, updated_at)
values ($1, $2, $3, $4, $5, $6)
on conflict (attempt_id, problem_id) do update set language = excluded.language, source = excluded.source, updated_at = excluded.updated_at
`

type UpsertAttemptSourceParams struct {
	AttemptID uuid.UUID
	OrgID     uuid.UUID
	ProblemID uuid.UUID
	Language  string
	Source    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertAttemptSource(ctx context.Context, arg UpsertAttemptSourceParams) error {
	_, err := q.db.Exec(ctx, upsertAttemptSource,
		arg.AttemptID,
		arg.OrgID,
		arg.ProblemID,
		arg.Language,
		arg.Source,
		arg.UpdatedAt,
	)
	return err
}

const upsertReviewByAuthor = `-- name: UpsertReviewByAuthor :one
insert into review (org_id, attempt_id, vetter_id, verdict, notes)
values ($1, $2, $3, $4, $5)
on conflict (attempt_id) do update set verdict = excluded.verdict, notes = excluded.notes
where review.vetter_id = excluded.vetter_id
returning id, org_id, attempt_id, vetter_id, verdict, notes, created_at
`

type UpsertReviewByAuthorParams struct {
	OrgID     uuid.UUID
	AttemptID uuid.UUID
	VetterID  uuid.UUID
	Verdict   string
	Notes     *string
}

// One review per attempt. A second reviewer matches no row rather than
// overwriting the verdict the first one filed.
func (q *Queries) UpsertReviewByAuthor(ctx context.Context, arg UpsertReviewByAuthorParams) (Review, error) {
	row := q.db.QueryRow(ctx, upsertReviewByAuthor,
		arg.OrgID,
		arg.AttemptID,
		arg.VetterID,
		arg.Verdict,
		arg.Notes,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AttemptID,
		&i.VetterID,
		&i.Verdict,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
