// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countApplicationsInStage = `-- name: CountApplicationsInStage :one
select count(*) from application where stage_id = $1
`

func (q *Queries) CountApplicationsInStage(ctx context.Context, stageID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsInStage, stageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :one
insert into application (org_id, job_id, candidate_id, client_company_id, stage_id, screening_answers)
values ($1, $2, $3, $4, $5, $6) returning id, org_id, job_id, candidate_id, client_company_id, stage_id, status, released_at, high_quality, recruiter_summary, screening_answers, created_at, updated_at, vetter_id
`

type CreateApplicationParams struct {
	OrgID            uuid.UUID
	JobID            uuid.UUID
	CandidateID      uuid.UUID
	ClientCompanyID  uuid.UUID
	StageID          uuid.UUID
	ScreeningAnswers []byte
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.OrgID,
		arg.JobID,
		arg.CandidateID,
		arg.ClientCompanyID,
		arg.StageID,
		arg.ScreeningAnswers,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.CandidateID,
		&i.ClientCompanyID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.HighQuality,
		&i.RecruiterSummary,
		&i.ScreeningAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VetterID,
	)
	return i, err
}

const createApplicationEvent = `-- name: CreateApplicationEvent :one
insert into application_event (org_id, application_id, actor_kind, actor_id, kind, from_stage_id, to_stage_id, reason, payload)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning id, org_id, application_id, actor_kind, actor_id, kind, from_stage_id, to_stage_id, reason, payload, created_at, seq
`

type CreateApplicationEventParams struct {
	OrgID         uuid.UUID
	ApplicationID uuid.UUID
	ActorKind     string
	ActorID       uuid.NullUUID
	Kind          string
	FromStageID   uuid.NullUUID
	ToStageID     uuid.NullUUID
	Reason        *string
	Payload       []byte
}

func (q *Queries) CreateApplicationEvent(ctx context.Context, arg CreateApplicationEventParams) (ApplicationEvent, error) {
	row := q.db.QueryRow(ctx, createApplicationEvent,
		arg.OrgID,
		arg.ApplicationID,
		arg.ActorKind,
		arg.ActorID,
		arg.Kind,
		arg.FromStageID,
		arg.ToStageID,
		arg.Reason,
		arg.Payload,
	)
	var i ApplicationEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.ActorKind,
		&i.ActorID,
		&i.Kind,
		&i.FromStageID,
		&i.ToStageID,
		&i.Reason,
		&i.Payload,
		&i.CreatedAt,
		&i.Seq,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
insert into job (org_id, client_company_id, title, slug, description, skills, seniority, location, remote_policy, salary_min, salary_max, blind_mode, status, created_by)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) returning id, org_id, client_company_id, title, description, skills, seniority, location, remote_policy, salary_min, salary_max, blind_mode, status, created_by, created_at, updated_at, slug
`

type CreateJobParams struct {
	OrgID           uuid.UUID
	ClientCompanyID uuid.UUID
	Title           string
	Slug            string
	Description     string
	Skills          []string
	Seniority       *string
	Location        *string
	RemotePolicy    *string
	SalaryMin       *int32
	SalaryMax       *int32
	BlindMode       bool
	Status          string
	CreatedBy       uuid.NullUUID
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.OrgID,
		arg.ClientCompanyID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Skills,
		arg.Seniority,
		arg.Location,
		arg.RemotePolicy,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.BlindMode,
		arg.Status,
		arg.CreatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientCompanyID,
		&i.Title,
		&i.Description,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemotePolicy,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.BlindMode,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const createStage = `-- name: CreateStage :one
insert into stage (org_id, job_id, position, name, kind, terminal_status, unblind, scorecard_rubric_id, default_vetter_id, assessment_id)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning id, org_id, job_id, position, name, kind, unblind, scorecard_rubric_id, default_vetter_id, assessment_id, terminal_status
`

type CreateStageParams struct {
	OrgID             uuid.UUID
	JobID             uuid.UUID
	Position          int32
	Name              string
	Kind              string
	TerminalStatus    *string
	Unblind           bool
	ScorecardRubricID uuid.NullUUID
	DefaultVetterID   uuid.NullUUID
	AssessmentID      uuid.NullUUID
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStage,
		arg.OrgID,
		arg.JobID,
		arg.Position,
		arg.Name,
		arg.Kind,
		arg.TerminalStatus,
		arg.Unblind,
		arg.ScorecardRubricID,
		arg.DefaultVetterID,
		arg.AssessmentID,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.Position,
		&i.Name,
		&i.Kind,
		&i.Unblind,
		&i.ScorecardRubricID,
		&i.DefaultVetterID,
		&i.AssessmentID,
		&i.TerminalStatus,
	)
	return i, err
}

const deleteStage = `-- name: DeleteStage :execrows
delete from stage where id = $1
`

func (q *Queries) DeleteStage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplication = `-- name: GetApplication :one
select id, org_id, job_id, candidate_id, client_company_id, stage_id, status, released_at, high_quality, recruiter_summary, screening_answers, created_at, updated_at, vetter_id from application where id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.CandidateID,
		&i.ClientCompanyID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.HighQuality,
		&i.RecruiterSummary,
		&i.ScreeningAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VetterID,
	)
	return i, err
}

const getCandidate = `-- name: GetCandidate :one
select id, org_id, email, name, phone, links, created_at, updated_at from candidate where id = $1
`

type GetCandidateRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Email     string
	Name      string
	Phone     *string
	Links     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetCandidate(ctx context.Context, id uuid.UUID) (GetCandidateRow, error) {
	row := q.db.QueryRow(ctx, getCandidate, id)
	var i GetCandidateRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.Links,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
select id, org_id, client_company_id, title, description, skills, seniority, location, remote_policy, salary_min, salary_max, blind_mode, status, created_by, created_at, updated_at, slug from job where id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientCompanyID,
		&i.Title,
		&i.Description,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemotePolicy,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.BlindMode,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const getJobBySlug = `-- name: GetJobBySlug :one
select id, org_id, client_company_id, title, description, skills, seniority, location, remote_policy, salary_min, salary_max, blind_mode, status, created_by, created_at, updated_at, slug from job where org_id = $1 and slug = $2
`

type GetJobBySlugParams struct {
	OrgID uuid.UUID
	Slug  string
}

func (q *Queries) GetJobBySlug(ctx context.Context, arg GetJobBySlugParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobBySlug, arg.OrgID, arg.Slug)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientCompanyID,
		&i.Title,
		&i.Description,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemotePolicy,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.BlindMode,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const listApplicationEvents = `-- name: ListApplicationEvents :many
select id, org_id, application_id, actor_kind, actor_id, kind, from_stage_id, to_stage_id, reason, payload, created_at, seq from application_event where application_id = $1 order by seq
`

func (q *Queries) ListApplicationEvents(ctx context.Context, applicationID uuid.UUID) ([]ApplicationEvent, error) {
	rows, err := q.db.Query(ctx, listApplicationEvents, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationEvent{}
	for rows.Next() {
		var i ApplicationEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ApplicationID,
			&i.ActorKind,
			&i.ActorID,
			&i.Kind,
			&i.FromStageID,
			&i.ToStageID,
			&i.Reason,
			&i.Payload,
			&i.CreatedAt,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByJob = `-- name: ListApplicationsByJob :many
select id, org_id, job_id, candidate_id, client_company_id, stage_id, status, released_at, high_quality, recruiter_summary, screening_answers, created_at, updated_at, vetter_id from application where job_id = $1 order by created_at
`

func (q *Queries) ListApplicationsByJob(ctx context.Context, jobID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.JobID,
			&i.CandidateID,
			&i.ClientCompanyID,
			&i.StageID,
			&i.Status,
			&i.ReleasedAt,
			&i.HighQuality,
			&i.RecruiterSummary,
			&i.ScreeningAnswers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VetterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
select id, org_id, client_company_id, title, description, skills, seniority, location, remote_policy, salary_min, salary_max, blind_mode, status, created_by, created_at, updated_at, slug from job where org_id = $1 order by created_at desc
`

func (q *Queries) ListJobs(ctx context.Context, orgID uuid.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientCompanyID,
			&i.Title,
			&i.Description,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemotePolicy,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.BlindMode,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStages = `-- name: ListStages :many
select id, org_id, job_id, position, name, kind, unblind, scorecard_rubric_id, default_vetter_id, assessment_id, terminal_status from stage where job_id = $1 order by position
`

func (q *Queries) ListStages(ctx context.Context, jobID uuid.UUID) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStages, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stage{}
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.JobID,
			&i.Position,
			&i.Name,
			&i.Kind,
			&i.Unblind,
			&i.ScorecardRubricID,
			&i.DefaultVetterID,
			&i.AssessmentID,
			&i.TerminalStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveApplication = `-- name: MoveApplication :one
update application set stage_id = $2, status = $3, updated_at = now()
where id = $1 and stage_id = $4 and status = 'active' returning id, org_id, job_id, candidate_id, client_company_id, stage_id, status, released_at, high_quality, recruiter_summary, screening_answers, created_at, updated_at, vetter_id
`

type MoveApplicationParams struct {
	ID          uuid.UUID
	StageID     uuid.UUID
	Status      string
	FromStageID uuid.UUID
}

// Conditional on the stage the mover saw, so a move decided on a stale read
// updates nothing rather than overwriting a concurrent move.
func (q *Queries) MoveApplication(ctx context.Context, arg MoveApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, moveApplication,
		arg.ID,
		arg.StageID,
		arg.Status,
		arg.FromStageID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.CandidateID,
		&i.ClientCompanyID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.HighQuality,
		&i.RecruiterSummary,
		&i.ScreeningAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VetterID,
	)
	return i, err
}

const setApplicationReleased = `-- name: SetApplicationReleased :one
update application set released_at = $2, updated_at = now() where id = $1 returning id, org_id, job_id, candidate_id, client_company_id, stage_id, status, released_at, high_quality, recruiter_summary, screening_answers, created_at, updated_at, vetter_id
`

type SetApplicationReleasedParams struct {
	ID         uuid.UUID
	ReleasedAt pgtype.Timestamptz
}

func (q *Queries) SetApplicationReleased(ctx context.Context, arg SetApplicationReleasedParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationReleased, arg.ID, arg.ReleasedAt)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.CandidateID,
		&i.ClientCompanyID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.HighQuality,
		&i.RecruiterSummary,
		&i.ScreeningAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VetterID,
	)
	return i, err
}

const setStagePosition = `-- name: SetStagePosition :exec
update stage set position = $2 where id = $1
`

type SetStagePositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetStagePosition(ctx context.Context, arg SetStagePositionParams) error {
	_, err := q.db.Exec(ctx, setStagePosition, arg.ID, arg.Position)
	return err
}

const updateJob = `-- name: UpdateJob :one
update job set client_company_id = $2, title = $3, slug = $4, description = $5, skills = $6,
    seniority = $7, location = $8, remote_policy = $9, salary_min = $10, salary_max = $11,
    blind_mode = $12, status = $13, updated_at = now()
where id = $1 returning id, org_id, client_company_id, title, description, skills, seniority, location, remote_policy, salary_min, salary_max, blind_mode, status, created_by, created_at, updated_at, slug
`

type UpdateJobParams struct {
	ID              uuid.UUID
	ClientCompanyID uuid.UUID
	Title           string
	Slug            string
	Description     string
	Skills          []string
	Seniority       *string
	Location        *string
	RemotePolicy    *string
	SalaryMin       *int32
	SalaryMax       *int32
	BlindMode       bool
	Status          string
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.ClientCompanyID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Skills,
		arg.Seniority,
		arg.Location,
		arg.RemotePolicy,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.BlindMode,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientCompanyID,
		&i.Title,
		&i.Description,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemotePolicy,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.BlindMode,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const updateStage = `-- name: UpdateStage :one
update stage set name = $2, kind = $3, terminal_status = $4, unblind = $5, default_vetter_id = $6 where id = $1 returning id, org_id, job_id, position, name, kind, unblind, scorecard_rubric_id, default_vetter_id, assessment_id, terminal_status
`

type UpdateStageParams struct {
	ID              uuid.UUID
	Name            string
	Kind            string
	TerminalStatus  *string
	Unblind         bool
	DefaultVetterID uuid.NullUUID
}

func (q *Queries) UpdateStage(ctx context.Context, arg UpdateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, updateStage,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.TerminalStatus,
		arg.Unblind,
		arg.DefaultVetterID,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.Position,
		&i.Name,
		&i.Kind,
		&i.Unblind,
		&i.ScorecardRubricID,
		&i.DefaultVetterID,
		&i.AssessmentID,
		&i.TerminalStatus,
	)
	return i, err
}

const upsertCandidate = `-- name: UpsertCandidate :one
insert into candidate (org_id, email, name, phone, links)
values ($1, $2, $3, $4, $5)
on conflict (org_id, lower(email)) do update
    set name = excluded.name, phone = coalesce(excluded.phone, candidate.phone),
        links = (select coalesce(jsonb_agg(distinct l), '[]'::jsonb)
            from jsonb_array_elements(candidate.links || excluded.links) l), updated_at = now()
returning id, org_id, email, name, phone, links, created_at, updated_at
`

type UpsertCandidateParams struct {
	OrgID uuid.UUID
	Email string
	Name  string
	Phone *string
	Links []byte
}

type UpsertCandidateRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Email     string
	Name      string
	Phone     *string
	Links     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// search is a derived tsvector maintained by trigger; it is never read back.
func (q *Queries) UpsertCandidate(ctx context.Context, arg UpsertCandidateParams) (UpsertCandidateRow, error) {
	row := q.db.QueryRow(ctx, upsertCandidate,
		arg.OrgID,
		arg.Email,
		arg.Name,
		arg.Phone,
		arg.Links,
	)
	var i UpsertCandidateRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Phone,
		&i.Links,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
