// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
insert into api_token (org_id, org_user_id, client_user_id, name, prefix, token_hash, expires_at)
values ($1, $2, $3, $4, $5, $6, $7) returning id, org_id, org_user_id, name, token_hash, created_at, revoked_at, prefix, expires_at, client_user_id
`

type CreateAPITokenParams struct {
	OrgID        uuid.UUID
	OrgUserID    uuid.NullUUID
	ClientUserID uuid.NullUUID
	Name         string
	Prefix       string
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.OrgID,
		arg.OrgUserID,
		arg.ClientUserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgUserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Prefix,
		&i.ExpiresAt,
		&i.ClientUserID,
	)
	return i, err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
insert into password_reset (org_id, org_user_id, client_user_id, token_hash, expires_at)
values ($1, $2, $3, $4, $5) returning id, org_id, org_user_id, client_user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetParams struct {
	OrgID        uuid.UUID
	OrgUserID    uuid.NullUUID
	ClientUserID uuid.NullUUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset,
		arg.OrgID,
		arg.OrgUserID,
		arg.ClientUserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgUserID,
		&i.ClientUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
delete from session where id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const deleteSessionsForClientUser = `-- name: DeleteSessionsForClientUser :exec
delete from session where client_user_id = $1
`

func (q *Queries) DeleteSessionsForClientUser(ctx context.Context, clientUserID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForClientUser, clientUserID)
	return err
}

const deleteSessionsForOrgUser = `-- name: DeleteSessionsForOrgUser :exec
delete from session where org_user_id = $1
`

func (q *Queries) DeleteSessionsForOrgUser(ctx context.Context, orgUserID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForOrgUser, orgUserID)
	return err
}

const getClientUser = `-- name: GetClientUser :one
select id, org_id, client_company_id, email, name, timezone, created_at from client_user where id = $1
`

func (q *Queries) GetClientUser(ctx context.Context, id uuid.UUID) (ClientUser, error) {
	row := q.db.QueryRow(ctx, getClientUser, id)
	var i ClientUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientCompanyID,
		&i.Email,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
select t.id, t.org_id, t.org_user_id, t.name, t.token_hash, t.created_at, t.revoked_at, t.prefix, t.expires_at, t.client_user_id, coalesce(o.email, c.email, '')::text as user_email
from api_token t
left join org_user o on o.id = t.org_user_id
left join client_user c on c.id = t.client_user_id
where t.org_id = $1
  and t.revoked_at is null
  and (t.expires_at is null or t.expires_at > now())
order by t.created_at desc
`

type ListAPITokensRow struct {
	ApiToken  ApiToken
	UserEmail string
}

func (q *Queries) ListAPITokens(ctx context.Context, orgID uuid.UUID) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ApiToken.ID,
			&i.ApiToken.OrgID,
			&i.ApiToken.OrgUserID,
			&i.ApiToken.Name,
			&i.ApiToken.TokenHash,
			&i.ApiToken.CreatedAt,
			&i.ApiToken.RevokedAt,
			&i.ApiToken.Prefix,
			&i.ApiToken.ExpiresAt,
			&i.ApiToken.ClientUserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPITokensByClientUser = `-- name: ListAPITokensByClientUser :many
select id, org_id, org_user_id, name, token_hash, created_at, revoked_at, prefix, expires_at, client_user_id from api_token
where client_user_id = $1 and revoked_at is null
  and (expires_at is null or expires_at > now())
order by created_at desc
`

// A client user's own live tokens, for the portal's developer page.
func (q *Queries) ListAPITokensByClientUser(ctx context.Context, clientUserID uuid.NullUUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensByClientUser, clientUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrgUserID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.Prefix,
			&i.ExpiresAt,
			&i.ClientUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPasswordReset = `-- name: LookupPasswordReset :one
select id, org_id, org_user_id, client_user_id, token_hash, expires_at, used_at, created_at from password_reset where token_hash = $1
`

func (q *Queries) LookupPasswordReset(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, lookupPasswordReset, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgUserID,
		&i.ClientUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :execrows
update password_reset set used_at = now() where id = $1 and used_at is null and expires_at > now()
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPasswordResetsUsedForClientUser = `-- name: MarkPasswordResetsUsedForClientUser :exec
update password_reset set used_at = now() where client_user_id = $1 and used_at is null
`

func (q *Queries) MarkPasswordResetsUsedForClientUser(ctx context.Context, clientUserID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetsUsedForClientUser, clientUserID)
	return err
}

const markPasswordResetsUsedForOrgUser = `-- name: MarkPasswordResetsUsedForOrgUser :exec
update password_reset set used_at = now() where org_user_id = $1 and used_at is null
`

func (q *Queries) MarkPasswordResetsUsedForOrgUser(ctx context.Context, orgUserID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetsUsedForOrgUser, orgUserID)
	return err
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
update api_token set revoked_at = now() where id = $1 and revoked_at is null
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPITokenOfClientUser = `-- name: RevokeAPITokenOfClientUser :execrows
update api_token set revoked_at = now()
where id = $1 and client_user_id = $2 and revoked_at is null
`

type RevokeAPITokenOfClientUserParams struct {
	ID           uuid.UUID
	ClientUserID uuid.NullUUID
}

func (q *Queries) RevokeAPITokenOfClientUser(ctx context.Context, arg RevokeAPITokenOfClientUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPITokenOfClientUser, arg.ID, arg.ClientUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeMagicLink = `-- name: RevokeMagicLink :exec
update magic_link set revoked_at = now() where id = $1 and revoked_at is null
`

func (q *Queries) RevokeMagicLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeMagicLink, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
update session set expires_at = $2 where id = $1
`

type TouchSessionParams struct {
	ID        uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}
