// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestAssessmentOutcome = `-- name: GetLatestAssessmentOutcome :one
select t.score, r.verdict
from attempt t
left join review r on r.attempt_id = t.id
where t.application_id = $1::uuid
order by t.created_at desc
limit 1
`

type GetLatestAssessmentOutcomeRow struct {
	Score   pgtype.Numeric
	Verdict *string
}

// Score and verdict only; the reviewer's notes stay internal.
func (q *Queries) GetLatestAssessmentOutcome(ctx context.Context, applicationID uuid.UUID) (GetLatestAssessmentOutcomeRow, error) {
	row := q.db.QueryRow(ctx, getLatestAssessmentOutcome, applicationID)
	var i GetLatestAssessmentOutcomeRow
	err := row.Scan(&i.Score, &i.Verdict)
	return i, err
}

const getReleasedApplication = `-- name: GetReleasedApplication :one
select a.id, a.job_id, a.stage_id, a.status, a.released_at, a.recruiter_summary, a.created_at, a.updated_at,
    c.id as candidate_id, c.name as candidate_name, c.email as candidate_email, c.phone as candidate_phone, c.links as candidate_links,
    s.name as stage_name, s.position as stage_position, s.kind as stage_kind, s.unblind as stage_unblind,
    j.title as job_title, j.blind_mode as job_blind_mode, j.client_company_id
from application a
join candidate c on c.id = a.candidate_id
join stage s on s.id = a.stage_id
join job j on j.id = a.job_id
where a.id = $1 and a.released_at is not null
`

type GetReleasedApplicationRow struct {
	ID               uuid.UUID
	JobID            uuid.UUID
	StageID          uuid.UUID
	Status           string
	ReleasedAt       pgtype.Timestamptz
	RecruiterSummary *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CandidateID      uuid.UUID
	CandidateName    string
	CandidateEmail   string
	CandidatePhone   *string
	CandidateLinks   []byte
	StageName        string
	StagePosition    int32
	StageKind        string
	StageUnblind     bool
	JobTitle         string
	JobBlindMode     bool
	ClientCompanyID  uuid.UUID
}

func (q *Queries) GetReleasedApplication(ctx context.Context, id uuid.UUID) (GetReleasedApplicationRow, error) {
	row := q.db.QueryRow(ctx, getReleasedApplication, id)
	var i GetReleasedApplicationRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.RecruiterSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CandidateID,
		&i.CandidateName,
		&i.CandidateEmail,
		&i.CandidatePhone,
		&i.CandidateLinks,
		&i.StageName,
		&i.StagePosition,
		&i.StageKind,
		&i.StageUnblind,
		&i.JobTitle,
		&i.JobBlindMode,
		&i.ClientCompanyID,
	)
	return i, err
}

const listClientEvents = `-- name: ListClientEvents :many
select e.seq, e.id, e.application_id, e.kind, e.actor_kind, e.reason, e.created_at,
    a.job_id, j.title as job_title,
    f.name as from_stage, t.name as to_stage
from application_event e
join application a on a.id = e.application_id
join job j on j.id = a.job_id
left join stage f on f.id = e.from_stage_id
left join stage t on t.id = e.to_stage_id
where a.client_company_id = $1::uuid
  and a.released_at is not null
  -- The release event is written in the transaction that sets released_at
  -- from the application clock, so it can predate the stamp by a moment
  -- and is named rather than compared.
  and (e.kind = 'released' or e.created_at >= a.released_at)
  and e.seq > $2::bigint
order by e.seq
limit $3::int
`

type ListClientEventsParams struct {
	ClientCompanyID uuid.UUID
	AfterSeq        int64
	RowLimit        int32
}

type ListClientEventsRow struct {
	Seq           *int64
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Kind          string
	ActorKind     string
	Reason        *string
	CreatedAt     pgtype.Timestamptz
	JobID         uuid.UUID
	JobTitle      string
	FromStage     *string
	ToStage       *string
}

// The company's change feed: every event on a released application from
// the moment it was released, in sequence order, after a cursor. The
// sequence is global and monotonic, so a caller that remembers the last
// seq it saw reads exactly what happened since.
func (q *Queries) ListClientEvents(ctx context.Context, arg ListClientEventsParams) ([]ListClientEventsRow, error) {
	rows, err := q.db.Query(ctx, listClientEvents, arg.ClientCompanyID, arg.AfterSeq, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientEventsRow{}
	for rows.Next() {
		var i ListClientEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.ApplicationID,
			&i.Kind,
			&i.ActorKind,
			&i.Reason,
			&i.CreatedAt,
			&i.JobID,
			&i.JobTitle,
			&i.FromStage,
			&i.ToStage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientJobs = `-- name: ListClientJobs :many
select j.id, j.org_id, j.client_company_id, j.title, j.description, j.skills, j.seniority, j.location, j.remote_policy, j.salary_min, j.salary_max, j.blind_mode, j.status, j.created_by, j.created_at, j.updated_at, j.slug, j.template_id, (select count(*) from application a where a.job_id = j.id and a.released_at is not null)::int as released_count
from job j
where j.client_company_id = $1 and j.status <> 'draft'
order by j.created_at desc
`

type ListClientJobsRow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	ClientCompanyID uuid.UUID
	Title           string
	Description     string
	Skills          []string
	Seniority       *string
	Location        *string
	RemotePolicy    *string
	SalaryMin       *int32
	SalaryMax       *int32
	BlindMode       bool
	Status          string
	CreatedBy       uuid.NullUUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Slug            string
	TemplateID      uuid.NullUUID
	ReleasedCount   int32
}

// The company's jobs with how many applications are released on each.
func (q *Queries) ListClientJobs(ctx context.Context, clientCompanyID uuid.UUID) ([]ListClientJobsRow, error) {
	rows, err := q.db.Query(ctx, listClientJobs, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientJobsRow{}
	for rows.Next() {
		var i ListClientJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientCompanyID,
			&i.Title,
			&i.Description,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemotePolicy,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.BlindMode,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.TemplateID,
			&i.ReleasedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientScorecards = `-- name: ListClientScorecards :many
select s.id, s.stage_id, s.scores, s.overall, s.created_at,
    u.name as vetter_name, st.name as stage_name
from scorecard s
join org_user u on u.id = s.vetter_id
join stage st on st.id = s.stage_id
where s.application_id = $1
order by st.position, s.created_at
`

type ListClientScorecardsRow struct {
	ID         uuid.UUID
	StageID    uuid.UUID
	Scores     []byte
	Overall    string
	CreatedAt  pgtype.Timestamptz
	VetterName string
	StageName  string
}

// The interviewer's notes column is deliberately absent: it never reaches a client.
func (q *Queries) ListClientScorecards(ctx context.Context, applicationID uuid.UUID) ([]ListClientScorecardsRow, error) {
	rows, err := q.db.Query(ctx, listClientScorecards, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientScorecardsRow{}
	for rows.Next() {
		var i ListClientScorecardsRow
		if err := rows.Scan(
			&i.ID,
			&i.StageID,
			&i.Scores,
			&i.Overall,
			&i.CreatedAt,
			&i.VetterName,
			&i.StageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientUsersByCompany = `-- name: ListClientUsersByCompany :many

select id, org_id, client_company_id, email, name, timezone, created_at from client_user where client_company_id = $1 order by name
`

// Client portal reads. Every query here runs under a client-scoped
// transaction, so RLS already limits rows to released applications of the
// caller's company; the predicates repeat that so the queries read correctly
// under an org scope too. None of them selects a notes column.
func (q *Queries) ListClientUsersByCompany(ctx context.Context, clientCompanyID uuid.UUID) ([]ClientUser, error) {
	rows, err := q.db.Query(ctx, listClientUsersByCompany, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientUser{}
	for rows.Next() {
		var i ClientUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientCompanyID,
			&i.Email,
			&i.Name,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUsersWithRole = `-- name: ListOrgUsersWithRole :many
select u.id, u.org_id, u.email, u.name, u.timezone, u.created_at from org_user u
join org_user_role r on r.org_user_id = u.id
where u.org_id = $1 and r.role = $2
order by u.name
`

type ListOrgUsersWithRoleParams struct {
	OrgID uuid.UUID
	Role  string
}

func (q *Queries) ListOrgUsersWithRole(ctx context.Context, arg ListOrgUsersWithRoleParams) ([]OrgUser, error) {
	rows, err := q.db.Query(ctx, listOrgUsersWithRole, arg.OrgID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgUser{}
	for rows.Next() {
		var i OrgUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasedApplications = `-- name: ListReleasedApplications :many
select a.id, a.job_id, a.stage_id, a.status, a.released_at, a.recruiter_summary, a.created_at, a.updated_at,
    c.id as candidate_id, c.name as candidate_name, c.email as candidate_email, c.phone as candidate_phone, c.links as candidate_links,
    s.name as stage_name, s.position as stage_position, s.kind as stage_kind, s.unblind as stage_unblind,
    j.title as job_title, j.blind_mode as job_blind_mode, j.client_company_id
from application a
join candidate c on c.id = a.candidate_id
join stage s on s.id = a.stage_id
join job j on j.id = a.job_id
where a.job_id = $1 and a.released_at is not null
order by s.position, a.created_at, a.id
`

type ListReleasedApplicationsRow struct {
	ID               uuid.UUID
	JobID            uuid.UUID
	StageID          uuid.UUID
	Status           string
	ReleasedAt       pgtype.Timestamptz
	RecruiterSummary *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CandidateID      uuid.UUID
	CandidateName    string
	CandidateEmail   string
	CandidatePhone   *string
	CandidateLinks   []byte
	StageName        string
	StagePosition    int32
	StageKind        string
	StageUnblind     bool
	JobTitle         string
	JobBlindMode     bool
	ClientCompanyID  uuid.UUID
}

func (q *Queries) ListReleasedApplications(ctx context.Context, jobID uuid.UUID) ([]ListReleasedApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listReleasedApplications, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasedApplicationsRow{}
	for rows.Next() {
		var i ListReleasedApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StageID,
			&i.Status,
			&i.ReleasedAt,
			&i.RecruiterSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateID,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.CandidatePhone,
			&i.CandidateLinks,
			&i.StageName,
			&i.StagePosition,
			&i.StageKind,
			&i.StageUnblind,
			&i.JobTitle,
			&i.JobBlindMode,
			&i.ClientCompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasedApplicationsByCompany = `-- name: ListReleasedApplicationsByCompany :many
select a.id, a.job_id, a.stage_id, a.status, a.released_at, a.recruiter_summary, a.created_at, a.updated_at,
    c.id as candidate_id, c.name as candidate_name, c.email as candidate_email, c.phone as candidate_phone, c.links as candidate_links,
    s.name as stage_name, s.position as stage_position, s.kind as stage_kind, s.unblind as stage_unblind,
    j.title as job_title, j.blind_mode as job_blind_mode, j.client_company_id
from application a
join candidate c on c.id = a.candidate_id
join stage s on s.id = a.stage_id
join job j on j.id = a.job_id
where a.client_company_id = $1::uuid and a.released_at is not null
  and ($2::uuid = '00000000-0000-0000-0000-000000000000'::uuid or a.job_id = $2::uuid)
  and ($3::text = '' or a.status = $3::text)
  and ($4::timestamptz is null or a.updated_at >= $4::timestamptz)
order by a.updated_at desc, a.id
limit $6::int offset $5::int
`

type ListReleasedApplicationsByCompanyParams struct {
	ClientCompanyID uuid.UUID
	JobID           uuid.UUID
	Status          string
	UpdatedSince    pgtype.Timestamptz
	RowOffset       int32
	RowLimit        int32
}

type ListReleasedApplicationsByCompanyRow struct {
	ID               uuid.UUID
	JobID            uuid.UUID
	StageID          uuid.UUID
	Status           string
	ReleasedAt       pgtype.Timestamptz
	RecruiterSummary *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CandidateID      uuid.UUID
	CandidateName    string
	CandidateEmail   string
	CandidatePhone   *string
	CandidateLinks   []byte
	StageName        string
	StagePosition    int32
	StageKind        string
	StageUnblind     bool
	JobTitle         string
	JobBlindMode     bool
	ClientCompanyID  uuid.UUID
}

// Every application released to the company, across its jobs, for the API's
// collection read. Filters are optional; a zero uuid or empty string is "any".
func (q *Queries) ListReleasedApplicationsByCompany(ctx context.Context, arg ListReleasedApplicationsByCompanyParams) ([]ListReleasedApplicationsByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listReleasedApplicationsByCompany,
		arg.ClientCompanyID,
		arg.JobID,
		arg.Status,
		arg.UpdatedSince,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasedApplicationsByCompanyRow{}
	for rows.Next() {
		var i ListReleasedApplicationsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StageID,
			&i.Status,
			&i.ReleasedAt,
			&i.RecruiterSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateID,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.CandidatePhone,
			&i.CandidateLinks,
			&i.StageName,
			&i.StagePosition,
			&i.StageKind,
			&i.StageUnblind,
			&i.JobTitle,
			&i.JobBlindMode,
			&i.ClientCompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
