// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intake.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createIntakeDraft = `-- name: CreateIntakeDraft :one

insert into intake_draft (org_id, created_by, step, payload) values ($1, $2, $3, $4) returning id, org_id, created_by, step, payload, created_at, updated_at
`

type CreateIntakeDraftParams struct {
	OrgID     uuid.UUID
	CreatedBy uuid.UUID
	Step      int32
	Payload   []byte
}

// The intake wizard's resumable draft. One row per recruiter, deleted the
// moment the intake creates the client, the job, and the assessment.
func (q *Queries) CreateIntakeDraft(ctx context.Context, arg CreateIntakeDraftParams) (IntakeDraft, error) {
	row := q.db.QueryRow(ctx, createIntakeDraft,
		arg.OrgID,
		arg.CreatedBy,
		arg.Step,
		arg.Payload,
	)
	var i IntakeDraft
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Step,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIntakeDraft = `-- name: DeleteIntakeDraft :execrows
delete from intake_draft where id = $1
`

func (q *Queries) DeleteIntakeDraft(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntakeDraft, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntakeDraft = `-- name: GetIntakeDraft :one
select id, org_id, created_by, step, payload, created_at, updated_at from intake_draft where id = $1
`

func (q *Queries) GetIntakeDraft(ctx context.Context, id uuid.UUID) (IntakeDraft, error) {
	row := q.db.QueryRow(ctx, getIntakeDraft, id)
	var i IntakeDraft
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Step,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenIntakeDraft = `-- name: GetOpenIntakeDraft :one
select id, org_id, created_by, step, payload, created_at, updated_at from intake_draft where created_by = $1
`

func (q *Queries) GetOpenIntakeDraft(ctx context.Context, createdBy uuid.UUID) (IntakeDraft, error) {
	row := q.db.QueryRow(ctx, getOpenIntakeDraft, createdBy)
	var i IntakeDraft
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Step,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveIntakeDraft = `-- name: SaveIntakeDraft :one
update intake_draft set step = $2, payload = $3, updated_at = now() where id = $1 returning id, org_id, created_by, step, payload, created_at, updated_at
`

type SaveIntakeDraftParams struct {
	ID      uuid.UUID
	Step    int32
	Payload []byte
}

func (q *Queries) SaveIntakeDraft(ctx context.Context, arg SaveIntakeDraftParams) (IntakeDraft, error) {
	row := q.db.QueryRow(ctx, saveIntakeDraft, arg.ID, arg.Step, arg.Payload)
	var i IntakeDraft
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Step,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
