// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobposting.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJobPosting = `-- name: CreateJobPosting :one
insert into job_posting (org_id, job_id, board, title, body, apply_url, created_by)
values ($1, $2, $3, $4, $5, $6, $7) returning id, org_id, job_id, board, status, title, body, apply_url, external_url, external_id, error, attempts, posted_at, created_by, created_at, updated_at
`

type CreateJobPostingParams struct {
	OrgID     uuid.UUID
	JobID     uuid.UUID
	Board     string
	Title     string
	Body      string
	ApplyUrl  string
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateJobPosting(ctx context.Context, arg CreateJobPostingParams) (JobPosting, error) {
	row := q.db.QueryRow(ctx, createJobPosting,
		arg.OrgID,
		arg.JobID,
		arg.Board,
		arg.Title,
		arg.Body,
		arg.ApplyUrl,
		arg.CreatedBy,
	)
	var i JobPosting
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.Board,
		&i.Status,
		&i.Title,
		&i.Body,
		&i.ApplyUrl,
		&i.ExternalUrl,
		&i.ExternalID,
		&i.Error,
		&i.Attempts,
		&i.PostedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJobPosting = `-- name: FailJobPosting :exec
update job_posting set status = 'failed', error = $2, updated_at = now() where id = $1
`

type FailJobPostingParams struct {
	ID    uuid.UUID
	Error *string
}

func (q *Queries) FailJobPosting(ctx context.Context, arg FailJobPostingParams) error {
	_, err := q.db.Exec(ctx, failJobPosting, arg.ID, arg.Error)
	return err
}

const finishJobPosting = `-- name: FinishJobPosting :exec
update job_posting set status = 'posted', external_url = $2, external_id = $3, error = null, posted_at = now(), updated_at = now()
where id = $1
`

type FinishJobPostingParams struct {
	ID          uuid.UUID
	ExternalUrl *string
	ExternalID  *string
}

func (q *Queries) FinishJobPosting(ctx context.Context, arg FinishJobPostingParams) error {
	_, err := q.db.Exec(ctx, finishJobPosting, arg.ID, arg.ExternalUrl, arg.ExternalID)
	return err
}

const getJobPosting = `-- name: GetJobPosting :one
select id, org_id, job_id, board, status, title, body, apply_url, external_url, external_id, error, attempts, posted_at, created_by, created_at, updated_at from job_posting where id = $1
`

func (q *Queries) GetJobPosting(ctx context.Context, id uuid.UUID) (JobPosting, error) {
	row := q.db.QueryRow(ctx, getJobPosting, id)
	var i JobPosting
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.Board,
		&i.Status,
		&i.Title,
		&i.Body,
		&i.ApplyUrl,
		&i.ExternalUrl,
		&i.ExternalID,
		&i.Error,
		&i.Attempts,
		&i.PostedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobPostingForUpdate = `-- name: GetJobPostingForUpdate :one
select id, org_id, job_id, board, status, title, body, apply_url, external_url, external_id, error, attempts, posted_at, created_by, created_at, updated_at from job_posting where id = $1 for update
`

func (q *Queries) GetJobPostingForUpdate(ctx context.Context, id uuid.UUID) (JobPosting, error) {
	row := q.db.QueryRow(ctx, getJobPostingForUpdate, id)
	var i JobPosting
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.Board,
		&i.Status,
		&i.Title,
		&i.Body,
		&i.ApplyUrl,
		&i.ExternalUrl,
		&i.ExternalID,
		&i.Error,
		&i.Attempts,
		&i.PostedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobPostings = `-- name: ListJobPostings :many
select id, org_id, job_id, board, status, title, body, apply_url, external_url, external_id, error, attempts, posted_at, created_by, created_at, updated_at from job_posting where job_id = $1 order by created_at desc
`

func (q *Queries) ListJobPostings(ctx context.Context, jobID uuid.UUID) ([]JobPosting, error) {
	rows, err := q.db.Query(ctx, listJobPostings, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobPosting{}
	for rows.Next() {
		var i JobPosting
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.JobID,
			&i.Board,
			&i.Status,
			&i.Title,
			&i.Body,
			&i.ApplyUrl,
			&i.ExternalUrl,
			&i.ExternalID,
			&i.Error,
			&i.Attempts,
			&i.PostedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobPostingsForOrg = `-- name: ListJobPostingsForOrg :many
select p.id, p.org_id, p.job_id, p.board, p.status, p.title, p.body, p.apply_url, p.external_url, p.external_id, p.error, p.attempts, p.posted_at, p.created_by, p.created_at, p.updated_at, j.title as job_title from job_posting p join job j on j.id = p.job_id
where p.org_id = $1 order by p.created_at desc limit $2::int
`

type ListJobPostingsForOrgParams struct {
	OrgID    uuid.UUID
	RowLimit int32
}

type ListJobPostingsForOrgRow struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	JobID       uuid.UUID
	Board       string
	Status      string
	Title       string
	Body        string
	ApplyUrl    string
	ExternalUrl *string
	ExternalID  *string
	Error       *string
	Attempts    int32
	PostedAt    pgtype.Timestamptz
	CreatedBy   uuid.NullUUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	JobTitle    string
}

// Every posting of the org, newest first, for the sourcing overview.
func (q *Queries) ListJobPostingsForOrg(ctx context.Context, arg ListJobPostingsForOrgParams) ([]ListJobPostingsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listJobPostingsForOrg, arg.OrgID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobPostingsForOrgRow{}
	for rows.Next() {
		var i ListJobPostingsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.JobID,
			&i.Board,
			&i.Status,
			&i.Title,
			&i.Body,
			&i.ApplyUrl,
			&i.ExternalUrl,
			&i.ExternalID,
			&i.Error,
			&i.Attempts,
			&i.PostedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeJobPosting = `-- name: RemoveJobPosting :execrows
update job_posting set status = 'removed', updated_at = now() where id = $1 and org_id = $2
`

type RemoveJobPostingParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) RemoveJobPosting(ctx context.Context, arg RemoveJobPostingParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeJobPosting, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startJobPosting = `-- name: StartJobPosting :execrows
update job_posting set status = 'posting', attempts = attempts + 1, updated_at = now()
where id = $1 and status in ('queued', 'posting', 'failed')
`

// Claims a queued or failed posting for one publish attempt.
func (q *Queries) StartJobPosting(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, startJobPosting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
