// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	OrgUserID uuid.UUID
	Name      string
	TokenHash string
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Application struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	JobID            uuid.UUID
	CandidateID      uuid.UUID
	ClientCompanyID  uuid.UUID
	StageID          uuid.UUID
	Status           string
	ReleasedAt       pgtype.Timestamptz
	HighQuality      bool
	RecruiterSummary *string
	ScreeningAnswers []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	VetterID         uuid.NullUUID
}

type ApplicationEvent struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	ApplicationID uuid.UUID
	ActorKind     string
	ActorID       uuid.NullUUID
	Kind          string
	FromStageID   uuid.NullUUID
	ToStageID     uuid.NullUUID
	Reason        *string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	Seq           *int64
}

type Assessment struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Name             string
	DurationMinutes  int32
	LanguageOverride *string
	InviteWindowDays int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AssessmentProblem struct {
	AssessmentID uuid.UUID
	OrgID        uuid.UUID
	ProblemID    uuid.UUID
	Position     int32
}

type Attempt struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	ApplicationID    uuid.UUID
	AssessmentID     uuid.UUID
	StageID          uuid.UUID
	Status           string
	InvitedAt        pgtype.Timestamptz
	InviteExpiresAt  pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	Score            pgtype.Numeric
	RiskScore        pgtype.Numeric
	RecordingStatus  string
	RecordingBlobKey *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	LastEventSeq     int64
	ProblemScores    []byte
	ErrorCount       int32
}

type AttemptEvent struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	AttemptID uuid.UUID
	Seq       int64
	Kind      string
	Payload   []byte
	ClientTs  pgtype.Timestamptz
	ServerTs  pgtype.Timestamptz
	ProblemID uuid.NullUUID
}

type AttemptSource struct {
	AttemptID uuid.UUID
	OrgID     uuid.UUID
	ProblemID uuid.UUID
	Language  string
	Source    string
	UpdatedAt pgtype.Timestamptz
}

type AvailabilityException struct {
	ID       uuid.UUID
	OrgID    uuid.UUID
	VetterID uuid.UUID
	StartsAt pgtype.Timestamptz
	EndsAt   pgtype.Timestamptz
	Reason   *string
}

type AvailabilityRule struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	VetterID      uuid.UUID
	Weekday       int16
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	Timezone      string
	BufferMinutes int32
	SlotMinutes   int32
	ValidFrom     pgtype.Date
	ValidTo       pgtype.Date
	CreatedAt     pgtype.Timestamptz
}

type Candidate struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Email     string
	Name      string
	Phone     *string
	Links     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Search    interface{}
}

type ClientCompany struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type ClientUser struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	ClientCompanyID uuid.UUID
	Email           string
	Name            string
	Timezone        string
	CreatedAt       pgtype.Timestamptz
}

type ClientUserCredential struct {
	ClientUserID uuid.UUID
	OrgID        uuid.UUID
	PasswordHash string
	DisabledAt   pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type EmailLog struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Template  string
	ToEmail   string
	Subject   string
	Status    string
	Attempts  int32
	LastError *string
	CreatedAt pgtype.Timestamptz
	SentAt    pgtype.Timestamptz
	JobID     *int64
}

type IntegritySignal struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	AttemptID  uuid.UUID
	Name       string
	Value      pgtype.Numeric
	Weight     pgtype.Numeric
	Confidence string
	Evidence   []byte
	CreatedAt  pgtype.Timestamptz
}

type InterviewSlot struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	VetterID          uuid.UUID
	ApplicationID     uuid.NullUUID
	StageID           uuid.NullUUID
	CandidateTimezone *string
	StartsAt          pgtype.Timestamptz
	EndsAt            pgtype.Timestamptz
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Job struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	ClientCompanyID uuid.UUID
	Title           string
	Description     string
	Skills          []string
	Seniority       *string
	Location        *string
	RemotePolicy    *string
	SalaryMin       *int32
	SalaryMax       *int32
	BlindMode       bool
	Status          string
	CreatedBy       uuid.NullUUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Slug            string
}

type MagicLink struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	TokenHash string
	Purpose   string
	SubjectID uuid.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Org struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type OrgSetting struct {
	OrgID     uuid.UUID
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type OrgUser struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Email     string
	Name      string
	Timezone  string
	CreatedAt pgtype.Timestamptz
}

type OrgUserCredential struct {
	OrgUserID    uuid.UUID
	OrgID        uuid.UUID
	PasswordHash string
	DisabledAt   pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type OrgUserRole struct {
	OrgUserID uuid.UUID
	OrgID     uuid.UUID
	Role      string
}

type PasswordReset struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	OrgUserID    uuid.NullUUID
	ClientUserID uuid.NullUUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type PipelineTemplate struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Name      string
	IsDefault bool
	CreatedAt pgtype.Timestamptz
}

type PipelineTemplateStage struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	TemplateID uuid.UUID
	Position   int32
	Name       string
	Kind       string
	Unblind    bool
}

type Problem struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Kind             string
	Title            string
	Statement        string
	Difficulty       string
	Tags             []string
	AllowedLanguages []string
	TimeLimitMs      int32
	MemoryLimitKb    int32
	SqlSchema        *string
	SqlSeed          *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ProblemReference struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ProblemID uuid.UUID
	Language  string
	Source    string
}

type Resume struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	CandidateID   uuid.UUID
	BlobKey       string
	Filename      string
	ContentType   string
	SizeBytes     int64
	ExtractedText *string
	CreatedAt     pgtype.Timestamptz
	TextStatus    string
}

type Review struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	AttemptID uuid.UUID
	VetterID  uuid.UUID
	Verdict   string
	Notes     *string
	CreatedAt pgtype.Timestamptz
}

type Scorecard struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	ApplicationID uuid.UUID
	StageID       uuid.UUID
	VetterID      uuid.UUID
	RubricID      uuid.NullUUID
	Scores        []byte
	Overall       string
	Notes         *string
	NoShow        bool
	CreatedAt     pgtype.Timestamptz
	Criteria      []byte
	UpdatedAt     pgtype.Timestamptz
}

type ScorecardRubric struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Name      string
	Criteria  []byte
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	OrgUserID    uuid.NullUUID
	ClientUserID uuid.NullUUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Stage struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	JobID             uuid.UUID
	Position          int32
	Name              string
	Kind              string
	Unblind           bool
	ScorecardRubricID uuid.NullUUID
	DefaultVetterID   uuid.NullUUID
	AssessmentID      uuid.NullUUID
	TerminalStatus    *string
}

type Submission struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	AttemptID uuid.UUID
	ProblemID uuid.UUID
	Kind      string
	Language  string
	Source    string
	Status    string
	Result    []byte
	Score     pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TalentPoolEntry struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	CandidateID      uuid.UUID
	Skills           []string
	Seniority        *string
	Location         *string
	RemoteOk         bool
	BestScores       []byte
	ScorecardSummary *string
	Notes            *string
	SourceJobIds     []uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RemovedAt        pgtype.Timestamptz
	Source           string
}

type TestCase struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	ProblemID      uuid.UUID
	Position       int32
	Input          string
	ExpectedOutput string
	Visibility     string
	Weight         pgtype.Numeric
	Unordered      bool
}
