// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeApplication = `-- name: CloseApplication :one
update application set status = $2, updated_at = now() where id = $1 and status = 'active' returning id, org_id, job_id, candidate_id, client_company_id, stage_id, status, released_at, high_quality, recruiter_summary, screening_answers, created_at, updated_at, vetter_id
`

type CloseApplicationParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) CloseApplication(ctx context.Context, arg CloseApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, closeApplication, arg.ID, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.CandidateID,
		&i.ClientCompanyID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.HighQuality,
		&i.RecruiterSummary,
		&i.ScreeningAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VetterID,
	)
	return i, err
}

const filterJobApplicationCards = `-- name: FilterJobApplicationCards :many
select a.id, a.job_id, a.candidate_id, a.stage_id, a.status, a.released_at, a.high_quality, a.created_at, a.updated_at,
    c.name as candidate_name, c.email as candidate_email,
    s.name as stage_name, s.position as stage_position, s.kind as stage_kind
from application a
join candidate c on c.id = a.candidate_id
join stage s on s.id = a.stage_id
where a.job_id = $1
  and ($2::uuid is null or a.stage_id = $2::uuid)
  and ($3::text = '' or a.status = $3::text)
  and ($4::text = '' or c.search @@ websearch_to_tsquery('english', $4::text)
       or lower(c.email) like '%' || lower($4::text) || '%')
order by s.position, a.created_at, a.id
limit $5::int
`

type FilterJobApplicationCardsParams struct {
	JobID    uuid.UUID
	StageID  uuid.NullUUID
	Status   string
	Query    string
	RowLimit int32
}

type FilterJobApplicationCardsRow struct {
	ID             uuid.UUID
	JobID          uuid.UUID
	CandidateID    uuid.UUID
	StageID        uuid.UUID
	Status         string
	ReleasedAt     pgtype.Timestamptz
	HighQuality    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CandidateName  string
	CandidateEmail string
	StageName      string
	StagePosition  int32
	StageKind      string
}

// The list screen: stage and status narrow in SQL, and the search runs on the
// candidate's maintained tsvector so it matches resume text as well as names.
func (q *Queries) FilterJobApplicationCards(ctx context.Context, arg FilterJobApplicationCardsParams) ([]FilterJobApplicationCardsRow, error) {
	rows, err := q.db.Query(ctx, filterJobApplicationCards,
		arg.JobID,
		arg.StageID,
		arg.Status,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterJobApplicationCardsRow{}
	for rows.Next() {
		var i FilterJobApplicationCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CandidateID,
			&i.StageID,
			&i.Status,
			&i.ReleasedAt,
			&i.HighQuality,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.StageName,
			&i.StagePosition,
			&i.StageKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationCard = `-- name: GetApplicationCard :one
select a.id, a.job_id, a.candidate_id, a.stage_id, a.status, a.released_at, a.high_quality, a.created_at, a.updated_at,
    c.name as candidate_name, c.email as candidate_email,
    s.name as stage_name, s.position as stage_position, s.kind as stage_kind,
    j.title as job_title
from application a
join candidate c on c.id = a.candidate_id
join stage s on s.id = a.stage_id
join job j on j.id = a.job_id
where a.id = $1
`

type GetApplicationCardRow struct {
	ID             uuid.UUID
	JobID          uuid.UUID
	CandidateID    uuid.UUID
	StageID        uuid.UUID
	Status         string
	ReleasedAt     pgtype.Timestamptz
	HighQuality    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CandidateName  string
	CandidateEmail string
	StageName      string
	StagePosition  int32
	StageKind      string
	JobTitle       string
}

func (q *Queries) GetApplicationCard(ctx context.Context, id uuid.UUID) (GetApplicationCardRow, error) {
	row := q.db.QueryRow(ctx, getApplicationCard, id)
	var i GetApplicationCardRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CandidateID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.HighQuality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CandidateName,
		&i.CandidateEmail,
		&i.StageName,
		&i.StagePosition,
		&i.StageKind,
		&i.JobTitle,
	)
	return i, err
}

const getApplicationForUpdate = `-- name: GetApplicationForUpdate :one
select id, org_id, job_id, candidate_id, client_company_id, stage_id, status, released_at, high_quality, recruiter_summary, screening_answers, created_at, updated_at, vetter_id from application where id = $1 for update
`

// Locks the row for the rest of the transaction, so concurrent moves of one
// application serialise and the second sees the first's result.
func (q *Queries) GetApplicationForUpdate(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationForUpdate, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.CandidateID,
		&i.ClientCompanyID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.HighQuality,
		&i.RecruiterSummary,
		&i.ScreeningAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VetterID,
	)
	return i, err
}

const getStage = `-- name: GetStage :one
select id, org_id, job_id, position, name, kind, unblind, scorecard_rubric_id, default_vetter_id, assessment_id, terminal_status from stage where id = $1
`

func (q *Queries) GetStage(ctx context.Context, id uuid.UUID) (Stage, error) {
	row := q.db.QueryRow(ctx, getStage, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.Position,
		&i.Name,
		&i.Kind,
		&i.Unblind,
		&i.ScorecardRubricID,
		&i.DefaultVetterID,
		&i.AssessmentID,
		&i.TerminalStatus,
	)
	return i, err
}

const hasScorecardForStage = `-- name: HasScorecardForStage :one
select exists (select 1 from scorecard where application_id = $1 and stage_id = $2)
`

type HasScorecardForStageParams struct {
	ApplicationID uuid.UUID
	StageID       uuid.UUID
}

func (q *Queries) HasScorecardForStage(ctx context.Context, arg HasScorecardForStageParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasScorecardForStage, arg.ApplicationID, arg.StageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasVerdictForStage = `-- name: HasVerdictForStage :one
select exists (
    select 1 from review r join attempt t on t.id = r.attempt_id
    where t.application_id = $1::uuid and t.stage_id = $2::uuid
)
`

type HasVerdictForStageParams struct {
	ApplicationID uuid.UUID
	StageID       uuid.UUID
}

func (q *Queries) HasVerdictForStage(ctx context.Context, arg HasVerdictForStageParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasVerdictForStage, arg.ApplicationID, arg.StageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listJobApplicationCards = `-- name: ListJobApplicationCards :many
select a.id, a.job_id, a.candidate_id, a.stage_id, a.status, a.released_at, a.high_quality, a.created_at, a.updated_at,
    c.name as candidate_name, c.email as candidate_email,
    s.name as stage_name, s.position as stage_position, s.kind as stage_kind
from application a
join candidate c on c.id = a.candidate_id
join stage s on s.id = a.stage_id
where a.job_id = $1
order by s.position, a.created_at, a.id
`

type ListJobApplicationCardsRow struct {
	ID             uuid.UUID
	JobID          uuid.UUID
	CandidateID    uuid.UUID
	StageID        uuid.UUID
	Status         string
	ReleasedAt     pgtype.Timestamptz
	HighQuality    bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CandidateName  string
	CandidateEmail string
	StageName      string
	StagePosition  int32
	StageKind      string
}

// One row per application on a job, with what a board card or list row shows.
func (q *Queries) ListJobApplicationCards(ctx context.Context, jobID uuid.UUID) ([]ListJobApplicationCardsRow, error) {
	rows, err := q.db.Query(ctx, listJobApplicationCards, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobApplicationCardsRow{}
	for rows.Next() {
		var i ListJobApplicationCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CandidateID,
			&i.StageID,
			&i.Status,
			&i.ReleasedAt,
			&i.HighQuality,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.StageName,
			&i.StagePosition,
			&i.StageKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeBookLinks = `-- name: RevokeBookLinks :exec
update magic_link set revoked_at = now() where purpose = 'book' and subject_id = $1 and revoked_at is null
`

func (q *Queries) RevokeBookLinks(ctx context.Context, subjectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeBookLinks, subjectID)
	return err
}
