// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pool.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bestAssessmentScoresForCandidate = `-- name: BestAssessmentScoresForCandidate :many
select tag::text as tag, max(a.score)::numeric as best_score
from attempt a
join application app on app.id = a.application_id
join assessment_problem ap on ap.assessment_id = a.assessment_id
join problem p on p.id = ap.problem_id
cross join lateral unnest(p.tags) as tag
where app.candidate_id = $1 and a.score is not null
group by tag
`

type BestAssessmentScoresForCandidateRow struct {
	Tag       string
	BestScore pgtype.Numeric
}

// The candidate's best assessment score per problem tag, across every
// application they have. Derived, so re-running an upsert cannot drift.
func (q *Queries) BestAssessmentScoresForCandidate(ctx context.Context, candidateID uuid.UUID) ([]BestAssessmentScoresForCandidateRow, error) {
	rows, err := q.db.Query(ctx, bestAssessmentScoresForCandidate, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BestAssessmentScoresForCandidateRow{}
	for rows.Next() {
		var i BestAssessmentScoresForCandidateRow
		if err := rows.Scan(&i.Tag, &i.BestScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTalentPoolEntry = `-- name: GetTalentPoolEntry :one
select e.id, e.org_id, e.candidate_id, e.skills, e.seniority, e.location, e.remote_ok, e.best_scores, e.scorecard_summary, e.notes, e.source_job_ids, e.created_at, e.updated_at, e.removed_at, e.source, c.name as candidate_name, c.email as candidate_email
from talent_pool_entry e
join candidate c on c.id = e.candidate_id
where e.id = $1 and e.removed_at is null
`

type GetTalentPoolEntryRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	CandidateID      uuid.UUID
	Skills           []string
	Seniority        *string
	Location         *string
	RemoteOk         bool
	BestScores       []byte
	ScorecardSummary *string
	Notes            *string
	SourceJobIds     []uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RemovedAt        pgtype.Timestamptz
	Source           string
	CandidateName    string
	CandidateEmail   string
}

func (q *Queries) GetTalentPoolEntry(ctx context.Context, id uuid.UUID) (GetTalentPoolEntryRow, error) {
	row := q.db.QueryRow(ctx, getTalentPoolEntry, id)
	var i GetTalentPoolEntryRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CandidateID,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemoteOk,
		&i.BestScores,
		&i.ScorecardSummary,
		&i.Notes,
		&i.SourceJobIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
		&i.Source,
		&i.CandidateName,
		&i.CandidateEmail,
	)
	return i, err
}

const getTalentPoolEntryForCandidate = `-- name: GetTalentPoolEntryForCandidate :one
select id, org_id, candidate_id, skills, seniority, location, remote_ok, best_scores, scorecard_summary, notes, source_job_ids, created_at, updated_at, removed_at, source from talent_pool_entry where org_id = $1 and candidate_id = $2
`

type GetTalentPoolEntryForCandidateParams struct {
	OrgID       uuid.UUID
	CandidateID uuid.UUID
}

func (q *Queries) GetTalentPoolEntryForCandidate(ctx context.Context, arg GetTalentPoolEntryForCandidateParams) (TalentPoolEntry, error) {
	row := q.db.QueryRow(ctx, getTalentPoolEntryForCandidate, arg.OrgID, arg.CandidateID)
	var i TalentPoolEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CandidateID,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemoteOk,
		&i.BestScores,
		&i.ScorecardSummary,
		&i.Notes,
		&i.SourceJobIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
		&i.Source,
	)
	return i, err
}

const latestScorecardForCandidate = `-- name: LatestScorecardForCandidate :one
select s.overall, s.notes
from scorecard s
join application a on a.id = s.application_id
where a.candidate_id = $1
order by s.created_at desc
limit 1
`

type LatestScorecardForCandidateRow struct {
	Overall string
	Notes   *string
}

func (q *Queries) LatestScorecardForCandidate(ctx context.Context, candidateID uuid.UUID) (LatestScorecardForCandidateRow, error) {
	row := q.db.QueryRow(ctx, latestScorecardForCandidate, candidateID)
	var i LatestScorecardForCandidateRow
	err := row.Scan(&i.Overall, &i.Notes)
	return i, err
}

const listClientRejections = `-- name: ListClientRejections :many
select a.candidate_id, max(e.created_at)::timestamptz as rejected_at
from application a
join application_event e on e.application_id = a.id
join stage s on s.id = e.to_stage_id
where a.client_company_id = $1 and a.status = 'rejected' and s.terminal_status = 'rejected'
group by a.candidate_id
`

type ListClientRejectionsRow struct {
	CandidateID uuid.UUID
	RejectedAt  pgtype.Timestamptz
}

// When each candidate was last rejected by one client company, read off the
// move that closed the application rather than its row timestamp, which any
// later edit would push forward. The ranker drops the recent ones.
func (q *Queries) ListClientRejections(ctx context.Context, clientCompanyID uuid.UUID) ([]ListClientRejectionsRow, error) {
	rows, err := q.db.Query(ctx, listClientRejections, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientRejectionsRow{}
	for rows.Next() {
		var i ListClientRejectionsRow
		if err := rows.Scan(&i.CandidateID, &i.RejectedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobCandidateIDs = `-- name: ListJobCandidateIDs :many
select candidate_id from application where job_id = $1
`

func (q *Queries) ListJobCandidateIDs(ctx context.Context, jobID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listJobCandidateIDs, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var candidate_id uuid.UUID
		if err := rows.Scan(&candidate_id); err != nil {
			return nil, err
		}
		items = append(items, candidate_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentPoolEntriesForRanking = `-- name: ListTalentPoolEntriesForRanking :many
select e.id, e.candidate_id, e.skills, e.seniority, e.location, e.remote_ok,
    e.best_scores, c.name as candidate_name, c.email as candidate_email
from talent_pool_entry e
join candidate c on c.id = e.candidate_id
where e.org_id = $1 and e.removed_at is null
limit $2::int
`

type ListTalentPoolEntriesForRankingParams struct {
	OrgID    uuid.UUID
	RowLimit int32
}

type ListTalentPoolEntriesForRankingRow struct {
	ID             uuid.UUID
	CandidateID    uuid.UUID
	Skills         []string
	Seniority      *string
	Location       *string
	RemoteOk       bool
	BestScores     []byte
	CandidateName  string
	CandidateEmail string
}

// Every live entry the ranker scores, with only the fields the formula and
// the panel read. The browse list is paged; ranking must see the whole pool.
func (q *Queries) ListTalentPoolEntriesForRanking(ctx context.Context, arg ListTalentPoolEntriesForRankingParams) ([]ListTalentPoolEntriesForRankingRow, error) {
	rows, err := q.db.Query(ctx, listTalentPoolEntriesForRanking, arg.OrgID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentPoolEntriesForRankingRow{}
	for rows.Next() {
		var i ListTalentPoolEntriesForRankingRow
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemoteOk,
			&i.BestScores,
			&i.CandidateName,
			&i.CandidateEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTalentPoolEntry = `-- name: RemoveTalentPoolEntry :execrows
update talent_pool_entry set removed_at = now(), updated_at = now()
where id = $1 and removed_at is null
`

func (q *Queries) RemoveTalentPoolEntry(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removeTalentPoolEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreTalentPoolEntry = `-- name: RestoreTalentPoolEntry :exec
update talent_pool_entry set removed_at = null, updated_at = now() where id = $1
`

// A removal stands until a recruiter asks for the person back; the automatic
// sources refresh the aggregates of a removed entry without reviving it.
func (q *Queries) RestoreTalentPoolEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreTalentPoolEntry, id)
	return err
}

const retractTalentPoolEntryFromReview = `-- name: RetractTalentPoolEntryFromReview :execrows
update talent_pool_entry e set removed_at = now(), updated_at = now()
from application app
where app.id = $1 and e.org_id = $2
  and e.candidate_id = app.candidate_id and e.removed_at is null
  and e.source = 'assessment_review' and not app.high_quality
`

type RetractTalentPoolEntryFromReviewParams struct {
	ApplicationID uuid.UUID
	OrgID         uuid.UUID
}

// Withdraws the entry a passing assessment review filed once that verdict is
// amended down. Only an entry the review is the latest source of goes; one a
// recruiter flagged, or whose application they marked high quality, stays.
func (q *Queries) RetractTalentPoolEntryFromReview(ctx context.Context, arg RetractTalentPoolEntryFromReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, retractTalentPoolEntryFromReview, arg.ApplicationID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchTalentPoolEntriesWithCandidate = `-- name: SearchTalentPoolEntriesWithCandidate :many
select e.id, e.org_id, e.candidate_id, e.skills, e.seniority, e.location, e.remote_ok, e.best_scores, e.scorecard_summary, e.notes, e.source_job_ids, e.created_at, e.updated_at, e.removed_at, e.source, c.name as candidate_name, c.email as candidate_email
from talent_pool_entry e
join candidate c on c.id = e.candidate_id
where e.org_id = $1 and e.removed_at is null
  and ($2::text = ''
    or c.name ilike '%' || $2::text || '%'
    or c.email ilike '%' || $2::text || '%'
    or exists (select 1 from unnest(e.skills) tag where tag ilike '%' || $2::text || '%'))
order by e.updated_at desc
limit $3::int
`

type SearchTalentPoolEntriesWithCandidateParams struct {
	OrgID    uuid.UUID
	Query    string
	RowLimit int32
}

type SearchTalentPoolEntriesWithCandidateRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	CandidateID      uuid.UUID
	Skills           []string
	Seniority        *string
	Location         *string
	RemoteOk         bool
	BestScores       []byte
	ScorecardSummary *string
	Notes            *string
	SourceJobIds     []uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RemovedAt        pgtype.Timestamptz
	Source           string
	CandidateName    string
	CandidateEmail   string
}

// The pool list is a working view: a name, an address, or a tag narrows it.
func (q *Queries) SearchTalentPoolEntriesWithCandidate(ctx context.Context, arg SearchTalentPoolEntriesWithCandidateParams) ([]SearchTalentPoolEntriesWithCandidateRow, error) {
	rows, err := q.db.Query(ctx, searchTalentPoolEntriesWithCandidate, arg.OrgID, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTalentPoolEntriesWithCandidateRow{}
	for rows.Next() {
		var i SearchTalentPoolEntriesWithCandidateRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CandidateID,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemoteOk,
			&i.BestScores,
			&i.ScorecardSummary,
			&i.Notes,
			&i.SourceJobIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
			&i.Source,
			&i.CandidateName,
			&i.CandidateEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationHighQuality = `-- name: SetApplicationHighQuality :one
update application set high_quality = $2, updated_at = now() where id = $1 returning id, org_id, job_id, candidate_id, client_company_id, stage_id, status, released_at, high_quality, recruiter_summary, screening_answers, created_at, updated_at, vetter_id
`

type SetApplicationHighQualityParams struct {
	ID          uuid.UUID
	HighQuality bool
}

func (q *Queries) SetApplicationHighQuality(ctx context.Context, arg SetApplicationHighQualityParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationHighQuality, arg.ID, arg.HighQuality)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.CandidateID,
		&i.ClientCompanyID,
		&i.StageID,
		&i.Status,
		&i.ReleasedAt,
		&i.HighQuality,
		&i.RecruiterSummary,
		&i.ScreeningAnswers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VetterID,
	)
	return i, err
}

const updateTalentPoolEntry = `-- name: UpdateTalentPoolEntry :one
update talent_pool_entry set skills = $2, notes = $3, location = $4, remote_ok = $5, updated_at = now()
where id = $1 and removed_at is null returning id, org_id, candidate_id, skills, seniority, location, remote_ok, best_scores, scorecard_summary, notes, source_job_ids, created_at, updated_at, removed_at, source
`

type UpdateTalentPoolEntryParams struct {
	ID       uuid.UUID
	Skills   []string
	Notes    *string
	Location *string
	RemoteOk bool
}

func (q *Queries) UpdateTalentPoolEntry(ctx context.Context, arg UpdateTalentPoolEntryParams) (TalentPoolEntry, error) {
	row := q.db.QueryRow(ctx, updateTalentPoolEntry,
		arg.ID,
		arg.Skills,
		arg.Notes,
		arg.Location,
		arg.RemoteOk,
	)
	var i TalentPoolEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CandidateID,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemoteOk,
		&i.BestScores,
		&i.ScorecardSummary,
		&i.Notes,
		&i.SourceJobIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
		&i.Source,
	)
	return i, err
}

const upsertTalentPoolEntry = `-- name: UpsertTalentPoolEntry :one
insert into talent_pool_entry (
    org_id, candidate_id, skills, seniority, location, remote_ok,
    best_scores, scorecard_summary, source_job_ids, source)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
on conflict (org_id, candidate_id) do update set
    skills = excluded.skills,
    seniority = coalesce(excluded.seniority, talent_pool_entry.seniority),
    location = excluded.location,
    remote_ok = excluded.remote_ok,
    best_scores = excluded.best_scores,
    scorecard_summary = coalesce(excluded.scorecard_summary, talent_pool_entry.scorecard_summary),
    source_job_ids = excluded.source_job_ids,
    source = excluded.source,
    updated_at = now()
returning id, org_id, candidate_id, skills, seniority, location, remote_ok, best_scores, scorecard_summary, notes, source_job_ids, created_at, updated_at, removed_at, source
`

type UpsertTalentPoolEntryParams struct {
	OrgID            uuid.UUID
	CandidateID      uuid.UUID
	Skills           []string
	Seniority        *string
	Location         *string
	RemoteOk         bool
	BestScores       []byte
	ScorecardSummary *string
	SourceJobIds     []uuid.UUID
	Source           string
}

// One entry per candidate: a second pool-worthy event updates the aggregate
// the caller merged rather than filing another entry.
func (q *Queries) UpsertTalentPoolEntry(ctx context.Context, arg UpsertTalentPoolEntryParams) (TalentPoolEntry, error) {
	row := q.db.QueryRow(ctx, upsertTalentPoolEntry,
		arg.OrgID,
		arg.CandidateID,
		arg.Skills,
		arg.Seniority,
		arg.Location,
		arg.RemoteOk,
		arg.BestScores,
		arg.ScorecardSummary,
		arg.SourceJobIds,
		arg.Source,
	)
	var i TalentPoolEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CandidateID,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemoteOk,
		&i.BestScores,
		&i.ScorecardSummary,
		&i.Notes,
		&i.SourceJobIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
		&i.Source,
	)
	return i, err
}
