// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pool_email.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEmailLog = `-- name: CreateEmailLog :one
insert into email_log (org_id, template, to_email, subject) values ($1, $2, $3, $4) returning id, org_id, template, to_email, subject, status, attempts, last_error, created_at, sent_at, job_id
`

type CreateEmailLogParams struct {
	OrgID    uuid.UUID
	Template string
	ToEmail  string
	Subject  string
}

func (q *Queries) CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (EmailLog, error) {
	row := q.db.QueryRow(ctx, createEmailLog,
		arg.OrgID,
		arg.Template,
		arg.ToEmail,
		arg.Subject,
	)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Template,
		&i.ToEmail,
		&i.Subject,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.JobID,
	)
	return i, err
}

const getEmailLogByJob = `-- name: GetEmailLogByJob :one
select id, org_id, template, to_email, subject, status, attempts, last_error, created_at, sent_at, job_id from email_log where job_id = $1
`

func (q *Queries) GetEmailLogByJob(ctx context.Context, jobID *int64) (EmailLog, error) {
	row := q.db.QueryRow(ctx, getEmailLogByJob, jobID)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Template,
		&i.ToEmail,
		&i.Subject,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.JobID,
	)
	return i, err
}

const listTalentPoolEntries = `-- name: ListTalentPoolEntries :many
select id, org_id, candidate_id, skills, seniority, location, remote_ok, best_scores, scorecard_summary, notes, source_job_ids, created_at, updated_at, removed_at, source from talent_pool_entry where org_id = $1 and removed_at is null order by updated_at desc
`

func (q *Queries) ListTalentPoolEntries(ctx context.Context, orgID uuid.UUID) ([]TalentPoolEntry, error) {
	rows, err := q.db.Query(ctx, listTalentPoolEntries, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TalentPoolEntry{}
	for rows.Next() {
		var i TalentPoolEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CandidateID,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemoteOk,
			&i.BestScores,
			&i.ScorecardSummary,
			&i.Notes,
			&i.SourceJobIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailLogStatus = `-- name: UpdateEmailLogStatus :exec
update email_log set status = $2, attempts = attempts + 1, last_error = $3, sent_at = case when $2 = 'sent' then now() else sent_at end where id = $1
`

type UpdateEmailLogStatusParams struct {
	ID        uuid.UUID
	Status    string
	LastError *string
}

func (q *Queries) UpdateEmailLogStatus(ctx context.Context, arg UpdateEmailLogStatusParams) error {
	_, err := q.db.Exec(ctx, updateEmailLogStatus, arg.ID, arg.Status, arg.LastError)
	return err
}

const upsertEmailLogForJob = `-- name: UpsertEmailLogForJob :one
insert into email_log (org_id, template, to_email, subject, job_id)
values ($1, $2, $3, $4, $5)
on conflict (job_id) where job_id is not null
do update set subject = excluded.subject
returning id, org_id, template, to_email, subject, status, attempts, last_error, created_at, sent_at, job_id
`

type UpsertEmailLogForJobParams struct {
	OrgID    uuid.UUID
	Template string
	ToEmail  string
	Subject  string
	JobID    *int64
}

func (q *Queries) UpsertEmailLogForJob(ctx context.Context, arg UpsertEmailLogForJobParams) (EmailLog, error) {
	row := q.db.QueryRow(ctx, upsertEmailLogForJob,
		arg.OrgID,
		arg.Template,
		arg.ToEmail,
		arg.Subject,
		arg.JobID,
	)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Template,
		&i.ToEmail,
		&i.Subject,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.JobID,
	)
	return i, err
}
