// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problem.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProblem = `-- name: CreateProblem :one
insert into problem (org_id, kind, title, statement, difficulty, tags, allowed_languages,
    time_limit_ms, memory_limit_kb, sql_schema, sql_seed, signature, guidelines,
    origin_problem_id, quality, proven_languages)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) returning id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at, guidelines, origin_problem_id, quality, proven_languages, signature
`

type CreateProblemParams struct {
	OrgID            uuid.UUID
	Kind             string
	Title            string
	Statement        string
	Difficulty       string
	Tags             []string
	AllowedLanguages []string
	TimeLimitMs      int32
	MemoryLimitKb    int32
	SqlSchema        *string
	SqlSeed          *string
	Signature        []byte
	Guidelines       string
	OriginProblemID  uuid.NullUUID
	Quality          int32
	ProvenLanguages  []string
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.OrgID,
		arg.Kind,
		arg.Title,
		arg.Statement,
		arg.Difficulty,
		arg.Tags,
		arg.AllowedLanguages,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.SqlSchema,
		arg.SqlSeed,
		arg.Signature,
		arg.Guidelines,
		arg.OriginProblemID,
		arg.Quality,
		arg.ProvenLanguages,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Title,
		&i.Statement,
		&i.Difficulty,
		&i.Tags,
		&i.AllowedLanguages,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.SqlSchema,
		&i.SqlSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Guidelines,
		&i.OriginProblemID,
		&i.Quality,
		&i.ProvenLanguages,
		&i.Signature,
	)
	return i, err
}

const createProblemReference = `-- name: CreateProblemReference :one
insert into problem_reference (org_id, problem_id, language, source)
values ($1, $2, $3, $4) returning id, org_id, problem_id, language, source
`

type CreateProblemReferenceParams struct {
	OrgID     uuid.UUID
	ProblemID uuid.UUID
	Language  string
	Source    string
}

func (q *Queries) CreateProblemReference(ctx context.Context, arg CreateProblemReferenceParams) (ProblemReference, error) {
	row := q.db.QueryRow(ctx, createProblemReference,
		arg.OrgID,
		arg.ProblemID,
		arg.Language,
		arg.Source,
	)
	var i ProblemReference
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProblemID,
		&i.Language,
		&i.Source,
	)
	return i, err
}

const createTestCase = `-- name: CreateTestCase :one
insert into test_case (org_id, problem_id, position, input, expected_output, visibility,
    weight, unordered, name, class)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning id, org_id, problem_id, position, input, expected_output, visibility, weight, unordered, name, class
`

type CreateTestCaseParams struct {
	OrgID          uuid.UUID
	ProblemID      uuid.UUID
	Position       int32
	Input          string
	ExpectedOutput string
	Visibility     string
	Weight         pgtype.Numeric
	Unordered      bool
	Name           string
	Class          string
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.OrgID,
		arg.ProblemID,
		arg.Position,
		arg.Input,
		arg.ExpectedOutput,
		arg.Visibility,
		arg.Weight,
		arg.Unordered,
		arg.Name,
		arg.Class,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProblemID,
		&i.Position,
		&i.Input,
		&i.ExpectedOutput,
		&i.Visibility,
		&i.Weight,
		&i.Unordered,
		&i.Name,
		&i.Class,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :execrows
delete from problem where id = $1 and org_id = $2
`

type DeleteProblemParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteProblem(ctx context.Context, arg DeleteProblemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProblem, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProblemReferences = `-- name: DeleteProblemReferences :exec
delete from problem_reference where problem_id = $1
`

func (q *Queries) DeleteProblemReferences(ctx context.Context, problemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProblemReferences, problemID)
	return err
}

const deleteTestCases = `-- name: DeleteTestCases :exec
delete from test_case where problem_id = $1
`

func (q *Queries) DeleteTestCases(ctx context.Context, problemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTestCases, problemID)
	return err
}

const filterProblems = `-- name: FilterProblems :many
select problem.id, problem.org_id, problem.kind, problem.title, problem.statement, problem.difficulty, problem.tags, problem.allowed_languages, problem.time_limit_ms, problem.memory_limit_kb, problem.sql_schema, problem.sql_seed, problem.created_at, problem.updated_at, problem.guidelines, problem.origin_problem_id, problem.quality, problem.proven_languages, problem.signature, (select count(*) from test_case where test_case.problem_id = problem.id)::int as case_count
from problem
where ($1::text = '' or kind = $1::text)
  and ($2::text = '' or difficulty = $2::text)
  and ($3::text = '' or $3::text = any(tags))
  and ($4::text = '' or title ilike '%' || $4::text || '%')
order by title
limit $5::int
`

type FilterProblemsParams struct {
	Kind       string
	Difficulty string
	Tag        string
	Query      string
	RowLimit   int32
}

type FilterProblemsRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Kind             string
	Title            string
	Statement        string
	Difficulty       string
	Tags             []string
	AllowedLanguages []string
	TimeLimitMs      int32
	MemoryLimitKb    int32
	SqlSchema        *string
	SqlSeed          *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Guidelines       string
	OriginProblemID  uuid.NullUUID
	Quality          int32
	ProvenLanguages  []string
	Signature        []byte
	CaseCount        int32
}

// RLS shows the caller's own problems and the platform seed; the filters are
// all optional, an empty string meaning "any".
func (q *Queries) FilterProblems(ctx context.Context, arg FilterProblemsParams) ([]FilterProblemsRow, error) {
	rows, err := q.db.Query(ctx, filterProblems,
		arg.Kind,
		arg.Difficulty,
		arg.Tag,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterProblemsRow{}
	for rows.Next() {
		var i FilterProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Title,
			&i.Statement,
			&i.Difficulty,
			&i.Tags,
			&i.AllowedLanguages,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.SqlSchema,
			&i.SqlSeed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Guidelines,
			&i.OriginProblemID,
			&i.Quality,
			&i.ProvenLanguages,
			&i.Signature,
			&i.CaseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblem = `-- name: GetProblem :one
select id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at, guidelines, origin_problem_id, quality, proven_languages, signature from problem where id = $1
`

func (q *Queries) GetProblem(ctx context.Context, id uuid.UUID) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Title,
		&i.Statement,
		&i.Difficulty,
		&i.Tags,
		&i.AllowedLanguages,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.SqlSchema,
		&i.SqlSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Guidelines,
		&i.OriginProblemID,
		&i.Quality,
		&i.ProvenLanguages,
		&i.Signature,
	)
	return i, err
}

const getProblemByTitle = `-- name: GetProblemByTitle :one
select id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at, guidelines, origin_problem_id, quality, proven_languages, signature from problem where org_id = $1 and lower(title) = lower($2)
`

type GetProblemByTitleParams struct {
	OrgID uuid.UUID
	Lower string
}

func (q *Queries) GetProblemByTitle(ctx context.Context, arg GetProblemByTitleParams) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemByTitle, arg.OrgID, arg.Lower)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Title,
		&i.Statement,
		&i.Difficulty,
		&i.Tags,
		&i.AllowedLanguages,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.SqlSchema,
		&i.SqlSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Guidelines,
		&i.OriginProblemID,
		&i.Quality,
		&i.ProvenLanguages,
		&i.Signature,
	)
	return i, err
}

const getTestCase = `-- name: GetTestCase :one
select id, org_id, problem_id, position, input, expected_output, visibility, weight, unordered, name, class from test_case where problem_id = $1 and id = $2
`

type GetTestCaseParams struct {
	ProblemID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetTestCase(ctx context.Context, arg GetTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, getTestCase, arg.ProblemID, arg.ID)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProblemID,
		&i.Position,
		&i.Input,
		&i.ExpectedOutput,
		&i.Visibility,
		&i.Weight,
		&i.Unordered,
		&i.Name,
		&i.Class,
	)
	return i, err
}

const listProblemReferences = `-- name: ListProblemReferences :many
select id, org_id, problem_id, language, source from problem_reference where problem_id = $1 order by language
`

func (q *Queries) ListProblemReferences(ctx context.Context, problemID uuid.UUID) ([]ProblemReference, error) {
	rows, err := q.db.Query(ctx, listProblemReferences, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemReference{}
	for rows.Next() {
		var i ProblemReference
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProblemID,
			&i.Language,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTestCases = `-- name: ListPublicTestCases :many
select id, org_id, problem_id, position, input, expected_output, visibility, weight, unordered, name, class from test_case where problem_id = $1 and visibility = 'public' order by position
`

// The cases a candidate may see, payloads included: the worked examples,
// which are small by construction.
func (q *Queries) ListPublicTestCases(ctx context.Context, problemID uuid.UUID) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listPublicTestCases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProblemID,
			&i.Position,
			&i.Input,
			&i.ExpectedOutput,
			&i.Visibility,
			&i.Weight,
			&i.Unordered,
			&i.Name,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCaseMeta = `-- name: ListTestCaseMeta :many
select id, position, name, class, visibility, weight, unordered,
    octet_length(input)::int as input_bytes, octet_length(expected_output)::int as expected_bytes
from test_case where problem_id = $1 order by position
`

type ListTestCaseMetaRow struct {
	ID            uuid.UUID
	Position      int32
	Name          string
	Class         string
	Visibility    string
	Weight        pgtype.Numeric
	Unordered     bool
	InputBytes    int32
	ExpectedBytes int32
}

// Everything about a problem's cases but the payloads: the byte size of
// each stands in for it, which is all a poll, a review, or a score needs.
func (q *Queries) ListTestCaseMeta(ctx context.Context, problemID uuid.UUID) ([]ListTestCaseMetaRow, error) {
	rows, err := q.db.Query(ctx, listTestCaseMeta, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestCaseMetaRow{}
	for rows.Next() {
		var i ListTestCaseMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.Class,
			&i.Visibility,
			&i.Weight,
			&i.Unordered,
			&i.InputBytes,
			&i.ExpectedBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCases = `-- name: ListTestCases :many
select id, org_id, problem_id, position, input, expected_output, visibility, weight, unordered, name, class from test_case where problem_id = $1 order by position
`

// Every case with its payload. A perf case's input runs to megabytes, so
// only a path that hands the cases to the runner reads this; everything
// else reads ListTestCaseMeta.
func (q *Queries) ListTestCases(ctx context.Context, problemID uuid.UUID) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProblemID,
			&i.Position,
			&i.Input,
			&i.ExpectedOutput,
			&i.Visibility,
			&i.Weight,
			&i.Unordered,
			&i.Name,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasesWithin = `-- name: ListTestCasesWithin :many
select id, org_id, problem_id, position, input, expected_output, visibility, weight, unordered, name, class from test_case where problem_id = $1
  and octet_length(input) <= $2::int
  and octet_length(expected_output) <= $2::int
order by position
`

type ListTestCasesWithinParams struct {
	ProblemID uuid.UUID
	MaxBytes  int32
}

// The cases whose payloads both fit in max_bytes, which is what a form can
// inline; the larger ones are edited by reference.
func (q *Queries) ListTestCasesWithin(ctx context.Context, arg ListTestCasesWithinParams) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCasesWithin, arg.ProblemID, arg.MaxBytes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProblemID,
			&i.Position,
			&i.Input,
			&i.ExpectedOutput,
			&i.Visibility,
			&i.Weight,
			&i.Unordered,
			&i.Name,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblem = `-- name: UpdateProblem :one
update problem set kind = $3, title = $4, statement = $5, difficulty = $6, tags = $7,
    allowed_languages = $8, time_limit_ms = $9, memory_limit_kb = $10, sql_schema = $11,
    sql_seed = $12, signature = $13, guidelines = $14, quality = $15,
    proven_languages = $16, updated_at = now()
where id = $1 and org_id = $2 returning id, org_id, kind, title, statement, difficulty, tags, allowed_languages, time_limit_ms, memory_limit_kb, sql_schema, sql_seed, created_at, updated_at, guidelines, origin_problem_id, quality, proven_languages, signature
`

type UpdateProblemParams struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Kind             string
	Title            string
	Statement        string
	Difficulty       string
	Tags             []string
	AllowedLanguages []string
	TimeLimitMs      int32
	MemoryLimitKb    int32
	SqlSchema        *string
	SqlSeed          *string
	Signature        []byte
	Guidelines       string
	Quality          int32
	ProvenLanguages  []string
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.OrgID,
		arg.Kind,
		arg.Title,
		arg.Statement,
		arg.Difficulty,
		arg.Tags,
		arg.AllowedLanguages,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.SqlSchema,
		arg.SqlSeed,
		arg.Signature,
		arg.Guidelines,
		arg.Quality,
		arg.ProvenLanguages,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Title,
		&i.Statement,
		&i.Difficulty,
		&i.Tags,
		&i.AllowedLanguages,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.SqlSchema,
		&i.SqlSeed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Guidelines,
		&i.OriginProblemID,
		&i.Quality,
		&i.ProvenLanguages,
		&i.Signature,
	)
	return i, err
}
