// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInterviewRoom = `-- name: GetInterviewRoom :one
select id, org_id, kind, subject_id, language, source, updated_at from interview_room where kind = $1 and subject_id = $2
`

type GetInterviewRoomParams struct {
	Kind      string
	SubjectID uuid.UUID
}

func (q *Queries) GetInterviewRoom(ctx context.Context, arg GetInterviewRoomParams) (InterviewRoom, error) {
	row := q.db.QueryRow(ctx, getInterviewRoom, arg.Kind, arg.SubjectID)
	var i InterviewRoom
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.SubjectID,
		&i.Language,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const getInterviewSlotRoom = `-- name: GetInterviewSlotRoom :one
select s.id, s.org_id, s.vetter_id, s.application_id, s.stage_id, s.starts_at, s.ends_at, s.status,
    u.name as vetter_name, c.name as candidate_name, j.title as job_title, j.id as job_id,
    st.name as stage_name, st.interview_format
from interview_slot s
join org_user u on u.id = s.vetter_id
join application a on a.id = s.application_id
join candidate c on c.id = a.candidate_id
join job j on j.id = a.job_id
join stage st on st.id = a.stage_id
where s.id = $1
`

type GetInterviewSlotRoomRow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	VetterID        uuid.UUID
	ApplicationID   uuid.NullUUID
	StageID         uuid.NullUUID
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Status          string
	VetterName      string
	CandidateName   string
	JobTitle        string
	JobID           uuid.UUID
	StageName       string
	InterviewFormat string
}

// A booked interview with everyone and everything a room needs to know.
func (q *Queries) GetInterviewSlotRoom(ctx context.Context, id uuid.UUID) (GetInterviewSlotRoomRow, error) {
	row := q.db.QueryRow(ctx, getInterviewSlotRoom, id)
	var i GetInterviewSlotRoomRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VetterID,
		&i.ApplicationID,
		&i.StageID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.VetterName,
		&i.CandidateName,
		&i.JobTitle,
		&i.JobID,
		&i.StageName,
		&i.InterviewFormat,
	)
	return i, err
}

const listInterviewSlotsForOrg = `-- name: ListInterviewSlotsForOrg :many
select s.id, s.vetter_id, s.application_id, s.stage_id, s.starts_at, s.ends_at, s.status,
    u.name as vetter_name, c.name as candidate_name, c.email as candidate_email, j.title as job_title,
    st.name as stage_name, st.interview_format,
    exists (select 1 from scorecard sc where sc.application_id = s.application_id and sc.stage_id = s.stage_id and sc.vetter_id = s.vetter_id) as has_scorecard
from interview_slot s
join org_user u on u.id = s.vetter_id
join application a on a.id = s.application_id
join candidate c on c.id = a.candidate_id
join job j on j.id = a.job_id
join stage st on st.id = coalesce(s.stage_id, a.stage_id)
where s.status <> 'cancelled' and s.ends_at > $1::timestamptz
  and ($2::uuid is null or s.vetter_id = $2::uuid)
order by s.starts_at, s.id
`

type ListInterviewSlotsForOrgParams struct {
	EndsAfter pgtype.Timestamptz
	VetterID  uuid.NullUUID
}

type ListInterviewSlotsForOrgRow struct {
	ID              uuid.UUID
	VetterID        uuid.UUID
	ApplicationID   uuid.NullUUID
	StageID         uuid.NullUUID
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Status          string
	VetterName      string
	CandidateName   string
	CandidateEmail  string
	JobTitle        string
	StageName       string
	InterviewFormat string
	HasScorecard    bool
}

// Every booked or finished interview from a moment on, soonest first, for
// the interviews screen. A vetter's own list filters by vetter_id.
func (q *Queries) ListInterviewSlotsForOrg(ctx context.Context, arg ListInterviewSlotsForOrgParams) ([]ListInterviewSlotsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listInterviewSlotsForOrg, arg.EndsAfter, arg.VetterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInterviewSlotsForOrgRow{}
	for rows.Next() {
		var i ListInterviewSlotsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.VetterID,
			&i.ApplicationID,
			&i.StageID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.VetterName,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.JobTitle,
			&i.StageName,
			&i.InterviewFormat,
			&i.HasScorecard,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInterviewRoom = `-- name: UpsertInterviewRoom :one
insert into interview_room (org_id, kind, subject_id, language, source)
values ($1, $2, $3, $4, $5)
on conflict (kind, subject_id) do update
    set language = excluded.language, source = excluded.source, updated_at = now()
returning id, org_id, kind, subject_id, language, source, updated_at
`

type UpsertInterviewRoomParams struct {
	OrgID     uuid.UUID
	Kind      string
	SubjectID uuid.UUID
	Language  string
	Source    string
}

func (q *Queries) UpsertInterviewRoom(ctx context.Context, arg UpsertInterviewRoomParams) (InterviewRoom, error) {
	row := q.db.QueryRow(ctx, upsertInterviewRoom,
		arg.OrgID,
		arg.Kind,
		arg.SubjectID,
		arg.Language,
		arg.Source,
	)
	var i InterviewRoom
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.SubjectID,
		&i.Language,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}
