// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scorecards.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScorecardRubric = `-- name: CreateScorecardRubric :one
insert into scorecard_rubric (org_id, name, criteria) values ($1, $2, $3) returning id, org_id, name, criteria, created_at
`

type CreateScorecardRubricParams struct {
	OrgID    uuid.UUID
	Name     string
	Criteria []byte
}

func (q *Queries) CreateScorecardRubric(ctx context.Context, arg CreateScorecardRubricParams) (ScorecardRubric, error) {
	row := q.db.QueryRow(ctx, createScorecardRubric, arg.OrgID, arg.Name, arg.Criteria)
	var i ScorecardRubric
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Criteria,
		&i.CreatedAt,
	)
	return i, err
}

const getScorecard = `-- name: GetScorecard :one
select id, org_id, application_id, stage_id, vetter_id, rubric_id, scores, overall, notes, no_show, created_at, criteria, updated_at from scorecard where id = $1
`

func (q *Queries) GetScorecard(ctx context.Context, id uuid.UUID) (Scorecard, error) {
	row := q.db.QueryRow(ctx, getScorecard, id)
	var i Scorecard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.StageID,
		&i.VetterID,
		&i.RubricID,
		&i.Scores,
		&i.Overall,
		&i.Notes,
		&i.NoShow,
		&i.CreatedAt,
		&i.Criteria,
		&i.UpdatedAt,
	)
	return i, err
}

const getScorecardForVetter = `-- name: GetScorecardForVetter :one
select id, org_id, application_id, stage_id, vetter_id, rubric_id, scores, overall, notes, no_show, created_at, criteria, updated_at from scorecard where application_id = $1 and stage_id = $2 and vetter_id = $3
`

type GetScorecardForVetterParams struct {
	ApplicationID uuid.UUID
	StageID       uuid.UUID
	VetterID      uuid.UUID
}

func (q *Queries) GetScorecardForVetter(ctx context.Context, arg GetScorecardForVetterParams) (Scorecard, error) {
	row := q.db.QueryRow(ctx, getScorecardForVetter, arg.ApplicationID, arg.StageID, arg.VetterID)
	var i Scorecard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.StageID,
		&i.VetterID,
		&i.RubricID,
		&i.Scores,
		&i.Overall,
		&i.Notes,
		&i.NoShow,
		&i.CreatedAt,
		&i.Criteria,
		&i.UpdatedAt,
	)
	return i, err
}

const getScorecardRubric = `-- name: GetScorecardRubric :one
select id, org_id, name, criteria, created_at from scorecard_rubric where id = $1
`

func (q *Queries) GetScorecardRubric(ctx context.Context, id uuid.UUID) (ScorecardRubric, error) {
	row := q.db.QueryRow(ctx, getScorecardRubric, id)
	var i ScorecardRubric
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Criteria,
		&i.CreatedAt,
	)
	return i, err
}

const listScorecardsForApplication = `-- name: ListScorecardsForApplication :many
select s.id, s.application_id, s.stage_id, s.vetter_id, s.rubric_id, s.criteria, s.scores,
    s.overall, s.notes, s.created_at, s.updated_at,
    u.name as vetter_name, st.name as stage_name, st.position as stage_position
from scorecard s
join org_user u on u.id = s.vetter_id
join stage st on st.id = s.stage_id
where s.application_id = $1
order by st.position, s.created_at
`

type ListScorecardsForApplicationRow struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	StageID       uuid.UUID
	VetterID      uuid.UUID
	RubricID      uuid.NullUUID
	Criteria      []byte
	Scores        []byte
	Overall       string
	Notes         *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	VetterName    string
	StageName     string
	StagePosition int32
}

func (q *Queries) ListScorecardsForApplication(ctx context.Context, applicationID uuid.UUID) ([]ListScorecardsForApplicationRow, error) {
	rows, err := q.db.Query(ctx, listScorecardsForApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScorecardsForApplicationRow{}
	for rows.Next() {
		var i ListScorecardsForApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.StageID,
			&i.VetterID,
			&i.RubricID,
			&i.Criteria,
			&i.Scores,
			&i.Overall,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VetterName,
			&i.StageName,
			&i.StagePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVetterAssignments = `-- name: ListVetterAssignments :many
select a.id as application_id, a.stage_id, c.name as candidate_name, c.email as candidate_email,
    j.title as job_title, st.name as stage_name, sc.id as scorecard_id, sc.overall as overall
from application a
join candidate c on c.id = a.candidate_id
join job j on j.id = a.job_id
join stage st on st.id = a.stage_id
left join scorecard sc on sc.application_id = a.id and sc.stage_id = a.stage_id and sc.vetter_id = $1
where a.vetter_id = $1 and a.status = 'active' and st.kind = 'interview'
order by a.updated_at desc, a.id
`

type ListVetterAssignmentsRow struct {
	ApplicationID  uuid.UUID
	StageID        uuid.UUID
	CandidateName  string
	CandidateEmail string
	JobTitle       string
	StageName      string
	ScorecardID    uuid.NullUUID
	Overall        *string
}

// The interviews waiting on the signed-in vetter, with their own card if they
// have already filed one.
func (q *Queries) ListVetterAssignments(ctx context.Context, vetterID uuid.UUID) ([]ListVetterAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listVetterAssignments, vetterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVetterAssignmentsRow{}
	for rows.Next() {
		var i ListVetterAssignmentsRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.StageID,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.JobTitle,
			&i.StageName,
			&i.ScorecardID,
			&i.Overall,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStageRubric = `-- name: SetStageRubric :exec
update stage set scorecard_rubric_id = $2 where id = $1
`

type SetStageRubricParams struct {
	ID                uuid.UUID
	ScorecardRubricID uuid.NullUUID
}

func (q *Queries) SetStageRubric(ctx context.Context, arg SetStageRubricParams) error {
	_, err := q.db.Exec(ctx, setStageRubric, arg.ID, arg.ScorecardRubricID)
	return err
}

const updateScorecardByAuthor = `-- name: UpdateScorecardByAuthor :one
update scorecard set scores = $3, overall = $4, notes = $5, updated_at = now()
where id = $1 and vetter_id = $2 returning id, org_id, application_id, stage_id, vetter_id, rubric_id, scores, overall, notes, no_show, created_at, criteria, updated_at
`

type UpdateScorecardByAuthorParams struct {
	ID       uuid.UUID
	VetterID uuid.UUID
	Scores   []byte
	Overall  string
	Notes    *string
}

// The vetter is part of the key so a card can only be rewritten by the
// interviewer who filed it, whatever the caller claims.
func (q *Queries) UpdateScorecardByAuthor(ctx context.Context, arg UpdateScorecardByAuthorParams) (Scorecard, error) {
	row := q.db.QueryRow(ctx, updateScorecardByAuthor,
		arg.ID,
		arg.VetterID,
		arg.Scores,
		arg.Overall,
		arg.Notes,
	)
	var i Scorecard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.StageID,
		&i.VetterID,
		&i.RubricID,
		&i.Scores,
		&i.Overall,
		&i.Notes,
		&i.NoShow,
		&i.CreatedAt,
		&i.Criteria,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScorecardRubric = `-- name: UpdateScorecardRubric :one
update scorecard_rubric set name = $2, criteria = $3 where id = $1 returning id, org_id, name, criteria, created_at
`

type UpdateScorecardRubricParams struct {
	ID       uuid.UUID
	Name     string
	Criteria []byte
}

func (q *Queries) UpdateScorecardRubric(ctx context.Context, arg UpdateScorecardRubricParams) (ScorecardRubric, error) {
	row := q.db.QueryRow(ctx, updateScorecardRubric, arg.ID, arg.Name, arg.Criteria)
	var i ScorecardRubric
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Criteria,
		&i.CreatedAt,
	)
	return i, err
}

const upsertScorecard = `-- name: UpsertScorecard :one
insert into scorecard (org_id, application_id, stage_id, vetter_id, rubric_id, criteria, scores, overall, notes)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (application_id, stage_id, vetter_id) do update
    set scores = excluded.scores, overall = excluded.overall, notes = excluded.notes, updated_at = now()
    where scorecard.vetter_id = excluded.vetter_id
returning id, org_id, application_id, stage_id, vetter_id, rubric_id, scores, overall, notes, no_show, created_at, criteria, updated_at
`

type UpsertScorecardParams struct {
	OrgID         uuid.UUID
	ApplicationID uuid.UUID
	StageID       uuid.UUID
	VetterID      uuid.UUID
	RubricID      uuid.NullUUID
	Criteria      []byte
	Scores        []byte
	Overall       string
	Notes         *string
}

// One card per interviewer per stage: a card filed twice at once updates the
// first rather than failing on the key. The guard restates the authorship the
// conflict target already carries, and the snapshot of what the interviewer
// was asked stays as it was filed.
func (q *Queries) UpsertScorecard(ctx context.Context, arg UpsertScorecardParams) (Scorecard, error) {
	row := q.db.QueryRow(ctx, upsertScorecard,
		arg.OrgID,
		arg.ApplicationID,
		arg.StageID,
		arg.VetterID,
		arg.RubricID,
		arg.Criteria,
		arg.Scores,
		arg.Overall,
		arg.Notes,
	)
	var i Scorecard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApplicationID,
		&i.StageID,
		&i.VetterID,
		&i.RubricID,
		&i.Scores,
		&i.Overall,
		&i.Notes,
		&i.NoShow,
		&i.CreatedAt,
		&i.Criteria,
		&i.UpdatedAt,
	)
	return i, err
}
