// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sprints.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSprintCandidate = `-- name: AddSprintCandidate :one
insert into sprint_candidate (sprint_id, org_id, application_id, position) values ($1, $2, $3, $4) returning id, sprint_id, org_id, application_id, position
`

type AddSprintCandidateParams struct {
	SprintID      uuid.UUID
	OrgID         uuid.UUID
	ApplicationID uuid.UUID
	Position      int32
}

func (q *Queries) AddSprintCandidate(ctx context.Context, arg AddSprintCandidateParams) (SprintCandidate, error) {
	row := q.db.QueryRow(ctx, addSprintCandidate,
		arg.SprintID,
		arg.OrgID,
		arg.ApplicationID,
		arg.Position,
	)
	var i SprintCandidate
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.OrgID,
		&i.ApplicationID,
		&i.Position,
	)
	return i, err
}

const addSprintInterviewer = `-- name: AddSprintInterviewer :exec
insert into sprint_interviewer (sprint_id, org_id, user_id, position) values ($1, $2, $3, $4)
`

type AddSprintInterviewerParams struct {
	SprintID uuid.UUID
	OrgID    uuid.UUID
	UserID   uuid.UUID
	Position int32
}

func (q *Queries) AddSprintInterviewer(ctx context.Context, arg AddSprintInterviewerParams) error {
	_, err := q.db.Exec(ctx, addSprintInterviewer,
		arg.SprintID,
		arg.OrgID,
		arg.UserID,
		arg.Position,
	)
	return err
}

const createSprint = `-- name: CreateSprint :one
insert into sprint (org_id, job_id, stage_id, name, starts_at, round_seconds, break_seconds, created_by)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, org_id, job_id, stage_id, name, status, starts_at, round_seconds, break_seconds, created_by, created_at, updated_at
`

type CreateSprintParams struct {
	OrgID        uuid.UUID
	JobID        uuid.UUID
	StageID      uuid.UUID
	Name         string
	StartsAt     pgtype.Timestamptz
	RoundSeconds int32
	BreakSeconds int32
	CreatedBy    uuid.NullUUID
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.OrgID,
		arg.JobID,
		arg.StageID,
		arg.Name,
		arg.StartsAt,
		arg.RoundSeconds,
		arg.BreakSeconds,
		arg.CreatedBy,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.StageID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.RoundSeconds,
		&i.BreakSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSprintPairing = `-- name: CreateSprintPairing :one
insert into sprint_pairing (sprint_id, org_id, round, interviewer_id, application_id)
values ($1, $2, $3, $4, $5) returning id, sprint_id, org_id, round, interviewer_id, application_id
`

type CreateSprintPairingParams struct {
	SprintID      uuid.UUID
	OrgID         uuid.UUID
	Round         int32
	InterviewerID uuid.UUID
	ApplicationID uuid.UUID
}

func (q *Queries) CreateSprintPairing(ctx context.Context, arg CreateSprintPairingParams) (SprintPairing, error) {
	row := q.db.QueryRow(ctx, createSprintPairing,
		arg.SprintID,
		arg.OrgID,
		arg.Round,
		arg.InterviewerID,
		arg.ApplicationID,
	)
	var i SprintPairing
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.OrgID,
		&i.Round,
		&i.InterviewerID,
		&i.ApplicationID,
	)
	return i, err
}

const deleteSprintCandidates = `-- name: DeleteSprintCandidates :exec
delete from sprint_candidate where sprint_id = $1
`

func (q *Queries) DeleteSprintCandidates(ctx context.Context, sprintID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSprintCandidates, sprintID)
	return err
}

const deleteSprintInterviewers = `-- name: DeleteSprintInterviewers :exec
delete from sprint_interviewer where sprint_id = $1
`

func (q *Queries) DeleteSprintInterviewers(ctx context.Context, sprintID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSprintInterviewers, sprintID)
	return err
}

const deleteSprintPairings = `-- name: DeleteSprintPairings :exec
delete from sprint_pairing where sprint_id = $1
`

func (q *Queries) DeleteSprintPairings(ctx context.Context, sprintID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSprintPairings, sprintID)
	return err
}

const getSprint = `-- name: GetSprint :one
select id, org_id, job_id, stage_id, name, status, starts_at, round_seconds, break_seconds, created_by, created_at, updated_at from sprint where id = $1
`

func (q *Queries) GetSprint(ctx context.Context, id uuid.UUID) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.StageID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.RoundSeconds,
		&i.BreakSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSprintCandidate = `-- name: GetSprintCandidate :one
select sc.id, sc.sprint_id, sc.org_id, sc.application_id, sc.position, c.name as candidate_name, c.email as candidate_email
from sprint_candidate sc
join application a on a.id = sc.application_id
join candidate c on c.id = a.candidate_id
where sc.id = $1
`

type GetSprintCandidateRow struct {
	ID             uuid.UUID
	SprintID       uuid.UUID
	OrgID          uuid.UUID
	ApplicationID  uuid.UUID
	Position       int32
	CandidateName  string
	CandidateEmail string
}

func (q *Queries) GetSprintCandidate(ctx context.Context, id uuid.UUID) (GetSprintCandidateRow, error) {
	row := q.db.QueryRow(ctx, getSprintCandidate, id)
	var i GetSprintCandidateRow
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.OrgID,
		&i.ApplicationID,
		&i.Position,
		&i.CandidateName,
		&i.CandidateEmail,
	)
	return i, err
}

const getSprintForUpdate = `-- name: GetSprintForUpdate :one
select id, org_id, job_id, stage_id, name, status, starts_at, round_seconds, break_seconds, created_by, created_at, updated_at from sprint where id = $1 for update
`

func (q *Queries) GetSprintForUpdate(ctx context.Context, id uuid.UUID) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprintForUpdate, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.StageID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.RoundSeconds,
		&i.BreakSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSprintPairing = `-- name: GetSprintPairing :one
select id, sprint_id, org_id, round, interviewer_id, application_id from sprint_pairing where id = $1
`

func (q *Queries) GetSprintPairing(ctx context.Context, id uuid.UUID) (SprintPairing, error) {
	row := q.db.QueryRow(ctx, getSprintPairing, id)
	var i SprintPairing
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.OrgID,
		&i.Round,
		&i.InterviewerID,
		&i.ApplicationID,
	)
	return i, err
}

const hasSprintRatingForStage = `-- name: HasSprintRatingForStage :one
select exists (
    select 1 from sprint_rating r join sprint s on s.id = r.sprint_id
    where r.application_id = $1::uuid and s.stage_id = $2::uuid
)
`

type HasSprintRatingForStageParams struct {
	ApplicationID uuid.UUID
	StageID       uuid.UUID
}

// Whether any interviewer rated the application in a sprint of this stage.
func (q *Queries) HasSprintRatingForStage(ctx context.Context, arg HasSprintRatingForStageParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSprintRatingForStage, arg.ApplicationID, arg.StageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listQueueSprintRatingsMissing = `-- name: ListQueueSprintRatingsMissing :many
select p.id as pairing_id, s.id as sprint_id, s.name as sprint_name,
    u.name as interviewer_name, c.name as candidate_name, j.title as job_title, cc.name as client_name,
    (s.starts_at + make_interval(secs => (p.round + 1) * (s.round_seconds + s.break_seconds) - s.break_seconds))::timestamptz as ended_at
from sprint_pairing p
join sprint s on s.id = p.sprint_id
join org_user u on u.id = p.interviewer_id
join application a on a.id = p.application_id
join candidate c on c.id = a.candidate_id
join job j on j.id = s.job_id
join client_company cc on cc.id = j.client_company_id
left join sprint_rating r on r.pairing_id = p.id
where s.status = 'scheduled' and r.id is null
  and s.starts_at + make_interval(secs => (p.round + 1) * (s.round_seconds + s.break_seconds) - s.break_seconds) < now() - interval '5 minutes'
order by ended_at
`

type ListQueueSprintRatingsMissingRow struct {
	PairingID       uuid.UUID
	SprintID        uuid.UUID
	SprintName      string
	InterviewerName string
	CandidateName   string
	JobTitle        string
	ClientName      string
	EndedAt         pgtype.Timestamptz
}

// Conversations that ended more than five minutes ago and were never rated,
// on sprints that still stand.
func (q *Queries) ListQueueSprintRatingsMissing(ctx context.Context) ([]ListQueueSprintRatingsMissingRow, error) {
	rows, err := q.db.Query(ctx, listQueueSprintRatingsMissing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueSprintRatingsMissingRow{}
	for rows.Next() {
		var i ListQueueSprintRatingsMissingRow
		if err := rows.Scan(
			&i.PairingID,
			&i.SprintID,
			&i.SprintName,
			&i.InterviewerName,
			&i.CandidateName,
			&i.JobTitle,
			&i.ClientName,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintCandidates = `-- name: ListSprintCandidates :many
select sc.id, sc.application_id, sc.position, c.name as candidate_name, c.email as candidate_email,
    a.status as application_status, a.stage_id
from sprint_candidate sc
join application a on a.id = sc.application_id
join candidate c on c.id = a.candidate_id
where sc.sprint_id = $1
order by sc.position
`

type ListSprintCandidatesRow struct {
	ID                uuid.UUID
	ApplicationID     uuid.UUID
	Position          int32
	CandidateName     string
	CandidateEmail    string
	ApplicationStatus string
	StageID           uuid.UUID
}

func (q *Queries) ListSprintCandidates(ctx context.Context, sprintID uuid.UUID) ([]ListSprintCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSprintCandidates, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintCandidatesRow{}
	for rows.Next() {
		var i ListSprintCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Position,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.ApplicationStatus,
			&i.StageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintInterviewers = `-- name: ListSprintInterviewers :many
select i.user_id, i.position, u.name, u.email
from sprint_interviewer i
join org_user u on u.id = i.user_id
where i.sprint_id = $1
order by i.position
`

type ListSprintInterviewersRow struct {
	UserID   uuid.UUID
	Position int32
	Name     string
	Email    string
}

func (q *Queries) ListSprintInterviewers(ctx context.Context, sprintID uuid.UUID) ([]ListSprintInterviewersRow, error) {
	rows, err := q.db.Query(ctx, listSprintInterviewers, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintInterviewersRow{}
	for rows.Next() {
		var i ListSprintInterviewersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Position,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintPairings = `-- name: ListSprintPairings :many
select p.id, p.round, p.interviewer_id, p.application_id,
    u.name as interviewer_name, c.name as candidate_name, c.email as candidate_email,
    r.score, r.recommendation, r.note, r.updated_at as rated_at
from sprint_pairing p
join org_user u on u.id = p.interviewer_id
join application a on a.id = p.application_id
join candidate c on c.id = a.candidate_id
left join sprint_rating r on r.pairing_id = p.id
where p.sprint_id = $1
order by p.round, u.name, p.id
`

type ListSprintPairingsRow struct {
	ID              uuid.UUID
	Round           int32
	InterviewerID   uuid.UUID
	ApplicationID   uuid.UUID
	InterviewerName string
	CandidateName   string
	CandidateEmail  string
	Score           *int16
	Recommendation  *string
	Note            *string
	RatedAt         pgtype.Timestamptz
}

// Every conversation of a sprint with both names and the rating if filed.
func (q *Queries) ListSprintPairings(ctx context.Context, sprintID uuid.UUID) ([]ListSprintPairingsRow, error) {
	rows, err := q.db.Query(ctx, listSprintPairings, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintPairingsRow{}
	for rows.Next() {
		var i ListSprintPairingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Round,
			&i.InterviewerID,
			&i.ApplicationID,
			&i.InterviewerName,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.Score,
			&i.Recommendation,
			&i.Note,
			&i.RatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintRatingsForApplication = `-- name: ListSprintRatingsForApplication :many
select r.id, r.org_id, r.sprint_id, r.pairing_id, r.interviewer_id, r.application_id, r.score, r.recommendation, r.note, r.created_at, r.updated_at, s.name as sprint_name, u.name as interviewer_name
from sprint_rating r
join sprint s on s.id = r.sprint_id
join org_user u on u.id = r.interviewer_id
where r.application_id = $1
order by r.created_at
`

type ListSprintRatingsForApplicationRow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	SprintID        uuid.UUID
	PairingID       uuid.UUID
	InterviewerID   uuid.UUID
	ApplicationID   uuid.UUID
	Score           int16
	Recommendation  string
	Note            string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SprintName      string
	InterviewerName string
}

func (q *Queries) ListSprintRatingsForApplication(ctx context.Context, applicationID uuid.UUID) ([]ListSprintRatingsForApplicationRow, error) {
	rows, err := q.db.Query(ctx, listSprintRatingsForApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintRatingsForApplicationRow{}
	for rows.Next() {
		var i ListSprintRatingsForApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SprintID,
			&i.PairingID,
			&i.InterviewerID,
			&i.ApplicationID,
			&i.Score,
			&i.Recommendation,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SprintName,
			&i.InterviewerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprints = `-- name: ListSprints :many
select s.id, s.org_id, s.job_id, s.stage_id, s.name, s.status, s.starts_at, s.round_seconds, s.break_seconds, s.created_by, s.created_at, s.updated_at, j.title as job_title, st.name as stage_name,
    (select count(*) from sprint_candidate c where c.sprint_id = s.id) as candidates,
    (select count(*) from sprint_interviewer i where i.sprint_id = s.id) as interviewers
from sprint s
join job j on j.id = s.job_id
join stage st on st.id = s.stage_id
where s.org_id = $1
order by s.starts_at desc, s.id
`

type ListSprintsRow struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	JobID        uuid.UUID
	StageID      uuid.UUID
	Name         string
	Status       string
	StartsAt     pgtype.Timestamptz
	RoundSeconds int32
	BreakSeconds int32
	CreatedBy    uuid.NullUUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	JobTitle     string
	StageName    string
	Candidates   int64
	Interviewers int64
}

// Every sprint of the org, newest start first, with where it belongs.
func (q *Queries) ListSprints(ctx context.Context, orgID uuid.UUID) ([]ListSprintsRow, error) {
	rows, err := q.db.Query(ctx, listSprints, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintsRow{}
	for rows.Next() {
		var i ListSprintsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.JobID,
			&i.StageID,
			&i.Name,
			&i.Status,
			&i.StartsAt,
			&i.RoundSeconds,
			&i.BreakSeconds,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.StageName,
			&i.Candidates,
			&i.Interviewers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsForInterviewer = `-- name: ListSprintsForInterviewer :many
select s.id, s.org_id, s.job_id, s.stage_id, s.name, s.status, s.starts_at, s.round_seconds, s.break_seconds, s.created_by, s.created_at, s.updated_at, j.title as job_title
from sprint s
join sprint_interviewer i on i.sprint_id = s.id
join job j on j.id = s.job_id
where i.user_id = $1 and s.status = 'scheduled'
order by s.starts_at, s.id
`

type ListSprintsForInterviewerRow struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	JobID        uuid.UUID
	StageID      uuid.UUID
	Name         string
	Status       string
	StartsAt     pgtype.Timestamptz
	RoundSeconds int32
	BreakSeconds int32
	CreatedBy    uuid.NullUUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	JobTitle     string
}

// The sprints one user interviews in, soonest first.
func (q *Queries) ListSprintsForInterviewer(ctx context.Context, userID uuid.UUID) ([]ListSprintsForInterviewerRow, error) {
	rows, err := q.db.Query(ctx, listSprintsForInterviewer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintsForInterviewerRow{}
	for rows.Next() {
		var i ListSprintsForInterviewerRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.JobID,
			&i.StageID,
			&i.Name,
			&i.Status,
			&i.StartsAt,
			&i.RoundSeconds,
			&i.BreakSeconds,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsForStage = `-- name: ListSprintsForStage :many
select id, org_id, job_id, stage_id, name, status, starts_at, round_seconds, break_seconds, created_by, created_at, updated_at from sprint where stage_id = $1 and status <> 'cancelled' order by starts_at desc
`

func (q *Queries) ListSprintsForStage(ctx context.Context, stageID uuid.UUID) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listSprintsForStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.JobID,
			&i.StageID,
			&i.Name,
			&i.Status,
			&i.StartsAt,
			&i.RoundSeconds,
			&i.BreakSeconds,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSprintLinks = `-- name: RevokeSprintLinks :exec
update magic_link set revoked_at = now()
where purpose = 'sprint' and revoked_at is null
  and subject_id in (select id from sprint_candidate where sprint_id = $1)
`

func (q *Queries) RevokeSprintLinks(ctx context.Context, sprintID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSprintLinks, sprintID)
	return err
}

const setSprintStartsAt = `-- name: SetSprintStartsAt :one
update sprint set starts_at = $2, updated_at = now() where id = $1 returning id, org_id, job_id, stage_id, name, status, starts_at, round_seconds, break_seconds, created_by, created_at, updated_at
`

type SetSprintStartsAtParams struct {
	ID       uuid.UUID
	StartsAt pgtype.Timestamptz
}

func (q *Queries) SetSprintStartsAt(ctx context.Context, arg SetSprintStartsAtParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, setSprintStartsAt, arg.ID, arg.StartsAt)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.StageID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.RoundSeconds,
		&i.BreakSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSprintStatus = `-- name: SetSprintStatus :one
update sprint set status = $2, updated_at = now() where id = $1 returning id, org_id, job_id, stage_id, name, status, starts_at, round_seconds, break_seconds, created_by, created_at, updated_at
`

type SetSprintStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetSprintStatus(ctx context.Context, arg SetSprintStatusParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, setSprintStatus, arg.ID, arg.Status)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.StageID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.RoundSeconds,
		&i.BreakSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSprintDraft = `-- name: UpdateSprintDraft :one
update sprint set name = $2, starts_at = $3, round_seconds = $4, break_seconds = $5, updated_at = now()
where id = $1 and status = 'draft' returning id, org_id, job_id, stage_id, name, status, starts_at, round_seconds, break_seconds, created_by, created_at, updated_at
`

type UpdateSprintDraftParams struct {
	ID           uuid.UUID
	Name         string
	StartsAt     pgtype.Timestamptz
	RoundSeconds int32
	BreakSeconds int32
}

func (q *Queries) UpdateSprintDraft(ctx context.Context, arg UpdateSprintDraftParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, updateSprintDraft,
		arg.ID,
		arg.Name,
		arg.StartsAt,
		arg.RoundSeconds,
		arg.BreakSeconds,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.JobID,
		&i.StageID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.RoundSeconds,
		&i.BreakSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSprintRating = `-- name: UpsertSprintRating :one
insert into sprint_rating (org_id, sprint_id, pairing_id, interviewer_id, application_id, score, recommendation, note)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (pairing_id) do update
    set score = excluded.score, recommendation = excluded.recommendation, note = excluded.note, updated_at = now()
    where sprint_rating.interviewer_id = excluded.interviewer_id
returning id, org_id, sprint_id, pairing_id, interviewer_id, application_id, score, recommendation, note, created_at, updated_at
`

type UpsertSprintRatingParams struct {
	OrgID          uuid.UUID
	SprintID       uuid.UUID
	PairingID      uuid.UUID
	InterviewerID  uuid.UUID
	ApplicationID  uuid.UUID
	Score          int16
	Recommendation string
	Note           string
}

func (q *Queries) UpsertSprintRating(ctx context.Context, arg UpsertSprintRatingParams) (SprintRating, error) {
	row := q.db.QueryRow(ctx, upsertSprintRating,
		arg.OrgID,
		arg.SprintID,
		arg.PairingID,
		arg.InterviewerID,
		arg.ApplicationID,
		arg.Score,
		arg.Recommendation,
		arg.Note,
	)
	var i SprintRating
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SprintID,
		&i.PairingID,
		&i.InterviewerID,
		&i.ApplicationID,
		&i.Score,
		&i.Recommendation,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
