// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: talent.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const answerTalentIntro = `-- name: AnswerTalentIntro :execrows
update talent_intro set status = $2, application_id = $3, answered_at = now()
where id = $1 and status = 'sent'
`

type AnswerTalentIntroParams struct {
	ID            uuid.UUID
	Status        string
	ApplicationID uuid.NullUUID
}

func (q *Queries) AnswerTalentIntro(ctx context.Context, arg AnswerTalentIntroParams) (int64, error) {
	result, err := q.db.Exec(ctx, answerTalentIntro, arg.ID, arg.Status, arg.ApplicationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeTalentRequest = `-- name: CloseTalentRequest :execrows
update talent_request set status = 'closed', updated_at = now() where id = $1 and status = 'open'
`

func (q *Queries) CloseTalentRequest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, closeTalentRequest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countTalentIntroWaiting = `-- name: CountTalentIntroWaiting :one
select count(*) from talent_intro where org_id = $1 and status = 'requested'
`

func (q *Queries) CountTalentIntroWaiting(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTalentIntroWaiting, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTalentIntro = `-- name: CreateTalentIntro :one
insert into talent_intro (org_id, request_id, candidate_id, source, score)
values ($1, $2, $3, $4, $5)
returning id, org_id, request_id, candidate_id, source, score, status, job_id, application_id, sent_by, requested_at, sent_at, answered_at
`

type CreateTalentIntroParams struct {
	OrgID       uuid.UUID
	RequestID   uuid.UUID
	CandidateID uuid.UUID
	Source      string
	Score       float32
}

func (q *Queries) CreateTalentIntro(ctx context.Context, arg CreateTalentIntroParams) (TalentIntro, error) {
	row := q.db.QueryRow(ctx, createTalentIntro,
		arg.OrgID,
		arg.RequestID,
		arg.CandidateID,
		arg.Source,
		arg.Score,
	)
	var i TalentIntro
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestID,
		&i.CandidateID,
		&i.Source,
		&i.Score,
		&i.Status,
		&i.JobID,
		&i.ApplicationID,
		&i.SentBy,
		&i.RequestedAt,
		&i.SentAt,
		&i.AnsweredAt,
	)
	return i, err
}

const createTalentRequest = `-- name: CreateTalentRequest :one
insert into talent_request (org_id, client_company_id, client_user_id, job_id, title, skills, seniority, location, remote_policy, note)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
returning id, org_id, client_company_id, client_user_id, job_id, title, skills, seniority, location, remote_policy, note, status, created_at, updated_at
`

type CreateTalentRequestParams struct {
	OrgID           uuid.UUID
	ClientCompanyID uuid.UUID
	ClientUserID    uuid.NullUUID
	JobID           uuid.NullUUID
	Title           string
	Skills          []string
	Seniority       *string
	Location        *string
	RemotePolicy    *string
	Note            string
}

func (q *Queries) CreateTalentRequest(ctx context.Context, arg CreateTalentRequestParams) (TalentRequest, error) {
	row := q.db.QueryRow(ctx, createTalentRequest,
		arg.OrgID,
		arg.ClientCompanyID,
		arg.ClientUserID,
		arg.JobID,
		arg.Title,
		arg.Skills,
		arg.Seniority,
		arg.Location,
		arg.RemotePolicy,
		arg.Note,
	)
	var i TalentRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientCompanyID,
		&i.ClientUserID,
		&i.JobID,
		&i.Title,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemotePolicy,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dismissTalentIntro = `-- name: DismissTalentIntro :execrows
update talent_intro set status = 'dismissed', answered_at = now()
where id = $1 and status in ('requested', 'sent')
`

func (q *Queries) DismissTalentIntro(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, dismissTalentIntro, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTalentIntro = `-- name: GetTalentIntro :one
select i.id, i.org_id, i.request_id, i.candidate_id, i.source, i.score, i.status, i.job_id, i.application_id, i.sent_by, i.requested_at, i.sent_at, i.answered_at, c.name as candidate_name, c.email as candidate_email,
    r.title as request_title, r.client_company_id, cc.name as client_company_name, r.job_id as request_job_id
from talent_intro i
join candidate c on c.id = i.candidate_id
join talent_request r on r.id = i.request_id
join client_company cc on cc.id = r.client_company_id
where i.id = $1
`

type GetTalentIntroRow struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	RequestID         uuid.UUID
	CandidateID       uuid.UUID
	Source            string
	Score             float32
	Status            string
	JobID             uuid.NullUUID
	ApplicationID     uuid.NullUUID
	SentBy            uuid.NullUUID
	RequestedAt       pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	AnsweredAt        pgtype.Timestamptz
	CandidateName     string
	CandidateEmail    string
	RequestTitle      string
	ClientCompanyID   uuid.UUID
	ClientCompanyName string
	RequestJobID      uuid.NullUUID
}

func (q *Queries) GetTalentIntro(ctx context.Context, id uuid.UUID) (GetTalentIntroRow, error) {
	row := q.db.QueryRow(ctx, getTalentIntro, id)
	var i GetTalentIntroRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestID,
		&i.CandidateID,
		&i.Source,
		&i.Score,
		&i.Status,
		&i.JobID,
		&i.ApplicationID,
		&i.SentBy,
		&i.RequestedAt,
		&i.SentAt,
		&i.AnsweredAt,
		&i.CandidateName,
		&i.CandidateEmail,
		&i.RequestTitle,
		&i.ClientCompanyID,
		&i.ClientCompanyName,
		&i.RequestJobID,
	)
	return i, err
}

const getTalentProfile = `-- name: GetTalentProfile :one
select p.id, p.org_id, p.candidate_id, p.headline, p.skills, p.seniority, p.roles, p.location, p.remote_policy, p.salary_min, p.available_from, p.consent_at, p.withdrawn_at, p.created_at, p.updated_at, c.name as candidate_name, c.email as candidate_email, c.phone as candidate_phone, c.links as candidate_links,
    exists (select 1 from resume r where r.candidate_id = c.id) as has_resume
from talent_profile p
join candidate c on c.id = p.candidate_id
where p.id = $1
`

type GetTalentProfileRow struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	CandidateID    uuid.UUID
	Headline       string
	Skills         []string
	Seniority      *string
	Roles          []string
	Location       *string
	RemotePolicy   *string
	SalaryMin      *int32
	AvailableFrom  pgtype.Date
	ConsentAt      pgtype.Timestamptz
	WithdrawnAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CandidateName  string
	CandidateEmail string
	CandidatePhone *string
	CandidateLinks []byte
	HasResume      bool
}

func (q *Queries) GetTalentProfile(ctx context.Context, id uuid.UUID) (GetTalentProfileRow, error) {
	row := q.db.QueryRow(ctx, getTalentProfile, id)
	var i GetTalentProfileRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CandidateID,
		&i.Headline,
		&i.Skills,
		&i.Seniority,
		&i.Roles,
		&i.Location,
		&i.RemotePolicy,
		&i.SalaryMin,
		&i.AvailableFrom,
		&i.ConsentAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CandidateName,
		&i.CandidateEmail,
		&i.CandidatePhone,
		&i.CandidateLinks,
		&i.HasResume,
	)
	return i, err
}

const getTalentProfileByCandidate = `-- name: GetTalentProfileByCandidate :one
select id, org_id, candidate_id, headline, skills, seniority, roles, location, remote_policy, salary_min, available_from, consent_at, withdrawn_at, created_at, updated_at from talent_profile where candidate_id = $1
`

func (q *Queries) GetTalentProfileByCandidate(ctx context.Context, candidateID uuid.UUID) (TalentProfile, error) {
	row := q.db.QueryRow(ctx, getTalentProfileByCandidate, candidateID)
	var i TalentProfile
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CandidateID,
		&i.Headline,
		&i.Skills,
		&i.Seniority,
		&i.Roles,
		&i.Location,
		&i.RemotePolicy,
		&i.SalaryMin,
		&i.AvailableFrom,
		&i.ConsentAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTalentRequest = `-- name: GetTalentRequest :one
select r.id, r.org_id, r.client_company_id, r.client_user_id, r.job_id, r.title, r.skills, r.seniority, r.location, r.remote_policy, r.note, r.status, r.created_at, r.updated_at, cc.name as client_company_name, j.title as job_title
from talent_request r
join client_company cc on cc.id = r.client_company_id
left join job j on j.id = r.job_id
where r.id = $1
`

type GetTalentRequestRow struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	ClientCompanyID   uuid.UUID
	ClientUserID      uuid.NullUUID
	JobID             uuid.NullUUID
	Title             string
	Skills            []string
	Seniority         *string
	Location          *string
	RemotePolicy      *string
	Note              string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ClientCompanyName string
	JobTitle          *string
}

func (q *Queries) GetTalentRequest(ctx context.Context, id uuid.UUID) (GetTalentRequestRow, error) {
	row := q.db.QueryRow(ctx, getTalentRequest, id)
	var i GetTalentRequestRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientCompanyID,
		&i.ClientUserID,
		&i.JobID,
		&i.Title,
		&i.Skills,
		&i.Seniority,
		&i.Location,
		&i.RemotePolicy,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientCompanyName,
		&i.JobTitle,
	)
	return i, err
}

const listCandidateIDsAtCompany = `-- name: ListCandidateIDsAtCompany :many
select distinct a.candidate_id from application a where a.client_company_id = $1
`

// People already in a company's pipeline, on any of its jobs: a match the
// company has, or has had, is no introduction.
func (q *Queries) ListCandidateIDsAtCompany(ctx context.Context, clientCompanyID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCandidateIDsAtCompany, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var candidate_id uuid.UUID
		if err := rows.Scan(&candidate_id); err != nil {
			return nil, err
		}
		items = append(items, candidate_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenJobsByCompany = `-- name: ListOpenJobsByCompany :many
select id, org_id, client_company_id, title, description, skills, seniority, location, remote_policy, salary_min, salary_max, blind_mode, status, created_by, created_at, updated_at, slug, template_id from job where client_company_id = $1 and status = 'open' order by created_at desc
`

func (q *Queries) ListOpenJobsByCompany(ctx context.Context, clientCompanyID uuid.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listOpenJobsByCompany, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientCompanyID,
			&i.Title,
			&i.Description,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemotePolicy,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.BlindMode,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentIntrosByRequest = `-- name: ListTalentIntrosByRequest :many
select i.id, i.org_id, i.request_id, i.candidate_id, i.source, i.score, i.status, i.job_id, i.application_id, i.sent_by, i.requested_at, i.sent_at, i.answered_at, c.name as candidate_name, c.email as candidate_email
from talent_intro i
join candidate c on c.id = i.candidate_id
where i.request_id = $1
order by i.requested_at, i.id
`

type ListTalentIntrosByRequestRow struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	RequestID      uuid.UUID
	CandidateID    uuid.UUID
	Source         string
	Score          float32
	Status         string
	JobID          uuid.NullUUID
	ApplicationID  uuid.NullUUID
	SentBy         uuid.NullUUID
	RequestedAt    pgtype.Timestamptz
	SentAt         pgtype.Timestamptz
	AnsweredAt     pgtype.Timestamptz
	CandidateName  string
	CandidateEmail string
}

func (q *Queries) ListTalentIntrosByRequest(ctx context.Context, requestID uuid.UUID) ([]ListTalentIntrosByRequestRow, error) {
	rows, err := q.db.Query(ctx, listTalentIntrosByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentIntrosByRequestRow{}
	for rows.Next() {
		var i ListTalentIntrosByRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequestID,
			&i.CandidateID,
			&i.Source,
			&i.Score,
			&i.Status,
			&i.JobID,
			&i.ApplicationID,
			&i.SentBy,
			&i.RequestedAt,
			&i.SentAt,
			&i.AnsweredAt,
			&i.CandidateName,
			&i.CandidateEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentIntrosWaiting = `-- name: ListTalentIntrosWaiting :many
select i.id, i.request_id, i.requested_at, c.name as candidate_name,
    r.title as request_title, cc.name as client_name
from talent_intro i
join candidate c on c.id = i.candidate_id
join talent_request r on r.id = i.request_id
join client_company cc on cc.id = r.client_company_id
where i.status = 'requested'
order by i.requested_at, i.id
`

type ListTalentIntrosWaitingRow struct {
	ID            uuid.UUID
	RequestID     uuid.UUID
	RequestedAt   pgtype.Timestamptz
	CandidateName string
	RequestTitle  string
	ClientName    string
}

// Introductions a company asked for that no recruiter has sent yet: the
// work-queue rule.
func (q *Queries) ListTalentIntrosWaiting(ctx context.Context) ([]ListTalentIntrosWaitingRow, error) {
	rows, err := q.db.Query(ctx, listTalentIntrosWaiting)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentIntrosWaitingRow{}
	for rows.Next() {
		var i ListTalentIntrosWaitingRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RequestedAt,
			&i.CandidateName,
			&i.RequestTitle,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentPoolForMatching = `-- name: ListTalentPoolForMatching :many
select e.id, e.candidate_id, e.skills, e.seniority, e.location, e.remote_ok, e.updated_at,
    exists (select 1 from resume r where r.candidate_id = e.candidate_id) as has_resume,
    case when $2::text = '' then 0::real
         else ts_rank(c.search, websearch_to_tsquery('english', $2::text))::real end as text_rank
from talent_pool_entry e
join candidate c on c.id = e.candidate_id
where e.org_id = $1 and e.removed_at is null
limit $3::int
`

type ListTalentPoolForMatchingParams struct {
	OrgID    uuid.UUID
	Terms    string
	RowLimit int32
}

type ListTalentPoolForMatchingRow struct {
	ID          uuid.UUID
	CandidateID uuid.UUID
	Skills      []string
	Seniority   *string
	Location    *string
	RemoteOk    bool
	UpdatedAt   pgtype.Timestamptz
	HasResume   bool
	TextRank    float32
}

// The org's pool entries as the matcher sees them: the same terms, without
// the network's preferences. Their people applied to the org before, so a
// match here is an introduction the recruiter makes, not a promise made.
func (q *Queries) ListTalentPoolForMatching(ctx context.Context, arg ListTalentPoolForMatchingParams) ([]ListTalentPoolForMatchingRow, error) {
	rows, err := q.db.Query(ctx, listTalentPoolForMatching, arg.OrgID, arg.Terms, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentPoolForMatchingRow{}
	for rows.Next() {
		var i ListTalentPoolForMatchingRow
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemoteOk,
			&i.UpdatedAt,
			&i.HasResume,
			&i.TextRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentProfiles = `-- name: ListTalentProfiles :many
select p.id, p.org_id, p.candidate_id, p.headline, p.skills, p.seniority, p.roles, p.location, p.remote_policy, p.salary_min, p.available_from, p.consent_at, p.withdrawn_at, p.created_at, p.updated_at, c.name as candidate_name, c.email as candidate_email
from talent_profile p
join candidate c on c.id = p.candidate_id
where p.org_id = $1
  and ($2::bool or p.withdrawn_at is null)
  and ($3::text = ''
    or c.name ilike '%' || $3::text || '%'
    or p.headline ilike '%' || $3::text || '%'
    or exists (select 1 from unnest(p.skills) tag where tag ilike '%' || $3::text || '%')
    or exists (select 1 from unnest(p.roles) tag where tag ilike '%' || $3::text || '%')
    or c.search @@ websearch_to_tsquery('english', $3::text))
order by p.updated_at desc
limit $4::int
`

type ListTalentProfilesParams struct {
	OrgID            uuid.UUID
	IncludeWithdrawn bool
	Query            string
	RowLimit         int32
}

type ListTalentProfilesRow struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	CandidateID    uuid.UUID
	Headline       string
	Skills         []string
	Seniority      *string
	Roles          []string
	Location       *string
	RemotePolicy   *string
	SalaryMin      *int32
	AvailableFrom  pgtype.Date
	ConsentAt      pgtype.Timestamptz
	WithdrawnAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CandidateName  string
	CandidateEmail string
}

// The recruiter's view of the network, newest first, narrowed by a search
// over names, headlines, skills, roles, and résumé text.
func (q *Queries) ListTalentProfiles(ctx context.Context, arg ListTalentProfilesParams) ([]ListTalentProfilesRow, error) {
	rows, err := q.db.Query(ctx, listTalentProfiles,
		arg.OrgID,
		arg.IncludeWithdrawn,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentProfilesRow{}
	for rows.Next() {
		var i ListTalentProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CandidateID,
			&i.Headline,
			&i.Skills,
			&i.Seniority,
			&i.Roles,
			&i.Location,
			&i.RemotePolicy,
			&i.SalaryMin,
			&i.AvailableFrom,
			&i.ConsentAt,
			&i.WithdrawnAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateName,
			&i.CandidateEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentProfilesForMatching = `-- name: ListTalentProfilesForMatching :many
select p.id, p.candidate_id, p.headline, p.skills, p.seniority, p.roles, p.location, p.remote_policy,
    p.salary_min, p.available_from, p.updated_at,
    exists (select 1 from resume r where r.candidate_id = p.candidate_id) as has_resume,
    case when $2::text = '' then 0::real
         else ts_rank(c.search, websearch_to_tsquery('english', $2::text))::real end as text_rank
from talent_profile p
join candidate c on c.id = p.candidate_id
where p.org_id = $1 and p.withdrawn_at is null
limit $3::int
`

type ListTalentProfilesForMatchingParams struct {
	OrgID    uuid.UUID
	Terms    string
	RowLimit int32
}

type ListTalentProfilesForMatchingRow struct {
	ID            uuid.UUID
	CandidateID   uuid.UUID
	Headline      string
	Skills        []string
	Seniority     *string
	Roles         []string
	Location      *string
	RemotePolicy  *string
	SalaryMin     *int32
	AvailableFrom pgtype.Date
	UpdatedAt     pgtype.Timestamptz
	HasResume     bool
	TextRank      float32
}

// Every consenting profile with the fields the matcher scores, plus how
// well the résumé and name index answer the request's terms. The rank is
// zero when the request has no terms or the text says nothing about them.
func (q *Queries) ListTalentProfilesForMatching(ctx context.Context, arg ListTalentProfilesForMatchingParams) ([]ListTalentProfilesForMatchingRow, error) {
	rows, err := q.db.Query(ctx, listTalentProfilesForMatching, arg.OrgID, arg.Terms, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentProfilesForMatchingRow{}
	for rows.Next() {
		var i ListTalentProfilesForMatchingRow
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.Headline,
			&i.Skills,
			&i.Seniority,
			&i.Roles,
			&i.Location,
			&i.RemotePolicy,
			&i.SalaryMin,
			&i.AvailableFrom,
			&i.UpdatedAt,
			&i.HasResume,
			&i.TextRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentRequests = `-- name: ListTalentRequests :many
select r.id, r.org_id, r.client_company_id, r.client_user_id, r.job_id, r.title, r.skills, r.seniority, r.location, r.remote_policy, r.note, r.status, r.created_at, r.updated_at, cc.name as client_company_name, j.title as job_title,
    (select count(*) from talent_intro i where i.request_id = r.id)::int as intro_count,
    (select count(*) from talent_intro i where i.request_id = r.id and i.status = 'requested')::int as waiting_count
from talent_request r
join client_company cc on cc.id = r.client_company_id
left join job j on j.id = r.job_id
where r.org_id = $1
order by (r.status = 'open') desc, r.created_at desc
`

type ListTalentRequestsRow struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	ClientCompanyID   uuid.UUID
	ClientUserID      uuid.NullUUID
	JobID             uuid.NullUUID
	Title             string
	Skills            []string
	Seniority         *string
	Location          *string
	RemotePolicy      *string
	Note              string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ClientCompanyName string
	JobTitle          *string
	IntroCount        int32
	WaitingCount      int32
}

// The recruiter's list: every company's requests, open ones first, with
// how many introductions are waiting to be sent on each.
func (q *Queries) ListTalentRequests(ctx context.Context, orgID uuid.UUID) ([]ListTalentRequestsRow, error) {
	rows, err := q.db.Query(ctx, listTalentRequests, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentRequestsRow{}
	for rows.Next() {
		var i ListTalentRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientCompanyID,
			&i.ClientUserID,
			&i.JobID,
			&i.Title,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemotePolicy,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientCompanyName,
			&i.JobTitle,
			&i.IntroCount,
			&i.WaitingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalentRequestsByCompany = `-- name: ListTalentRequestsByCompany :many
select r.id, r.org_id, r.client_company_id, r.client_user_id, r.job_id, r.title, r.skills, r.seniority, r.location, r.remote_policy, r.note, r.status, r.created_at, r.updated_at, cc.name as client_company_name, j.title as job_title,
    (select count(*) from talent_intro i where i.request_id = r.id)::int as intro_count
from talent_request r
join client_company cc on cc.id = r.client_company_id
left join job j on j.id = r.job_id
where r.client_company_id = $1
order by r.created_at desc
`

type ListTalentRequestsByCompanyRow struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	ClientCompanyID   uuid.UUID
	ClientUserID      uuid.NullUUID
	JobID             uuid.NullUUID
	Title             string
	Skills            []string
	Seniority         *string
	Location          *string
	RemotePolicy      *string
	Note              string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ClientCompanyName string
	JobTitle          *string
	IntroCount        int32
}

func (q *Queries) ListTalentRequestsByCompany(ctx context.Context, clientCompanyID uuid.UUID) ([]ListTalentRequestsByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listTalentRequestsByCompany, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTalentRequestsByCompanyRow{}
	for rows.Next() {
		var i ListTalentRequestsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientCompanyID,
			&i.ClientUserID,
			&i.JobID,
			&i.Title,
			&i.Skills,
			&i.Seniority,
			&i.Location,
			&i.RemotePolicy,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientCompanyName,
			&i.JobTitle,
			&i.IntroCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTalentIntroSent = `-- name: MarkTalentIntroSent :execrows
update talent_intro set status = 'sent', job_id = $2, sent_by = $3, sent_at = now()
where id = $1 and status = 'requested'
`

type MarkTalentIntroSentParams struct {
	ID     uuid.UUID
	JobID  uuid.NullUUID
	SentBy uuid.NullUUID
}

func (q *Queries) MarkTalentIntroSent(ctx context.Context, arg MarkTalentIntroSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTalentIntroSent, arg.ID, arg.JobID, arg.SentBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejoinTalentProfile = `-- name: RejoinTalentProfile :execrows
update talent_profile set withdrawn_at = null, consent_at = now(), updated_at = now() where id = $1 and withdrawn_at is not null
`

func (q *Queries) RejoinTalentProfile(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, rejoinTalentProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTalentProfile = `-- name: UpdateTalentProfile :one
update talent_profile
set headline = $2, skills = $3, seniority = $4, roles = $5, location = $6, remote_policy = $7,
    salary_min = $8, available_from = $9, updated_at = now()
where id = $1
returning id, org_id, candidate_id, headline, skills, seniority, roles, location, remote_policy, salary_min, available_from, consent_at, withdrawn_at, created_at, updated_at
`

type UpdateTalentProfileParams struct {
	ID            uuid.UUID
	Headline      string
	Skills        []string
	Seniority     *string
	Roles         []string
	Location      *string
	RemotePolicy  *string
	SalaryMin     *int32
	AvailableFrom pgtype.Date
}

func (q *Queries) UpdateTalentProfile(ctx context.Context, arg UpdateTalentProfileParams) (TalentProfile, error) {
	row := q.db.QueryRow(ctx, updateTalentProfile,
		arg.ID,
		arg.Headline,
		arg.Skills,
		arg.Seniority,
		arg.Roles,
		arg.Location,
		arg.RemotePolicy,
		arg.SalaryMin,
		arg.AvailableFrom,
	)
	var i TalentProfile
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CandidateID,
		&i.Headline,
		&i.Skills,
		&i.Seniority,
		&i.Roles,
		&i.Location,
		&i.RemotePolicy,
		&i.SalaryMin,
		&i.AvailableFrom,
		&i.ConsentAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTalentProfile = `-- name: UpsertTalentProfile :one

insert into talent_profile (org_id, candidate_id, headline, skills, seniority, roles, location, remote_policy, salary_min, available_from)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
on conflict (org_id, candidate_id) do update
    set headline = excluded.headline, skills = excluded.skills, seniority = excluded.seniority,
        roles = excluded.roles, location = excluded.location, remote_policy = excluded.remote_policy,
        salary_min = excluded.salary_min, available_from = excluded.available_from,
        consent_at = now(), withdrawn_at = null, updated_at = now()
returning id, org_id, candidate_id, headline, skills, seniority, roles, location, remote_policy, salary_min, available_from, consent_at, withdrawn_at, created_at, updated_at
`

type UpsertTalentProfileParams struct {
	OrgID         uuid.UUID
	CandidateID   uuid.UUID
	Headline      string
	Skills        []string
	Seniority     *string
	Roles         []string
	Location      *string
	RemotePolicy  *string
	SalaryMin     *int32
	AvailableFrom pgtype.Date
}

// The talent network: profiles people keep with the org, the requests
// companies file against it, and the introductions between the two. Every
// query runs org-scoped; a client's reads go through the service, which
// anonymises before anything reaches the company.
// One profile per candidate. A returning member's submission replaces their
// details, renews consent, and reverses a withdrawal.
func (q *Queries) UpsertTalentProfile(ctx context.Context, arg UpsertTalentProfileParams) (TalentProfile, error) {
	row := q.db.QueryRow(ctx, upsertTalentProfile,
		arg.OrgID,
		arg.CandidateID,
		arg.Headline,
		arg.Skills,
		arg.Seniority,
		arg.Roles,
		arg.Location,
		arg.RemotePolicy,
		arg.SalaryMin,
		arg.AvailableFrom,
	)
	var i TalentProfile
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CandidateID,
		&i.Headline,
		&i.Skills,
		&i.Seniority,
		&i.Roles,
		&i.Location,
		&i.RemotePolicy,
		&i.SalaryMin,
		&i.AvailableFrom,
		&i.ConsentAt,
		&i.WithdrawnAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawTalentProfile = `-- name: WithdrawTalentProfile :execrows
update talent_profile set withdrawn_at = now(), updated_at = now() where id = $1 and withdrawn_at is null
`

func (q *Queries) WithdrawTalentProfile(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, withdrawTalentProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
