// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgUserRole = `-- name: AddOrgUserRole :exec
insert into org_user_role (org_user_id, org_id, role) values ($1, $2, $3) on conflict do nothing
`

type AddOrgUserRoleParams struct {
	OrgUserID uuid.UUID
	OrgID     uuid.UUID
	Role      string
}

func (q *Queries) AddOrgUserRole(ctx context.Context, arg AddOrgUserRoleParams) error {
	_, err := q.db.Exec(ctx, addOrgUserRole, arg.OrgUserID, arg.OrgID, arg.Role)
	return err
}

const createClientCompany = `-- name: CreateClientCompany :one
insert into client_company (org_id, name) values ($1, $2) returning id, org_id, name, created_at
`

type CreateClientCompanyParams struct {
	OrgID uuid.UUID
	Name  string
}

func (q *Queries) CreateClientCompany(ctx context.Context, arg CreateClientCompanyParams) (ClientCompany, error) {
	row := q.db.QueryRow(ctx, createClientCompany, arg.OrgID, arg.Name)
	var i ClientCompany
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createClientUser = `-- name: CreateClientUser :one
insert into client_user (org_id, client_company_id, email, name, timezone)
values ($1, $2, $3, $4, $5) returning id, org_id, client_company_id, email, name, timezone, created_at
`

type CreateClientUserParams struct {
	OrgID           uuid.UUID
	ClientCompanyID uuid.UUID
	Email           string
	Name            string
	Timezone        string
}

func (q *Queries) CreateClientUser(ctx context.Context, arg CreateClientUserParams) (ClientUser, error) {
	row := q.db.QueryRow(ctx, createClientUser,
		arg.OrgID,
		arg.ClientCompanyID,
		arg.Email,
		arg.Name,
		arg.Timezone,
	)
	var i ClientUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientCompanyID,
		&i.Email,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const createMagicLink = `-- name: CreateMagicLink :one
insert into magic_link (org_id, token_hash, purpose, subject_id, expires_at)
values ($1, $2, $3, $4, $5) returning id, org_id, token_hash, purpose, subject_id, expires_at, used_at, revoked_at, created_at
`

type CreateMagicLinkParams struct {
	OrgID     uuid.UUID
	TokenHash string
	Purpose   string
	SubjectID uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, createMagicLink,
		arg.OrgID,
		arg.TokenHash,
		arg.Purpose,
		arg.SubjectID,
		arg.ExpiresAt,
	)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TokenHash,
		&i.Purpose,
		&i.SubjectID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOrg = `-- name: CreateOrg :one
insert into org (name, slug) values ($1, $2) returning id, name, slug, created_at
`

type CreateOrgParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.Slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const createOrgUser = `-- name: CreateOrgUser :one
insert into org_user (org_id, email, name, timezone)
values ($1, $2, $3, $4) returning id, org_id, email, name, timezone, created_at
`

type CreateOrgUserParams struct {
	OrgID    uuid.UUID
	Email    string
	Name     string
	Timezone string
}

func (q *Queries) CreateOrgUser(ctx context.Context, arg CreateOrgUserParams) (OrgUser, error) {
	row := q.db.QueryRow(ctx, createOrgUser,
		arg.OrgID,
		arg.Email,
		arg.Name,
		arg.Timezone,
	)
	var i OrgUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const createPipelineTemplate = `-- name: CreatePipelineTemplate :one
insert into pipeline_template (org_id, name, is_default) values ($1, $2, $3) returning id, org_id, name, is_default, created_at
`

type CreatePipelineTemplateParams struct {
	OrgID     uuid.UUID
	Name      string
	IsDefault bool
}

func (q *Queries) CreatePipelineTemplate(ctx context.Context, arg CreatePipelineTemplateParams) (PipelineTemplate, error) {
	row := q.db.QueryRow(ctx, createPipelineTemplate, arg.OrgID, arg.Name, arg.IsDefault)
	var i PipelineTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createPipelineTemplateStage = `-- name: CreatePipelineTemplateStage :one
insert into pipeline_template_stage (org_id, template_id, position, name, kind, unblind)
values ($1, $2, $3, $4, $5, $6) returning id, org_id, template_id, position, name, kind, unblind
`

type CreatePipelineTemplateStageParams struct {
	OrgID      uuid.UUID
	TemplateID uuid.UUID
	Position   int32
	Name       string
	Kind       string
	Unblind    bool
}

func (q *Queries) CreatePipelineTemplateStage(ctx context.Context, arg CreatePipelineTemplateStageParams) (PipelineTemplateStage, error) {
	row := q.db.QueryRow(ctx, createPipelineTemplateStage,
		arg.OrgID,
		arg.TemplateID,
		arg.Position,
		arg.Name,
		arg.Kind,
		arg.Unblind,
	)
	var i PipelineTemplateStage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateID,
		&i.Position,
		&i.Name,
		&i.Kind,
		&i.Unblind,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
insert into session (org_id, org_user_id, client_user_id, token_hash, expires_at)
values ($1, $2, $3, $4, $5) returning id, org_id, org_user_id, client_user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	OrgID        uuid.UUID
	OrgUserID    uuid.NullUUID
	ClientUserID uuid.NullUUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.OrgID,
		arg.OrgUserID,
		arg.ClientUserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgUserID,
		&i.ClientUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrgUserRoles = `-- name: DeleteOrgUserRoles :exec
delete from org_user_role where org_user_id = $1
`

func (q *Queries) DeleteOrgUserRoles(ctx context.Context, orgUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrgUserRoles, orgUserID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from session where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getClientCompany = `-- name: GetClientCompany :one
select id, org_id, name, created_at from client_company where id = $1 and org_id = $2
`

type GetClientCompanyParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetClientCompany(ctx context.Context, arg GetClientCompanyParams) (ClientCompany, error) {
	row := q.db.QueryRow(ctx, getClientCompany, arg.ID, arg.OrgID)
	var i ClientCompany
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultPipelineTemplate = `-- name: GetDefaultPipelineTemplate :one
select id, org_id, name, is_default, created_at from pipeline_template where org_id = $1 and is_default
`

func (q *Queries) GetDefaultPipelineTemplate(ctx context.Context, orgID uuid.UUID) (PipelineTemplate, error) {
	row := q.db.QueryRow(ctx, getDefaultPipelineTemplate, orgID)
	var i PipelineTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getOrg = `-- name: GetOrg :one
select id, name, slug, created_at from org where id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
select id, name, slug, created_at from org where slug = $1
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgSetting = `-- name: GetOrgSetting :one
select value from org_setting where org_id = $1 and key = $2
`

type GetOrgSettingParams struct {
	OrgID uuid.UUID
	Key   string
}

func (q *Queries) GetOrgSetting(ctx context.Context, arg GetOrgSettingParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOrgSetting, arg.OrgID, arg.Key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getOrgUser = `-- name: GetOrgUser :one
select id, org_id, email, name, timezone, created_at from org_user where id = $1 and org_id = $2
`

type GetOrgUserParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetOrgUser(ctx context.Context, arg GetOrgUserParams) (OrgUser, error) {
	row := q.db.QueryRow(ctx, getOrgUser, arg.ID, arg.OrgID)
	var i OrgUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgUserByEmail = `-- name: GetOrgUserByEmail :one
select id, org_id, email, name, timezone, created_at from org_user where org_id = $1 and lower(email) = lower($2)
`

type GetOrgUserByEmailParams struct {
	OrgID uuid.UUID
	Lower string
}

func (q *Queries) GetOrgUserByEmail(ctx context.Context, arg GetOrgUserByEmailParams) (OrgUser, error) {
	row := q.db.QueryRow(ctx, getOrgUserByEmail, arg.OrgID, arg.Lower)
	var i OrgUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgUserCredential = `-- name: GetOrgUserCredential :one
select org_user_id, org_id, password_hash, disabled_at, updated_at from org_user_credential where org_user_id = $1
`

func (q *Queries) GetOrgUserCredential(ctx context.Context, orgUserID uuid.UUID) (OrgUserCredential, error) {
	row := q.db.QueryRow(ctx, getOrgUserCredential, orgUserID)
	var i OrgUserCredential
	err := row.Scan(
		&i.OrgUserID,
		&i.OrgID,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientCompanies = `-- name: ListClientCompanies :many
select id, org_id, name, created_at from client_company where org_id = $1 order by name
`

func (q *Queries) ListClientCompanies(ctx context.Context, orgID uuid.UUID) ([]ClientCompany, error) {
	rows, err := q.db.Query(ctx, listClientCompanies, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientCompany{}
	for rows.Next() {
		var i ClientCompany
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientUsers = `-- name: ListClientUsers :many
select id, org_id, client_company_id, email, name, timezone, created_at from client_user where org_id = $1 order by name
`

func (q *Queries) ListClientUsers(ctx context.Context, orgID uuid.UUID) ([]ClientUser, error) {
	rows, err := q.db.Query(ctx, listClientUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientUser{}
	for rows.Next() {
		var i ClientUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientCompanyID,
			&i.Email,
			&i.Name,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgSettings = `-- name: ListOrgSettings :many
select org_id, key, value, updated_at from org_setting where org_id = $1 order by key
`

func (q *Queries) ListOrgSettings(ctx context.Context, orgID uuid.UUID) ([]OrgSetting, error) {
	rows, err := q.db.Query(ctx, listOrgSettings, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgSetting{}
	for rows.Next() {
		var i OrgSetting
		if err := rows.Scan(
			&i.OrgID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUserRoles = `-- name: ListOrgUserRoles :many
select role from org_user_role where org_user_id = $1 order by role
`

func (q *Queries) ListOrgUserRoles(ctx context.Context, orgUserID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOrgUserRoles, orgUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUserRolesForOrg = `-- name: ListOrgUserRolesForOrg :many
select org_user_id, role from org_user_role where org_id = $1 order by org_user_id, role
`

type ListOrgUserRolesForOrgRow struct {
	OrgUserID uuid.UUID
	Role      string
}

func (q *Queries) ListOrgUserRolesForOrg(ctx context.Context, orgID uuid.UUID) ([]ListOrgUserRolesForOrgRow, error) {
	rows, err := q.db.Query(ctx, listOrgUserRolesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgUserRolesForOrgRow{}
	for rows.Next() {
		var i ListOrgUserRolesForOrgRow
		if err := rows.Scan(&i.OrgUserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUsers = `-- name: ListOrgUsers :many
select id, org_id, email, name, timezone, created_at from org_user where org_id = $1 order by name
`

func (q *Queries) ListOrgUsers(ctx context.Context, orgID uuid.UUID) ([]OrgUser, error) {
	rows, err := q.db.Query(ctx, listOrgUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgUser{}
	for rows.Next() {
		var i OrgUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineTemplateStages = `-- name: ListPipelineTemplateStages :many
select id, org_id, template_id, position, name, kind, unblind from pipeline_template_stage where template_id = $1 order by position
`

func (q *Queries) ListPipelineTemplateStages(ctx context.Context, templateID uuid.UUID) ([]PipelineTemplateStage, error) {
	rows, err := q.db.Query(ctx, listPipelineTemplateStages, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineTemplateStage{}
	for rows.Next() {
		var i PipelineTemplateStage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TemplateID,
			&i.Position,
			&i.Name,
			&i.Kind,
			&i.Unblind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAPIToken = `-- name: LookupAPIToken :one
select id, org_id, org_user_id, name, token_hash, created_at, revoked_at from api_token where token_hash = $1 and revoked_at is null
`

func (q *Queries) LookupAPIToken(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, lookupAPIToken, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgUserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lookupClientUsersByEmail = `-- name: LookupClientUsersByEmail :many
select u.id, u.org_id, u.client_company_id, u.email, u.name, u.timezone, u.created_at, c.password_hash
from client_user u join client_user_credential c on c.client_user_id = u.id
where lower(u.email) = lower($1) and c.disabled_at is null
`

type LookupClientUsersByEmailRow struct {
	ClientUser   ClientUser
	PasswordHash string
}

func (q *Queries) LookupClientUsersByEmail(ctx context.Context, lower string) ([]LookupClientUsersByEmailRow, error) {
	rows, err := q.db.Query(ctx, lookupClientUsersByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupClientUsersByEmailRow{}
	for rows.Next() {
		var i LookupClientUsersByEmailRow
		if err := rows.Scan(
			&i.ClientUser.ID,
			&i.ClientUser.OrgID,
			&i.ClientUser.ClientCompanyID,
			&i.ClientUser.Email,
			&i.ClientUser.Name,
			&i.ClientUser.Timezone,
			&i.ClientUser.CreatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupMagicLink = `-- name: LookupMagicLink :one
select id, org_id, token_hash, purpose, subject_id, expires_at, used_at, revoked_at, created_at from magic_link where token_hash = $1
`

func (q *Queries) LookupMagicLink(ctx context.Context, tokenHash string) (MagicLink, error) {
	row := q.db.QueryRow(ctx, lookupMagicLink, tokenHash)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TokenHash,
		&i.Purpose,
		&i.SubjectID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lookupOrgUsersByEmail = `-- name: LookupOrgUsersByEmail :many
select u.id, u.org_id, u.email, u.name, u.timezone, u.created_at, c.password_hash
from org_user u join org_user_credential c on c.org_user_id = u.id
where lower(u.email) = lower($1) and c.disabled_at is null
`

type LookupOrgUsersByEmailRow struct {
	OrgUser      OrgUser
	PasswordHash string
}

func (q *Queries) LookupOrgUsersByEmail(ctx context.Context, lower string) ([]LookupOrgUsersByEmailRow, error) {
	rows, err := q.db.Query(ctx, lookupOrgUsersByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupOrgUsersByEmailRow{}
	for rows.Next() {
		var i LookupOrgUsersByEmailRow
		if err := rows.Scan(
			&i.OrgUser.ID,
			&i.OrgUser.OrgID,
			&i.OrgUser.Email,
			&i.OrgUser.Name,
			&i.OrgUser.Timezone,
			&i.OrgUser.CreatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupSession = `-- name: LookupSession :one
select id, org_id, org_user_id, client_user_id, token_hash, expires_at, created_at from session where token_hash = $1 and expires_at > now()
`

func (q *Queries) LookupSession(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, lookupSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgUserID,
		&i.ClientUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :execrows
update magic_link set used_at = now()
where id = $1 and used_at is null and revoked_at is null and expires_at > now()
`

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markMagicLinkUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertClientUserCredential = `-- name: UpsertClientUserCredential :exec
insert into client_user_credential (client_user_id, org_id, password_hash) values ($1, $2, $3)
on conflict (client_user_id) do update set password_hash = excluded.password_hash, updated_at = now()
`

type UpsertClientUserCredentialParams struct {
	ClientUserID uuid.UUID
	OrgID        uuid.UUID
	PasswordHash string
}

func (q *Queries) UpsertClientUserCredential(ctx context.Context, arg UpsertClientUserCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertClientUserCredential, arg.ClientUserID, arg.OrgID, arg.PasswordHash)
	return err
}

const upsertOrgSetting = `-- name: UpsertOrgSetting :exec
insert into org_setting (org_id, key, value) values ($1, $2, $3)
on conflict (org_id, key) do update set value = excluded.value, updated_at = now()
`

type UpsertOrgSettingParams struct {
	OrgID uuid.UUID
	Key   string
	Value []byte
}

func (q *Queries) UpsertOrgSetting(ctx context.Context, arg UpsertOrgSettingParams) error {
	_, err := q.db.Exec(ctx, upsertOrgSetting, arg.OrgID, arg.Key, arg.Value)
	return err
}

const upsertOrgUserCredential = `-- name: UpsertOrgUserCredential :exec
insert into org_user_credential (org_user_id, org_id, password_hash) values ($1, $2, $3)
on conflict (org_user_id) do update set password_hash = excluded.password_hash, updated_at = now()
`

type UpsertOrgUserCredentialParams struct {
	OrgUserID    uuid.UUID
	OrgID        uuid.UUID
	PasswordHash string
}

func (q *Queries) UpsertOrgUserCredential(ctx context.Context, arg UpsertOrgUserCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertOrgUserCredential, arg.OrgUserID, arg.OrgID, arg.PasswordHash)
	return err
}
