// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workqueue.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNavSubjects = `-- name: CountNavSubjects :one
select
    (select count(*) from client_company cc where cc.org_id = $1)::int as clients,
    (select count(*) from candidate c where c.org_id = $1)::int as candidates,
    (select count(*) from problem pr where pr.org_id = $1)::int as problems,
    (select count(*) from assessment asm where asm.org_id = $1)::int as assessments
`

type CountNavSubjectsRow struct {
	Clients     int32
	Candidates  int32
	Problems    int32
	Assessments int32
}

// The sidebar's non-queue counts, in one round trip.
func (q *Queries) CountNavSubjects(ctx context.Context, orgID uuid.UUID) (CountNavSubjectsRow, error) {
	row := q.db.QueryRow(ctx, countNavSubjects, orgID)
	var i CountNavSubjectsRow
	err := row.Scan(
		&i.Clients,
		&i.Candidates,
		&i.Problems,
		&i.Assessments,
	)
	return i, err
}

const listActiveQueueSnoozes = `-- name: ListActiveQueueSnoozes :many
select kind, subject_id from queue_snooze where user_id = $1 and until > now()
`

type ListActiveQueueSnoozesRow struct {
	Kind      string
	SubjectID uuid.UUID
}

// A snooze hides the item from the one user who set it, until it lapses.
func (q *Queries) ListActiveQueueSnoozes(ctx context.Context, userID uuid.UUID) ([]ListActiveQueueSnoozesRow, error) {
	rows, err := q.db.Query(ctx, listActiveQueueSnoozes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveQueueSnoozesRow{}
	for rows.Next() {
		var i ListActiveQueueSnoozesRow
		if err := rows.Scan(&i.Kind, &i.SubjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueClientWaiting = `-- name: ListQueueClientWaiting :many
select distinct on (a.id)
    a.id as application_id, e.created_at, e.reason as message,
    c.name as candidate_name, j.title as job_title, cc.name as client_name
from application_event e
join application a on a.id = e.application_id
join candidate c on c.id = a.candidate_id
join job j on j.id = a.job_id
join client_company cc on cc.id = j.client_company_id
where e.kind = $1::text
    and not exists (
        select 1 from application_event later
        where later.application_id = e.application_id
            and later.actor_kind = 'org_user'
            and later.created_at > e.created_at)
order by a.id, e.created_at
`

type ListQueueClientWaitingRow struct {
	ApplicationID uuid.UUID
	CreatedAt     pgtype.Timestamptz
	Message       *string
	CandidateName string
	JobTitle      string
	ClientName    string
}

// The client asked a question and no org user has touched the application
// since: every recruiter reply lands on the timeline, so a later org_user
// event is the answer. The oldest unanswered question per application wins,
// because that is how long the client has been waiting.
func (q *Queries) ListQueueClientWaiting(ctx context.Context, requestKind string) ([]ListQueueClientWaitingRow, error) {
	rows, err := q.db.Query(ctx, listQueueClientWaiting, requestKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueClientWaitingRow{}
	for rows.Next() {
		var i ListQueueClientWaitingRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.CreatedAt,
			&i.Message,
			&i.CandidateName,
			&i.JobTitle,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueExpiring = `-- name: ListQueueExpiring :many
select t.id as attempt_id, a.id as application_id, c.name as candidate_name,
    t.invite_expires_at, j.title as job_title, cc.name as client_name
from attempt t
join application a on a.id = t.application_id
join candidate c on c.id = a.candidate_id
join job j on j.id = a.job_id
join client_company cc on cc.id = j.client_company_id
where t.status = 'invited' and not t.preview
    and t.invite_expires_at is not null
    and t.invite_expires_at < now() + interval '24 hours'
order by t.invite_expires_at, t.id
`

type ListQueueExpiringRow struct {
	AttemptID       uuid.UUID
	ApplicationID   uuid.UUID
	CandidateName   string
	InviteExpiresAt pgtype.Timestamptz
	JobTitle        string
	ClientName      string
}

// An invite runs out within the day and the candidate has not started. An
// invite already past its window still counts: nothing sweeps it, and the
// recruiter is the one who has to re-issue it.
func (q *Queries) ListQueueExpiring(ctx context.Context) ([]ListQueueExpiringRow, error) {
	rows, err := q.db.Query(ctx, listQueueExpiring)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueExpiringRow{}
	for rows.Next() {
		var i ListQueueExpiringRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.ApplicationID,
			&i.CandidateName,
			&i.InviteExpiresAt,
			&i.JobTitle,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueReview = `-- name: ListQueueReview :many

select t.id as attempt_id, a.id as application_id, c.name as candidate_name,
    t.score, t.finished_at, j.title as job_title, cc.name as client_name
from attempt t
join application a on a.id = t.application_id
join candidate c on c.id = a.candidate_id
join job j on j.id = a.job_id
join client_company cc on cc.id = j.client_company_id
left join review r on r.attempt_id = t.id
where t.status = 'scored' and not t.preview and r.id is null
order by t.finished_at, t.id
`

type ListQueueReviewRow struct {
	AttemptID     uuid.UUID
	ApplicationID uuid.UUID
	CandidateName string
	Score         pgtype.Numeric
	FinishedAt    pgtype.Timestamptz
	JobTitle      string
	ClientName    string
}

// The work queue is a read model: one query per rule, unioned in Go, so a
// rule can be read and tested on its own. Preview sittings are the
// recruiter's rehearsal and never raise work.
// A sitting has been scored and nobody has reviewed it yet.
func (q *Queries) ListQueueReview(ctx context.Context) ([]ListQueueReviewRow, error) {
	rows, err := q.db.Query(ctx, listQueueReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueReviewRow{}
	for rows.Next() {
		var i ListQueueReviewRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.ApplicationID,
			&i.CandidateName,
			&i.Score,
			&i.FinishedAt,
			&i.JobTitle,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueScorecardsOverdue = `-- name: ListQueueScorecardsOverdue :many
select s.id as slot_id, s.application_id, s.stage_id, s.ends_at,
    c.name as candidate_name, u.name as vetter_name, st.name as stage_name,
    j.title as job_title, cc.name as client_name
from interview_slot s
join application a on a.id = s.application_id
join stage st on st.id = s.stage_id
join candidate c on c.id = a.candidate_id
join org_user u on u.id = s.vetter_id
join job j on j.id = a.job_id
join client_company cc on cc.id = j.client_company_id
where s.status in ('booked', 'completed')
    and s.ends_at < now() - interval '24 hours'
    and not exists (
        select 1 from scorecard sc
        where sc.application_id = s.application_id and sc.stage_id = s.stage_id)
order by s.ends_at, s.id
`

type ListQueueScorecardsOverdueRow struct {
	SlotID        uuid.UUID
	ApplicationID uuid.NullUUID
	StageID       uuid.NullUUID
	EndsAt        pgtype.Timestamptz
	CandidateName string
	VetterName    string
	StageName     string
	JobTitle      string
	ClientName    string
}

// The interview finished more than a day ago and its scorecard is missing.
func (q *Queries) ListQueueScorecardsOverdue(ctx context.Context) ([]ListQueueScorecardsOverdueRow, error) {
	rows, err := q.db.Query(ctx, listQueueScorecardsOverdue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueScorecardsOverdueRow{}
	for rows.Next() {
		var i ListQueueScorecardsOverdueRow
		if err := rows.Scan(
			&i.SlotID,
			&i.ApplicationID,
			&i.StageID,
			&i.EndsAt,
			&i.CandidateName,
			&i.VetterName,
			&i.StageName,
			&i.JobTitle,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueShortlistDrafts = `-- name: ListQueueShortlistDrafts :many
select p.id as packet_id, p.job_id, p.updated_at,
    j.title as job_title, cc.name as client_name,
    (select count(*) from shortlist_pick k where k.packet_id = p.id)::int as picks
from shortlist_packet p
join job j on j.id = p.job_id
join client_company cc on cc.id = j.client_company_id
where p.status = 'draft'
order by p.updated_at, p.id
`

type ListQueueShortlistDraftsRow struct {
	PacketID   uuid.UUID
	JobID      uuid.UUID
	UpdatedAt  pgtype.Timestamptz
	JobTitle   string
	ClientName string
	Picks      int32
}

// A packet was built and never sent; the client is waiting on a decision
// that has already been made.
func (q *Queries) ListQueueShortlistDrafts(ctx context.Context) ([]ListQueueShortlistDraftsRow, error) {
	rows, err := q.db.Query(ctx, listQueueShortlistDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueShortlistDraftsRow{}
	for rows.Next() {
		var i ListQueueShortlistDraftsRow
		if err := rows.Scan(
			&i.PacketID,
			&i.JobID,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.ClientName,
			&i.Picks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQueueSnooze = `-- name: UpsertQueueSnooze :exec
insert into queue_snooze (org_id, user_id, kind, subject_id, until)
values ($1, $2, $3, $4, $5)
on conflict (user_id, kind, subject_id) do update set until = excluded.until
`

type UpsertQueueSnoozeParams struct {
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Kind      string
	SubjectID uuid.UUID
	Until     pgtype.Timestamptz
}

func (q *Queries) UpsertQueueSnooze(ctx context.Context, arg UpsertQueueSnoozeParams) error {
	_, err := q.db.Exec(ctx, upsertQueueSnooze,
		arg.OrgID,
		arg.UserID,
		arg.Kind,
		arg.SubjectID,
		arg.Until,
	)
	return err
}
